### ISSUE TITLE
README data  not showing on npm.js website .

### ISSUE THREAD

**Issue by sahilbakoru** [react-native-async-storage/async-storage#1011]
## The readme file docs not found or showing on npmjs.com for  @react-native-async-storage/async-storage .

<img width="1279" alt="Screenshot 2023-09-18 at 5 24 30 PM" src="https://github.com/react-native-async-storage/async-storage/assets/68190549/8630d7e5-9ca7-47c1-85c1-642509a643d8">

 

### Version

1.19.3

### What platforms are you seeing this issue on?

- [x] Android
- [ ] iOS
- [X] macOS
- [ ] Windows
- [X] web

### System Information

```true
System:
    OS: macOS 11.7.9
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 65.15 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.20.1 - /usr/local/opt/node@16/bin/node
    Yarn: Not Found
    npm: 8.19.4 - /usr/local/opt/node@16/bin/npm
    Watchman: 2023.07.24.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.2/13C90 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

Just go to   https://www.npmjs.com/package/@react-native-async-storage/async-storage?activeTab=readme  .

<img width="1279" alt="Screenshot 2023-09-18 at 5 24 30 PM" src="https://github.com/react-native-async-storage/async-storage/assets/68190549/817f3232-ba86-4b29-9bda-db5aa4fee573">

**Comment by tido64** [comment]
Thanks for reporting this. This is probably caused by us migrating to a monorepo setup. FWIW, you can still access is from here: https://github.com/react-native-async-storage/async-storage#readme

I think we just need to publish a new version for npm to update the page.
