### ISSUE TITLE
Project with path ':@react-native-community_async-storage' could not be found in project ':app'.

### ISSUE THREAD

**Issue by Florent75** [react-native-async-storage/async-storage#1017]
### What happened?

I update my RN from 0.62 to 0.71.

Then I did npx react-native start --reset-cache

I got the following error : 

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/florent/Bocoloco/hermes/android/app/build.gradle' line: 169

* What went wrong:
A problem occurred evaluating project ':app'.
> Project with path ':@react-native-community_async-storage' could not be found in project ':app'.

I have checked previous similar issue. One stuff I don't  get is that I am supposed to remove manual linking, but I have never put it in place.

So my main question is : should I do something to remove manual linking ? Something specific to this repo ?

### Version

1.17.11

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
System:
    OS: macOS 13.5.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 460.41 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.15.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 16.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.0 => 0.71.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

Install package and  try to start the android app

**Comment by krizzu** [comment]
What exactly is at line 169 in your build.gradle?

**Comment by Florent75** [comment]
Hi Krizzu,

Thanks fo your quick answer. You were right, I forgot to remove an old try I did on line 169.

After removing it : 
I have now the following error :  
* Where:
Script '/Users/florent/Bocoloco/hermes/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 195

* What went wrong:
A problem occurred evaluating project ':app'.
> Project with path ':react-native-async-storage_async-storage' could not be found in project ':app'.

When I check in line 195, here is what I have  : 
  /**
   * Adds the react native modules as dependencies to the users `app` project
   */
  void addReactNativeModuleDependencies(Project appProject) {
    reactNativeModules.forEach { reactNativeModule ->
      def nameCleansed = reactNativeModule["nameCleansed"]
      def dependencyConfiguration = reactNativeModule["dependencyConfiguration"]
      appProject.dependencies {
        if (reactNativeModulesBuildVariants.containsKey(nameCleansed)) {
          reactNativeModulesBuildVariants
            .get(nameCleansed)
            .forEach { buildVariant -> 
              if(dependencyConfiguration != null) {
                "${buildVariant}${dependencyConfiguration}"
              } else {
                "${buildVariant}Implementation" project(path: ":${nameCleansed}")
              }
            }
        } else {
          if(dependencyConfiguration != null) {
            "${dependencyConfiguration}"
          } else {
//                this.logger.error("${nameCleansed}")
             implementation project(path: ":${nameCleansed}")
          }
        }
      }
    }
  }

Any ideas ?

**Comment by izzyiscodingsomehow** [comment]
bump same problem

**Comment by krizzu** [comment]
I'd need more repro step help out.
When upgrading to 70+, make sure your project has proper setup, because RN changed how native modules are linked together. I prefer using Upgrade Helper tool to not miss anything, [see RN docs about upgrade](https://reactnative.dev/docs/upgrading#upgrade-helper)

**Comment by MarioBanovac** [comment]
I have the same problem as the author of this issue
