### ISSUE TITLE
Offline Bundle Android - [@RNC/AsyncStorage]: NativeModule: AsyncStorage is NULL

### ISSUE THREAD

**Issue by iamsamuelhere** [react-native-async-storage/async-storage#1019]
### What happened?

- Using ReactNative CLI. React Native version = 0.72.4
- Using AsyncStorage version = 1.19.3
- While running ReactNative Metro server, the package works as expected. I can SET and GET values in both Android & IOS platform.
- But my use case is to, Generate a bundle file for Android, IOS and Add the bundle file into the native app. Which loads my reactnative module
  `Android - npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output ./index.android.bundle --assets-dest ../index.android.bundle`
- After generating and adding the bundle file into my native app, while running the app throws me an Error:
  `[@RNC/AsyncStorage]: NativeModule: AsyncStorage is null`
- I need the package to also load into my native apps, after bundling the app.

### Version

1.19.3

### What platforms are you seeing this issue on?

- [X] Android
- [X] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
System:
  OS: macOS 13.5
  CPU: (10) arm64 Apple M1 Pro
  Memory: 82.09 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.14.2
    path: /usr/local/bin/node
  Yarn: Not Found
  npm:
    version: 9.5.0
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/userone/.gem/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10671973
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to Reproduce

- Generate the bundle file of the ReactNative App:
     `Android - npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output ./index.android.bundle --assets-dest ../index.android.bundle`
- Include the bundle file into your native app.
- Run the native app

**Comment by gmantuanrosa** [comment]
I can get it working on the Native Android App that we have and working towards adding support for React Native on iOS but it gives me the same error as the first thing when Metro Bundler finishes building (since it runs async storage to store session tokens that we pass down from native side through native module). 

I am using react-native `0.72.6` and async on `1.19.3`.

**Comment by ternaus** [comment]
The same expo project. Works in iOS, but not in Android simulator:

`"react-native": "0.72.6"`
`"@react-native-async-storage/async-storage": "1.18.2"`

```
 ERROR  Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.

To fix this issue try these steps:

  • Rebuild and restart the app.

  • Run the packager with `--reset-cache` flag.

  • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app.

  • If this happens while testing with Jest, check out docs how to integrate AsyncStorage with it: https://react-native-async-storage.github.io/async-storage/docs/advanced/jest

If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-async-storage/async-storage/issues
```
