### ISSUE TITLE
Kotlin Compatibility 

### ISSUE THREAD

**Issue by LFMAKER** [react-native-async-storage/async-storage#1027]
### What happened?

`Execution failed for task ':react-native-async-storage_async-storage:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)`

Kotlin Version of Root Project
1.19.0 or 1.19.10

### Version

1.19.5

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
System:
    OS: macOS 13.5.2
    CPU: (8) arm64 Apple M1
    Memory: 64.06 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.0.0 - ~/.nvm/versions/node/v18.0.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.10.0/bin/yarn
    npm: 8.6.0 - ~/.nvm/versions/node/v18.0.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.13.0 - /Users/leonardo.felipe/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10671973
    Xcode: 15.0/15A240d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.20.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.5 => 0.71.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

- Create a new react native app
- Install @react-native-async-storage/async-storage
- Setup kotlin version as 1.9.0 or 1.9.10

**Comment by krizzu** [comment]
https://github.com/react-native-async-storage/async-storage/pull/1028
