### ISSUE TITLE
Error: Could not get unknown property 'kotlinVersion' for project

### ISSUE THREAD

**Issue by recallwei** [react-native-async-storage/async-storage#1040]
### What happened?

Bump to 1.20.0, then build throw an error.

![image](https://github.com/react-native-async-storage/async-storage/assets/62941121/00a7036c-e4a4-4167-88fd-53172961b194)

### Version

1.20.0

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
System:
  OS: macOS 14.1.1
  CPU: (10) arm64 Apple M2 Pro
  Memory: 167.36 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.9.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.1.0
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.09.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK:
    API Levels:
      - "29"
      - "33"
      - "34"
    Build Tools:
      - 29.0.2
      - 30.0.2
      - 30.0.3
      - 33.0.0
      - 33.0.1
      - 34.0.0
    System Images:
      - android-33 | Google APIs ARM 64 v8a
      - android-33 | Google Play ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.8.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.7
    wanted: 0.72.7
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to Reproduce

Bump to 1.20.0 and start android.

**Comment by dangleh** [comment]
Happened to me, too!

**Comment by cheehieu** [comment]
Same here... In the meantime, I've just reverted back to version 1.19.8 to avoid the build error.

```
"@react-native-async-storage/async-storage": "1.19.8",
```

**Comment by sajad786** [comment]
> Same here... In the meantime, I've just reverted back to version 1.19.8 to avoid the build error.
> 
> ```
> "@react-native-async-storage/async-storage": "1.19.8",
> ```

This works fine for me . Rn version ^0.67.5

**Comment by vipulav-j** [comment]
"@react-native-async-storage/async-storage": "1.17.9",
this version works for me

**Comment by krizzu** [comment]
Seems like a regression introduced in latest version, going to address it now

**Comment by krizzu** [comment]
Fix is here: #1042

**Comment by firstpersoncode** [comment]
still get the error in version 1.20.0 even after this patch

> Fix is here: #1042

**Comment by krizzu** [comment]
Version v1.21.0 is out, please give it a go
https://github.com/react-native-async-storage/async-storage/releases/tag/v1.21.0

**Comment by firstpersoncode** [comment]
I tried the patch.. the build error message is gone.. but now my app keep crashing, but my app on ios working fine..

**Comment by firstpersoncode** [comment]
> @firstpersoncode please open new issue with details, so I could check it out 🙏

false alarm.. I just clean the build and now it works. 🙏
