### ISSUE TITLE
Failed to write manifest file.Error Domain=NSCocoaErrorDomain Code=640 "You can’t save the file “manifest.json” because the volume “Data” is out of space."

### ISSUE THREAD

**Issue by MaratowKyryl** [react-native-async-storage/async-storage#1043]
### What happened?

I got this error logged in Sentry. 

`Failed to write manifest file.Error Domain=NSCocoaErrorDomain Code=640 "You can’t save the file “manifest.json” because the volume “Data” is out of space."`

All of users have at least 100mb free memory.

I assume, that the problem is the size of manifest file reached the limit. But, I can't find any info about known limits of manifest.json file on ios and there is no information in documentation or elsewhere how to increase the size limit.

### Version

1.19.3

### What platforms are you seeing this issue on?

- [ ] Android
- [X] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
OS: macOS 14.1.1
    CPU: (8) arm64 Apple M1
    Memory: 74.42 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 6.12.0
    Watchman: 2023.11.20.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.14.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
react: 17.0.2 => 17.0.2 
    react-native: 0.67.5 => 0.67.5 

```

### Steps to Reproduce

Run an application and save a lot of data on user login

**Comment by krizzu** [comment]
There's no limit for manifest file. It seems like there's not sufficient space to store app related data anymore. Here's the error you see
https://developer.apple.com/documentation/foundation/1448136-nserror_codes/nsfilewriteoutofspaceerror

**Comment by MaratowKyryl** [comment]
> There's no limit for manifest file. It seems like there's not sufficient space to store app related data anymore. Here's the error you see https://developer.apple.com/documentation/foundation/1448136-nserror_codes/nsfilewriteoutofspaceerror

I just checked ad figured out that we use only around 750 bytes of data stored in AsyncStorage. Still cannot understand how it's possible to run out of space.

**Comment by krizzu** [comment]
It might be that users are low on total amount, hence the issue. For values larger than 1MB, AsyncStorages on iOS stores them in a separate file (for each item) - does your calculation cover this?

**Comment by MaratowKyryl** [comment]
It supposed to. I'm using this solution to calculate the size of all key-values from storage:

https://github.com/react-native-async-storage/async-storage/issues/336#issuecomment-1654434540
