### ISSUE TITLE
on real device iphone 15 pro max, i face a bug on login request, app is hang and log ->  Excessive number of pending callbacks: 501. Some pending callbacks that might have leaked by never being called from native code:

### ISSUE THREAD

**Issue by jahanzaibUs** [react-native-async-storage/async-storage#1044]
### What happened?

after login save some data on asyncstorage,

### Version

^1.19.8

### What platforms are you seeing this issue on?

- [ ] Android
- [X] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
System:
  OS: macOS 14.1.1
  CPU: (8) arm64 Apple M1
  Memory: 108.61 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.20.2
    path: ~/.nvm/versions/node/v16.20.2/bin/node
  Yarn:
    version: 1.22.21
    path: ~/Desktop/Projects/Tada-Mobile-RN/node_modules/.bin/yarn
  npm:
    version: 8.19.4
    path: ~/.nvm/versions/node/v16.20.2/bin/npm
  Watchman:
    version: 2023.09.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.2
    path: /Users/o16labs/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.9971841
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 2.7.4
    path: /Users/o16labs/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: false
```

### Steps to Reproduce

my package.json is
"dependencies": {
    "@flyerhq/react-native-link-preview": "^1.6.0",
    "@invertase/react-native-apple-authentication": "^2.2.2",
    "@notifee/react-native": "^7.8.0",
    "@react-native-async-storage/async-storage": "^1.21.0",
    "@react-native-clipboard/clipboard": "^1.8.5",
    "@react-native-community/datetimepicker": "^6.1.3",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^9.3.1",
    "@react-native-community/slider": "^4.3.2",
    "@react-native-firebase/app": "^14.2.4",
    "@react-native-firebase/crashlytics": "^14.11.0",
    "@react-native-firebase/database": "^14.11.0",
    "@react-native-firebase/messaging": "^14.2.4",
    "@react-native-google-signin/google-signin": "^8.2.1",
    "@react-navigation/bottom-tabs": "^5.11.10",
    "@react-navigation/drawer": "^5.12.4",
    "@react-navigation/native": "^5.9.3",
    "@react-navigation/stack": "^5.14.3",
    "@sanar/react-native-highlight-text": "^1.0.2",
    "@sentry/react-native": "^5.14.1",
    "@stripe/stripe-react-native": "^0.27.1",
    "@twotalltotems/react-native-otp-input": "^1.3.11",
    "add": "^2.0.6",
    "axios": "^1.6.2",
    "card-validator": "^8.1.1",
    "cpy-cli": "^4.1.0",
    "lodash": "^4.17.21",
    "moment": "^2.29.1",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "react-native-app-intro-slider": "^4.0.4",
    "react-native-calendars": "^1.1299.0",
    "react-native-camera": "^4.2.1",
    "react-native-chart-kit": "^6.11.0",
    "react-native-cn-quill": "^0.7.17",
    "react-native-confirmation-code-field": "^7.3.2",
    "react-native-device-info": "^10.11.0",
    "react-native-dialogflow-messenger": "^0.0.3",
    "react-native-document-picker": "^8.1.1",
    "react-native-draggable-flatlist": "^4.0.1",
    "react-native-elements": "^3.3.2",
    "react-native-exit-app": "^1.1.0",
    "react-native-fbsdk": "^3.0.0",
    "react-native-floating-label-input": "^1.3.5",
    "react-native-fs": "^2.20.0",
    "react-native-geocoding": "^0.5.0",
    "react-native-geolocation-service": "^5.3.0-beta.4",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-gifted-chat": "^1.1.1",
    "react-native-google-places-autocomplete": "^2.4.1",
    "react-native-iap": "^12.10.7",
    "react-native-image-crop-picker": "^0.38.1",
    "react-native-image-view": "^2.1.9",
    "react-native-image-viewing": "^0.2.2",
    "react-native-iphone-x-helper": "^1.3.1",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-loader-overlay": "^1.0.0",
    "react-native-loading-spinner-overlay": "2.0.0",
    "react-native-maps": "^0.30.1",
    "react-native-modal": "^13.0.0",
    "react-native-modal-datetime-picker": "^13.1.2",
    "react-native-modal-dropdown": "^1.0.2",
    "react-native-neomorph-shadows": "^1.1.2",
    "react-native-otp-textinput": "^1.1.3",
    "react-native-parallax-header": "^1.1.4",
    "react-native-pell-rich-editor": "^1.8.8",
    "react-native-permissions": "^3.8.3",
    "react-native-popup-menu": "^0.15.12",
    "react-native-progress-steps": "^1.3.4",
    "react-native-qrcode-scanner": "^1.5.5",
    "react-native-quill-editor": "0.1.1",
    "react-native-ratings": "^8.1.0",
    "react-native-reanimated": "^3.5.4",
    "react-native-render-html": "^6.3.4",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-root-siblings": "^4.1.1",
    "react-native-safe-area-context": "^4.7.4",
    "react-native-screens": "^3.27.0",
    "react-native-see-more-inline": "^1.3.0",
    "react-native-simple-toast": "^1.1.3",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-splash-screen": "^3.3.0",
    "react-native-step-indicator": "^1.0.3",
    "react-native-svg": "^12.1.1",
    "react-native-swipe-list-view": "^3.2.9",
    "react-native-system-setting": "^1.7.6",
    "react-native-text-size": "^4.0.0-rc.1",
    "react-native-user-avatar": "^1.0.8",
    "react-native-vector-icons": "^8.1.0",
    "react-native-webview": "^11.23.0",
    "react-redux": "^8.1.3",
    "redux": "^4.2.1",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.4.2",
    "rn-swipeable-panel": "^1.2.5",
    "rn-tourguide": "^3.3.0",
    "socket.io-client": "^4.5.1",
    "yarn": "^1.22.19"
  },

bug log is:
Excessive number of pending callbacks: 501. Some pending callbacks that might have leaked by never being called from native code: {“9419”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9452":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9485”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9519":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9520”:{“module”:“RNCAsyncStorage”,“method”:“multiSet”},“9553":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9586”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9619":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9652”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9685":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9719”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9752":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9785”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9819":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9852”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9885":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9919”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9920":{“module”:“RNCAsyncStorage”,“method”:“multiSet”},“9953”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9986":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10019”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10052":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10085”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10119":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10152”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10185":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10219”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10252":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10285”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10319":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10352”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10385":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10419”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10452":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10485”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10519":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10552”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10585":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10619”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10620":{“module”:“RNCAsyncStorage”,“method”:“multiSet”},“10653”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10686":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10719”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10752":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10785”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10819":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10852”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10885":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10919”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10952":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“...(truncated keys)...“:451}

**Comment by ThelegendisbackV** [comment]
code: {“9419”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9452":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9485”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9519":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9520”:{“module”:“RNCAsyncStorage”,“method”:“multiSet”},“9553":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9586”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9619":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9652”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9685":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9719”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9752":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9785”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9819":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9852”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9885":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9919”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9920":{“module”:“RNCAsyncStorage”,“method”:“multiSet”},“9953”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“9986":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10019”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10052":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10085”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10119":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10152”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10185":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10219”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10252":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10285”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10319":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10352”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10385":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10419”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10452":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10485”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10519":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10552”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10585":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10619”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10620":{“module”:“RNCAsyncStorage”,“method”:“multiSet”},“10653”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10686":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10719”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10752":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10785”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10819":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10852”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10885":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10919”:{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“10952":{“module”:“RNCAsyncStorage”,“method”:“multiGet”},“...(truncated keys)...“:451

**Comment by thelukepritchard** [comment]
I to am getting this error, on Android only
