### ISSUE TITLE
Asynch storage clear atomatically Cleared value

### ISSUE THREAD

**Issue by asutariyadigit** [react-native-async-storage/async-storage#1048]
### Proposal

Asynch storage clear atomatically Cleared value

### Alternatives

Asynch storage clear atomatically Cleared value

**Comment by krizzu** [comment]
Hey please provide some more details and ideally, repro steps.

**Comment by abhayagrawal-fareye** [comment]
Any updates on this? I am also facing this same issue

**Comment by krizzu** [comment]
A repository where problem can be replicated would be awesome to get to bottom to this.

**Comment by heildionis** [comment]
I'm facing the same issue, im using @react-native-async-storage/async-storage 1.22.3 and @reduxjs/toolkit + redux-persist with nested persistReducers

At first day data stored on device and app is working correctly, after few days data has unhappenly wiped from device
