### ISSUE TITLE
@react-native-async-storage/secure-async-storage

### ISSUE THREAD

**Issue by slavko-lukic** [react-native-async-storage/async-storage#1053]
### Proposal

I understand this was discussed before but one thing I see missing from react native is providing simple and clear way to securely store data. 
This would pretty much resolve the question `best way to store tokens in react native?`.
This package would work the same way as it does now but it would have extra step to encrypt data before storing it and decrypt after reading it.
There is react-native-keychain that can do that but it's interface could be confusing to some people and looks like that it has specific use case, it persist data between reinstalls etc...

This package would live in separate context from AsyncStorage so `SecureAsyncStorage.getItem('my-key')` and `AsyncStorage.getItem('my-key')` would return different values potentially.
I am not much of a native developer so I will not go into that part but for javascript part I am proposing simple interface like AsyncStorage already has:
```javascript
import SecureAsyncStorage from '@react-native-async-storage/secure-async-storage';

const storeData = async (value) => {
  try {
    await SecureAsyncStorage.setItem('my-key', value);
  } catch (e) {
    // saving error
  }
};

const getData = async () => {
  try {
    const value = await SecureAsyncStorage.getItem('my-key');
    if (value !== null) {
      // value previously stored
    }
  } catch (e) {
    // error reading value
  }
};
```

Would something like this be possible?

**Comment by krizzu** [comment]
Hey @slavko-lukic, thanks for putting this together.

Actually, this is our end goal for next major version - different types of storage, accessible via same, simple API. This would allow to cover different use cases, such as mentioned, secure storage. I'm finishing up sqlite rewrite of storage, but due to time limit, it's dragging out a bit.

**Comment by slavko-lukic** [comment]
@krizzu It's good to know that this is in the works. It's gonna be really good for the community! 😆
