### ISSUE TITLE
Add support for iOS App Groups

### ISSUE THREAD

**Issue by bpeltonc** [react-native-async-storage/async-storage#1086]
### Proposal

Currently, the library stores the `manifest.json` file in a folder that can't be easily found by iOS apps that need access to this file, but target different platforms (e.g. WatchOS, Widget extensions, etc). Apple supports this functionality via App Groups, so the issue is entirely in the way this library interacts with the native APIs and can be fixed. Ideally React Native Async Storage would expose a JavaScript method that creates an App Group and writes data to a file in there.

**Comment by NTag** [comment]
Agreed, I also need this feature to share data between two apps I develop. It's a safe Apple feature allowing multiple apps from the same developer to access the same data: https://developer.apple.com/documentation/xcode/configuring-app-groups

I'd be great that `async-storage` supports it 🙌

**Comment by jcarioti** [comment]
Someone already did it a while back, but it's not been updated or maintained. I don't know if it's still relevant: https://github.com/react-native-async-storage/async-storage/issues/126#issuecomment-697042925

**Comment by EnricoMazzu** [comment]
Any news?

**Comment by phazei** [comment]
We have a share extension and in order for it to function, it needs to be able to access the main apps data and without group support that's not possible.
