### ISSUE TITLE
Next storage implementation: Build issues with RN 0.74

### ISSUE THREAD

**Issue by QOAL** [react-native-async-storage/async-storage#1091]
### What happened?

With React Native 0.74 updating to Kotlin 1.9.22 users using the Next storage implementation will face the following error, along with the build failing:
`ksp-1.9.20-1.0.14 is too old for kotlin-1.9.22. Please upgrade ksp or downgrade kotlin-gradle-plugin to 1.9.20.`

Updating `gradle.properties` with the following mitigates the issue:
`AsyncStorage_useNextStorage=true
AsyncStorage_kotlinVersion=1.9.22
AsyncStorage_next_kspVersion=1.9.22-1.0.17`

I haven't tried any of the newer Room versions.

It looks like `async-storage/packages/default-storage/android/config.gradle`, and the documentation just needs updating, but this is not my area of expertise.  

### Version

1.23.1

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
System:
  OS: Windows 10 10.0.19045
  CPU: (4) x64 Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
  Memory: 5.58 GB / 15.87 GB
Binaries:
  Node:
    version: 21.7.3
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 3.6.4
    path: ~\AppData\Roaming\npm\yarn.CMD
  npm:
    version: 10.2.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
IDEs:
  Android Studio: AI-221.6008.13.2211.9619390
  Visual Studio: Not Found
Languages:
  Java: 17.0.10
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.1
    wanted: 0.74.1
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Steps to Reproduce

See above.

**Comment by krizzu** [comment]
Hey, thanks for reporting, see here: https://github.com/react-native-async-storage/async-storage/pull/1094
