### ISSUE TITLE
AsyncStorage is automatically cleared when the app is restarted

### ISSUE THREAD

**Issue by Inalegwu** [react-native-async-storage/async-storage#1093]
### What happened?

While working with AsyncStorage, All information I've saved is automatically cleared from the app when it is closed or restarted, Both in Production and Development.

### Version

1.21.0

### What platforms are you seeing this issue on?

- [X] Android
- [X] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
System:
  OS: Windows 11 10.0.22631
  CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
  Memory: 710.92 MB / 7.83 GB

Binaries:
  Node:
    version: 21.7.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 10.5.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found

SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    Versions:
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio: Not Found

Languages:
  Java: Not Found
  Ruby: Not Found

npmPackages:
  "@react-native-community/cli": Not Found 
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-windows: Not Found

npmGlobalPackages:
  "*react-native*": Not Found

Android:
  hermesEnabled: Not found
  newArchEnabled: Not found

iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Steps to Reproduce

In a freshly created React Native project , after installing AsyncStorage and setting data using 
```ts
AsyncStorage.setItem(key,value)
```

restart said app and try

```ts
console.log(await AsyncStorage.getItem(key))
```

it returns undefined

**Comment by SphynxCodes** [comment]
It works if you wrap it around in an async function

**Comment by SphynxCodes** [comment]
I tried to reproduce the error but worked fine, wrapped the  `console.log(await AsyncStorage.getItem(key))` in a async function.

**Comment by blairharper** [comment]
Having the same issue on 1.21.0

**Comment by krizzu** [comment]
Hey, if you could provide me a repo with a project where the issue can be reproduced, that'd be great

**Comment by mihaibulic2** [comment]
I'm having this issue too! 

We see it every 1 in 10,000 sessions (and only on Android). There are no real clues (ie no crashes or anything showing up in our logs). Just people reporting the app looks as if they just did a 'clear data'.
