### ISSUE TITLE
The new package code is incomplete

### ISSUE THREAD

**Issue by usedlife** [react-native-async-storage/async-storage#1141]
### What happened?

Why does [release@1.24.0](https://github.com/react-native-async-storage/async-storage/releases/tag/%40react-native-async-storage%2Fasync-storage%401.24.0) not include this [commit](https://github.com/react-native-async-storage/async-storage/commit/c3192050ca15d60ce95954f364a3c34e30e6ab3f)

<img width="1360" alt="image" src="https://github.com/user-attachments/assets/beffc520-1905-4e53-8152-52837eed77ef">

### Version

1.24.0

### What platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
--
```

### Steps to Reproduce

--

**Comment by krizzu** [comment]
this is yet to be released here: https://github.com/react-native-async-storage/async-storage/pull/1129
