### ISSUE TITLE
Bug: Mocks broken for plain JS projects

### ISSUE THREAD

**Issue by janhesters** [react-native-async-storage/async-storage#236]
## Current behavior

When you follow [the docs](https://github.com/react-native-community/async-storage/blob/LEGACY/docs/Jest-integration.md) on how to integrate this module with Jest in a plain JS project, tests don't run. The reason is that the mock code references Flow types.

```
  ● Test suite failed to runmponent.test.js

    /Users/jan/dev/app/node_modules/@react-native-community/async-storage/jest/async-storagemock.js: 6
    type KeysType = Array<string>;
         ^^^^^^^^

    SyntaxError: Unexpected identifier
```

See also discussion in https://github.com/react-native-community/async-storage/issues/39.

## Expected behavior

The mock should work for projects that avoid static types.

## Repro steps

1. Create a project without static types (e.g. `npx react-native init myproject`) and install `AsyncStorage`
2. In your project root directory, create `__mocks__/@react-native-community` directory.
3. Inside that folder, create `async-storage.js` file.
4. Inside that file, export `Async Storage` mock.
5. Run a test that uses `AsyncStorage`

```javascript
export default from '@react-native-community/async-storage/jest/async-storage-mock'
```

## Environment

- **Async Storage version**: 1.6.2
- **React-Native version**: 0.61.3
- **Platform tested**: None -> It's in Jest tests
- **Logs/Error that are relevant**: see **Actual behavior**

**Comment by Krizzu** [comment]
@janhesters Whole project uses Flow, not only the Mock implementation. What preset do you use in your jest tests?

**Comment by janhesters** [comment]
@Krizzu Here is my Jest `config`:

```json
  "jest": {
    "preset": "@testing-library/react-native",
    "setupFilesAfterEnv": [
      "@testing-library/react-native/cleanup-after-each"
    ],
    "moduleDirectories": [
      "node_modules",
      "utils"
    ]
  }
```

**Comment by Krizzu** [comment]
@janhesters What about `babel.config.js`? `@testing-library/react-native` uses `react-native` preset, which relies on babel `module:metro-react-native-babel-preset` preset to parse flow in RN app.

**Comment by Krizzu** [comment]
@janhesters any update for this?

**Comment by janhesters** [comment]
@Krizzu `babel.config.js` is:

```js
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
};
```

**Comment by Krizzu** [comment]
Have you tried the [step from troubleshooting docs?](https://github.com/react-native-community/async-storage/blob/LEGACY/docs/Jest-integration.md#syntaxerror-unexpected-token-export-in-async-storagelibindexjs)

**Comment by iamolegga** [comment]
Same issue, with same babel config.

@Krizzu there is another error text , and it did not help

**Comment by Krizzu** [comment]
@iamolegga what error text you see?

**Comment by iamolegga** [comment]
The same as topic starter

**Comment by Krizzu** [comment]
I'd need more context then, like your Jest setup. Example app is a good place to lookup the config, if you need it.

**Comment by Krizzu** [comment]
Addressed already, mocks are type-free now
