### ISSUE TITLE
Document backup behaviour

### ISSUE THREAD

**Issue by mo22** [react-native-async-storage/async-storage#249]
## Motivation

Hi, it would be nice if you could update the documentation to include information about whether AsyncStorage data is stored and restored in iCloud and android backups, and what configuration steps might be necessary for this (i.e. android manifest android:fullBackupContent etc.)

## Description

see Motivation

**Comment by Krizzu** [comment]
Good idea. On iOS, AsyncStorage saves the data to the file, that's accessible for user to look into. There's a feature request that allows you to change the default save location. We'd have to keep this in mind if we were to write docs about it.

**Comment by zwenza** [comment]
I would really appreciate that! Is there any information already somewhere how to properly backup and restore AsyncStorage data?

**Comment by Krizzu** [comment]
@zwenza 

[Here are Android docs regarding auto backup (Android 23+)](https://developer.android.com/guide/topics/data/autobackup). Haven't tested it against AsyncStorage though.

**Comment by mo22** [comment]
### Android:
- https://developer.apple.com/icloud/documentation/data-storage/index.html
- Manifest <application> tag should have android:allowBackup="true"
- If manifest <application> tag defines android:fullBackupContent, the backup content xml file should have `<include domain="database" path="RKStorage" />` in it or at least no analog <exclude> tag, which for some reason was auto-generated for me by android studio.
- To test backup and restore you can use `adb shell bmgr backupnow your.package` and other commands at https://developer.android.com/guide/topics/data/testingbackup.html

### IOS:
- https://developer.android.com/guide/topics/data/autobackup.html
- generally Library/ and Documents/ are backed up unless a special file attribute is set
- restoring AsyncStorage settings works out of the box for me for iOS 13.3
- To test backup and restore without actually restoring the phone you can offload an app using settings / storage and click "Offload App"

**Comment by nishanttatva** [comment]
@mo22 
Is there any way to opt-out of auto-backup feature in iOS?. In android changing `android:allowBackup="false"` does it. Anything similar in iOS? I have a privacy concern and need to clear the app data on uninstall.

**Comment by mo22** [comment]
I don't think there's an built-in way.

You could use https://github.com/mo22/react-native-mo-fs and manually set the backup attribute for the storage directory.

```
Fs.ios.Module.setResourceValues('file:///path/to/file', {
  'NSURLIsExcludedFromBackupKey': true,
});
```

**Comment by Krizzu** [comment]
@nishantpillai5 
[Related issue](https://github.com/react-native-community/async-storage/issues/342). I'll come up with solution in upcoming days

**Comment by nishanttatva** [comment]
@Krizzu 
> Related issue. I'll come up with solution in upcoming days

Were you able to find anything?

**Comment by compojoom** [comment]
We'll in the latest version one by default opts out of backups. However I'm wondering how everyone else managed to get app data backed up in the first place?

I've tried with 0.13 and pre 0.13 releases - our app data never gets saved in the cloud. Do I need to enable some capabilities?

We use redux and redux-persist and redux-persist stores the data using async storage. I've downloaded the appData from the phone and I can see that the async files are stored inside of the Docs folder. So I don't understand how everyone else managed to back up the data in the cloud and I didn't :)

**Comment by Krizzu** [comment]
> We'll in the latest version one by default opts out of backups. However I'm wondering how everyone else managed to get app data backed up in the first place?

Devs were raising concern that might be the happening in some cases for their users. I could not repro this myself, but went ahead and added a this as a feature toggle, off by default.

Here is the documentation about it
https://react-native-async-storage.github.io/async-storage/docs/advanced/backup

**Comment by compojoom** [comment]
@Krizzu - I saw that docs. I was actually asking - how do you force AsyncStorage to store the data in iCloud? We've set the `RCTAsyncStorageExcludeFromBackup` to `false`, but our data is never uploaded to icloud. How does one configure an app to upload the data? Is there something in XCode that needs to be configured? I added iCloud as capability in it, but our data never left the device...

**Comment by rdonnelly** [comment]
@compojoom 
> how do you force AsyncStorage to store the data in iCloud?

It’s worth noting that this is different than storing the value in iCloud storage. This is related to storing the data in an iCloud backup, which comes back when you restore the phone (which was the original problem). My initial thought when reading the docs was that this data would save/sync _to_ iCloud (which would be available in other devices). I was confused for a good bit, so I figured I’d share. 😄

I don’t necessarily think any change needs to be made to the docs, but if it’s easy and others have similar confusion, it might be nice to add a note. 💭

**Comment by QiYuNew** [comment]
Hello - I uninstalled my app on iPhone and there is backup file saved on iCloud. How can I restore the data after I reinstall the app?

**Comment by ttristan** [comment]
> It’s worth noting that this is different than storing the value in iCloud storage. This is related to storing the data in an iCloud backup, which comes back when you restore the phone (which was the original problem). My initial thought when reading the docs was that this data would save/sync _to_ iCloud (which would be available in other devices). I was confused for a good bit, so I figured I’d share. 😄

I think the docs could be more clear on this part. I also thought that data is actually synced via iCloud between devices. Seems like this is not the case.

**Comment by nhatduy209** [comment]
> Hello - I uninstalled my app on iPhone and there is backup file saved on iCloud. How can I restore the data after I reinstall the app?
how can you save data on icloud ? Pls help me , many thanks
