### ISSUE TITLE
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :@react-native-community_async-storage.

### ISSUE THREAD

**Issue by Luckygirlllll** [react-native-async-storage/async-storage#251]
## Current behavior

ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :@react-native-community_async-storage.

## Expected behavior

I can build Android project

## Repro steps

1. add async storage
2. Try to build Android project

## Environment

- **Async Storage version**:  1.6.3
- **React-Native version**:    "react-native": "0.59.10",
- **Platform tested**:  Android
- **Logs/Error that are relevant**:  ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :@react-native-community_async-storage.

**Comment by ste001** [comment]
It looks like you installed Async Storage using a wrong character. It should be `yarn add @react-native-community/async-storage`, not `yarn add @react-native-community_async-storage`.

Also, be sure to follow the linking instructions, as you have a React-Native version below 0.60. You should link it like `react-native link @react-native-community/async-storage`.

**Comment by gorvinsky** [comment]
@ste001 I'm at React Native version 0.61.2 and I have some questions regarding installing the package. I'm still new to this autolinking feature. Anyway, I have not used yarn before and is it necessary to install via yarn? I did try ``npm install --save @react-native-community/async-storage`` and then ``react-native unlink @react-native-community/async-storage`` only to receive unable to resolve module error while compiling.

**Comment by Krizzu** [comment]
@Luckygirlllll 

Can you show your `settings.gradle` file?

**Comment by akinncar** [comment]
Added maven like this solved for me

```
allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven { url "https://jitpack.io" }
    }
}
```

**Comment by tido64** [comment]
Closed due to inactivity.
