### ISSUE TITLE
How do I import AsyncStorage in order to get flow-types working?

### ISSUE THREAD

**Issue by PauliusLiekis** [react-native-async-storage/async-storage#286]
## You want to:  

if I import AsyncStorage like:

`import AsyncStorage from "@react-native-community/async-storage";`

it doesn't get proper flow types and it is imported as `any`. My guess would be that it happens because `index.js` missing `@flow` tag, at least that's the issue in my own project.

## Details:

Am I missing something? How to I make it work?

**Comment by shani-maini** [comment]
I am getting full documentation from the below blog link

Hope it helps you

https://medium.com/@tiwarishani/react-native-async-storage-8773dcdcb54a

**Comment by tido64** [comment]
Closed due to inactivity.
