### ISSUE TITLE
Error: attempt to write a readonly database (code 1032)

### ISSUE THREAD

**Issue by bscheideldyrt** [react-native-async-storage/async-storage#311]
## Current behavior

```
Error: attempt to write a readonly database (code 1032)
  at f(node_modules/@react-native-community/async-storage/lib/AsyncStorage.js:413:25)
  at map(app:///[native code]:0:0)
  at apply(node_modules/@react-native-community/async-storage/lib/AsyncStorage.js:127:22)
  at __invokeCallback(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:483:13)
  at fn(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:135:12)
  at value(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:9)
  at value(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:134:18)
  at value(app:///[native code]:0:0)
```

We're currently seeing a large spike of Android users receiving `Error attempt to write a readonly database (code 1032)`.

Looks like our dependencies that rely on `async-storage` are throwing errors as well.

## Expected behavior

No errors.

## Environment

- **Async Storage version**: `1.8.1`
- **React-Native version**: `0.61.4`
- **Platform tested**: `Android`

**Comment by Krizzu** [comment]
I suspect this could be related to having both Community's and Core's `AsyncStorage` in a project. 
What Android are you seeing the issue on?

**Comment by bscheideldyrt** [comment]
Pretty much all of them.  Everything from Android 5 to Android 10 across about 50 different Android devices.

**Comment by Krizzu** [comment]
I can't say for sure, I need more details.
If you have some repro steps or repo that has the issue, that be great.

**Comment by bscheideldyrt** [comment]
I wish we had a repro.  We haven't been able to get any of our devices in this state (either accidentally or attempting to force db states).  We're just seeing thousands of users who are now unable to write anything to async storage.  I'm going to look at all of our dependencies to see if I can find any that are using the Core's version of `AsyncStorage`.

**Comment by tianxind** [comment]
We have encountered this issue with thousands of errors every week as well

**Comment by maxikgreat** [comment]
> I suspect this could be related to having both Community's and Core's `AsyncStorage` in a project.
> What Android are you seeing the issue on?

Using only your's library in project, but got the same problem..
What can it be?

**Comment by maxikgreat** [comment]
> > I suspect this could be related to having both Community's and Core's `AsyncStorage` in a project.
> > What Android are you seeing the issue on?
> 
> Using only your's library in project, but got the same problem..
> What can it be?

Was fixed by adding code from this page :)
[https://reactnative.dev/docs/removing-default-permissions](url)

Maybe will be helpful to someone

**Comment by hanno-jonlay** [comment]
@bscheideldyrt @tianxind - are you by any chance using https://github.com/aws-amplify/amplify-js in your projects?

We've seen some other issues related to AsyncStorage when using Amplify. Interested to know if this ends up being a common factor.

**Comment by RodolfoGS** [comment]
Hi @hanno-jonlay, I'm having the same issue and I'm using Amplify. You think that can be related? 🤔

**Comment by hanno-jonlay** [comment]
I can't say for sure. I know only that we had issues with Amplify breaking other aspects of our AsyncStorage usage, and I believe that Amplify is using the [deprecated core version](https://reactnative.dev/docs/asyncstorage.html) of AsyncStorage 

So it could be a possible culprit 🤷

**Comment by tido64** [comment]
Closed due to inactivity.
