### ISSUE TITLE
memory leak on read data out

### ISSUE THREAD

**Issue by code-brewer** [react-native-async-storage/async-storage#330]
## Current behavior

Firstly, init data record of large size 1.4MB, then repeatedly invoke getItem() to read out this larget record,  I observed that memory, for example, after doing 20 times getItem(), raise from 51MB to 71MB and stable on 71MB. 

 

## Expected behavior

The memory consumption should fall back the amount before invoked getItem() API, which is 51MB for my case.

## Repro steps

1)  Init a record around 37KB size
2) Expand this record to even large size by append  1.1MB  content
3) Repeatedly do  getItem()
 Then you will see memory raise on Xcode debug navigator Tab.

Here is the minimal demo:  https://github.com/code-brewer/rn_asyncstorage_leak_demo

## Environment

- **Async Storage version**:  "@react-native-community/async-storage": "^1.8.1",
- **React-Native version**:     0.59.3
- **Platform tested**:  iOS
- **Logs/Error that are relevant**:  No

**Comment by Krizzu** [comment]
Thanks for repro! I'll check what might be happening here

**Comment by tido64** [comment]
@Krizzu: Do we have an update here?

**Comment by Krizzu** [comment]
Unfortunately not yet
