### ISSUE TITLE
V2: Outdated typings

### ISSUE THREAD

**Issue by maximzhemerenko** [react-native-async-storage/async-storage#349]
Hi Guys, thanks a lot, I found v2 version of this library very useful for me, but noticed one problem.

## Current behavior

Typescript typings are outdated with the current implementation.
For example, WebStorage class should have constructor, but typings not...

## Expected behavior

Typings should be up to date.

## Repro steps

Write a basic sample from the Readme file using typescript. Compilator says `TS2554: Expected 0 arguments, but got 1.`.

## Environment

"@react-native-community/async-storage-backend-web": "^2.0.0-rc.3"

- **React-Native version**: - Not react native, "react": "^16.13.1",
- **Platform tested**: - Web platform
- **Logs/Error that are relevant**: TS2554: Expected 0 arguments, but got 1.

Who can help me, what can I do to find a workaround to this issue? I can help and make a merge request, but I don't know how to generate typing in a proper way? And how I can test is my fixes works fine?
I noticed that someone removed `yarn generate:types` in #216, but I do not completely understand how it does works)

**Comment by tido64** [comment]
No longer applicable.
