### ISSUE TITLE
The connection pool for database 'xxx' has been unable to grant a connection to thread 376 (pool-5-thread-1) with flags 0x2 for 180.01001 seconds

### ISSUE THREAD

**Issue by anthinkingcoder** [react-native-async-storage/async-storage#355]
## Current behavior
`setItem` not callback 

## Expected behavior
`setItem` callback 

## Repro steps
when excute `mReactDatabaseSupplier.get().setTransactionSuccessful();`,
I found `get()` not enter。it‘s block，maybe not get` lock`。
1. add log
![C7BAAFBD-ED33-499E-9A71-645F17883000](https://user-images.githubusercontent.com/17498633/81768896-c0814700-950e-11ea-8c2c-02f2d3de4d9f.png)
![4415314F-9268-4DD5-BDD6-6422014FF2BA](https://user-images.githubusercontent.com/17498633/81769220-a1cf8000-950f-11ea-876b-9ee03d3b0ae8.png)

run it, show the log。`mReactDatabaseSupplier.get()` not log `get lock AsyncTask #1`，it‘s block。
![84A9EC98-EF01-4DAE-B9EB-BE60C3B1DCFB](https://user-images.githubusercontent.com/17498633/81769448-376b0f80-9510-11ea-9f6d-713bbea9d9ea.png)

2. use `Lock` instead of `synchronized`
get()
![image](https://user-images.githubusercontent.com/17498633/81772267-0393e800-9518-11ea-9722-22e4a9ea172b.png)
ensureDatabase()
![image](https://user-images.githubusercontent.com/17498633/81772300-18707b80-9518-11ea-89e1-1f62ec3a2582.png)

it's ok。
![8F55E933-18AD-431A-933A-D0E803F78BCF](https://user-images.githubusercontent.com/17498633/81772447-6dac8d00-9518-11ea-919e-d0c7cf6a8767.png)

## Environment

- **Async Storage version**: 1.9.0
- **React-Native version**:0.59 
- **Platform tested**: Android9
- **Logs/Error that are relevant**:

**Comment by Krizzu** [comment]
@anthinkingcoder Hey, thanks for the insight. We had similar issue before, hence we created [Dedicated Executor pool for this case](https://github.com/react-native-community/async-storage/blob/master/docs/advanced/DedicatedExecutor.md). Can you give it a try?

**Comment by anthinkingcoder** [comment]
@Krizzu  I tried this method, but I found it was not possible。Only changing the lock mechanism can solve my problem。
