### ISSUE TITLE
flag variable automaitcally deleted after sometime from memory

### ISSUE THREAD

**Issue by ashu-11** [react-native-async-storage/async-storage#357]
## Current behavior

previously when I am storing the flag variable in the async storage so that it can identify between login and sign up user and it was working fine now the data of variable automatically deleted from that variable

## Expected behavior
it should stay in the async memory 

## Environment

- **Async Storage version**: 
- **React-Native version**: 
- **Platform tested**: 
- **Logs/Error that are relevant**:

**Comment by tido64** [comment]
Thanks for reporting this issue. Can you please provide repro steps as well as the environment section? You can edit your issue to include them.

**Comment by tido64** [comment]
Closed due to inactivity.
