### ISSUE TITLE
Warning: deep-assign is deprecated

### ISSUE THREAD

**Issue by yvbeek** [react-native-async-storage/async-storage#374]
> warning @react-native-community/async-storage > deep-assign@3.0.0: Check out `lodash.merge` or `merge-options` instead.

We can probably swap out the `deep-assign` library with one of these:

https://github.com/TehShrike/deepmerge
https://github.com/schnittstabil/merge-options

Only seems to be used here?
https://github.com/react-native-community/async-storage/blob/85c5278534eef549a959ae386bd0e16fdb0167b0/src/AsyncStorage.js#L17

**Comment by Krizzu** [comment]
Hey,

This is great first-time contribution task - I can provide help with implementing it.

**Comment by tido64** [comment]
@Krizzu: Are we still doing this?

**Comment by Krizzu** [comment]
We rely on the library that has its quirks, so upgrading means we could potentially break already released versions.
