### ISSUE TITLE
Auth-Session not persisted on iOS after closing app

### ISSUE THREAD

**Issue by emmanuel-D** [react-native-async-storage/async-storage#385]
I am using:
- SDK Version: 36.0.0
- Platforms(Android/iOS)

I have builded a simple server with [Spring Security](https://spring.io/guides/gs/securing-web/) that provides a **Basic Auth** via a REST-API for my **Expo Standalone app**.

- On **Android**, after successfully login the session is persisted, even if I close the app and reopen it. Also after app-updates, the session is still available and the server can authorize me access the ressources. So all here works well (It is the same case on browser).

- But on **iOS**, after successfully login a first time, the server authozire me access the ressources as long as the app is not closed. After I close the app and immediately reopen it, the session disappears and I must login again.

I am not understanding what is not working on **iOS**. Maybe the **cookies** are deleted each times ?
I would like to release the first version of the app, but the **iOS** behaviour does not allow me now.

**Comment by Krizzu** [comment]
> Maybe the cookies are deleted each times

Is your issue related to Async Storage?

**Comment by tido64** [comment]
Closed due to inactivity.
