### ISSUE TITLE
Program type already present: com.reactnativecommunity.asyncstorage.AsyncLocalStorageUtil

### ISSUE THREAD

**Issue by NITISHSHARMA12** [react-native-async-storage/async-storage#397]
## Environment

- **Async Storage version**: 
- **React-Native version**: 
- **Platform tested**: 
- **Logs/Error that are relevant**:

**Comment by Krizzu** [comment]
Hey, can you provide more info?

**Comment by tido64** [comment]
Closed due to inactivity.
