### ISSUE TITLE
Adding event listener functionality 

### ISSUE THREAD

**Issue by YogiHa** [react-native-async-storage/async-storage#401]
## Motivation

As in web storage, it would be very useful to have { onChange } listener that will trigger each time values in storage changed. That way different components can be rendered with new values, even if the change happened somewhere else

**Comment by Krizzu** [comment]
IMO, this would go beyond the scope of this package. Adding reactive functionality could be done in local codebase, with some abstraction on top of Async Storage.

**Comment by YogiHa** [comment]
I agree it possible to achieve it as you said with some abstraction on top of Async Storage, but IMO it a bit shame that this great package without state management has a big downside

**Comment by cmnstmntmn** [comment]
@YogiHa did you find a way to implement an event wrapper on top of async-storage?

@Krizzu, there's this case where we have an auth token; 
if the token is removed, then we have to redirect the user to login; 

another argument is that web localstorage have such a [thing](https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event)

**Comment by YogiHa** [comment]
@cmnstmntmn I have also redux store, and actually the variable live there. Any time redux action change the state I also set the asyncStore state.
At init mount I set initial redux state as the cached value if exist

**Comment by Krizzu** [comment]
>  it not following DRY standard to have the same constant in both AsyncStorage and store, when you can have only in AsyncStorage in case event listener exist

@YogiHa  It's more about separation of domains here - one is persistent storage, one is a state management. 

@cmnstmntmn 

For example, you could use a facade pattern for reading/saving persisting data and add listener functionality on top of that.

```typescript
class Storage {
  _enableFlag: boolean = false;
  _listeners = [];

  constructor() {
    AsyncStorage.getItem('flag').then(value => {
      this._enableFlag = value;
    });
  }

  addListener(listener: () => void) {
    this._listeners.push(listener);
  }

  readFlag = () => this._enableFlag;

  saveFlag(value: boolean) {
    AsyncStorage.setItem('flag', value).then(() => {
      this._enableFlag = value;
      this._listeners.forEach(listener => listener(value));
    });
  }
}

export default new Storage();
```

**Comment by pke** [comment]
While I also was just missing this listener functionality I can understand the decission not to include this. The code example from @Krizzu would be a good candidate for a `react-native-async-storage-listener` ;)

**Comment by panshulyogesh** [comment]
@Krizzu,
 hI, does the above solution work ?

**Comment by jayampathiadhikari** [comment]
@panshulyogesh https://www.npmjs.com/package/react-native-async-storage-listener check this out

**Comment by jayampathiadhikari** [comment]
for everyone looking for a package. try this: https://www.npmjs.com/package/react-native-async-storage-listener

**Comment by ChocolateLoverRaj** [comment]
@jayampathiadhikari That package doesn't use this package a dependency 😕

**Comment by jayampathiadhikari** [comment]
@ChocolateLoverRaj I don't know why it does not show 'async-storage' as a dependency. but if you look in the package.json you can see "@react-native-community/async-storage": "^1.12.1". https://github.com/jayampathiadhikari/react-native-async-storage-listener/blob/master/package.json

**Comment by kierancrown** [comment]
I added this functionality to a hook which works well enough
```
import { useEffect, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

const useAsyncStorageSubscription = (key: string, interval: number = 500) => {
  const [value, setValue] = useState<string | null>(null);

  useEffect(() => {
    const intervalId = setInterval(() => {
      AsyncStorage.getItem(key).then(val => {
        setValue(val);
      });
    }, interval);

    return () => {
      clearInterval(intervalId);
    };
  }, [key, interval]);

  return value;
};

export default useAsyncStorageSubscription;
```

**Comment by erenkulaksiz** [comment]
> I added this functionality to a hook which works well enough
> 
> ```ts
> import { useEffect, useState } from 'react';
> import AsyncStorage from '@react-native-async-storage/async-storage';
> 
> const useAsyncStorageSubscription = (key: string, interval: number = 500) => {
>   const [value, setValue] = useState<string | null>(null);
> 
>   useEffect(() => {
>     const intervalId = setInterval(() => {
>       AsyncStorage.getItem(key).then(val => {
>         setValue(val);
>       });
>     }, interval);
> 
>     return () => {
>       clearInterval(intervalId);
>     };
>   }, [key, interval]);
> 
>   return value;
> };
> 
> export default useAsyncStorageSubscription;
> ```

This is not a subscription. This is just checking its value every given time. Dont do this on your codebase. Please.

**Comment by KMJ-007** [comment]
in case any one want class based code with little bit of type safety also

```ts
import AsyncStorage from '@react-native-async-storage/async-storage';

type StorageKeyValuePair = {
  user: User;
  theme: ThemeTypes;
}

type Listener = () => void;

class LocalAsyncCache {
  private listeners: Map<string, Set<Listener>> = new Map();

  getItem = async <K extends keyof StorageKeyValuePair>(key: K): Promise<StorageKeyValuePair[K] | null> => {
    try {
      const item = await AsyncStorage.getItem(key);
      if (!item) {
        return null;
      }
      try {
        return JSON.parse(item);
      } catch {
        return item as StorageKeyValuePair[K] | null;
      }
    } catch (error) {
      console.error('Error getting item from AsyncStorage:', error);
      return null;
    }
  };

  setItem = async <K extends keyof StorageKeyValuePair>(
    key: K,
    value: StorageKeyValuePair[K]
  ): Promise<void> => {
    try {
      await AsyncStorage.setItem(key, JSON.stringify(value));
      this.notifyListeners(key);
    } catch (error) {
      console.error('Error setting item in AsyncStorage:', error);
    }
  };

  removeItem = async <K extends keyof StorageKeyValuePair>(key: K): Promise<void> => {
    try {
      await AsyncStorage.removeItem(key);
      this.notifyListeners(key);
    } catch (error) {
      console.error('Error removing item from AsyncStorage:', error);
    }
  };

  addListener = <K extends keyof StorageKeyValuePair>(key: K, listener: Listener) => {
    if (!this.listeners.has(key)) {
      this.listeners.set(key, new Set());
    }
    this.listeners.get(key)?.add(listener);

    return {
      remove: () => {
        this.listeners.get(key)?.delete(listener);
        if (this.listeners.get(key)?.size === 0) {
          this.listeners.delete(key);
        }
      },
    };
  };

  private notifyListeners(key: string) {
    this.listeners.get(key)?.forEach((listener) => listener());
  }
}

export const localAsyncCacheAPI = new LocalAsyncCache();
```

**Comment by marcilioware** [comment]
> in case any one want class based code with little bit of type safety also
> 
> import AsyncStorage from '@react-native-async-storage/async-storage';
> 
> type StorageKeyValuePair = {
>   user: User;
>   theme: ThemeTypes;
> }
> 
> type Listener = () => void;
> 
> class LocalAsyncCache {
>   private listeners: Map<string, Set<Listener>> = new Map();
> 
>   getItem = async <K extends keyof StorageKeyValuePair>(key: K): Promise<StorageKeyValuePair[K] | null> => {
>     try {
>       const item = await AsyncStorage.getItem(key);
>       if (!item) {
>         return null;
>       }
>       try {
>         return JSON.parse(item);
>       } catch {
>         return item as StorageKeyValuePair[K] | null;
>       }
>     } catch (error) {
>       console.error('Error getting item from AsyncStorage:', error);
>       return null;
>     }
>   };
> 
>   setItem = async <K extends keyof StorageKeyValuePair>(
>     key: K,
>     value: StorageKeyValuePair[K]
>   ): Promise<void> => {
>     try {
>       await AsyncStorage.setItem(key, JSON.stringify(value));
>       this.notifyListeners(key);
>     } catch (error) {
>       console.error('Error setting item in AsyncStorage:', error);
>     }
>   };
> 
>   removeItem = async <K extends keyof StorageKeyValuePair>(key: K): Promise<void> => {
>     try {
>       await AsyncStorage.removeItem(key);
>       this.notifyListeners(key);
>     } catch (error) {
>       console.error('Error removing item from AsyncStorage:', error);
>     }
>   };
> 
>   addListener = <K extends keyof StorageKeyValuePair>(key: K, listener: Listener) => {
>     if (!this.listeners.has(key)) {
>       this.listeners.set(key, new Set());
>     }
>     this.listeners.get(key)?.add(listener);
> 
>     return {
>       remove: () => {
>         this.listeners.get(key)?.delete(listener);
>         if (this.listeners.get(key)?.size === 0) {
>           this.listeners.delete(key);
>         }
>       },
>     };
>   };
> 
>   private notifyListeners(key: string) {
>     this.listeners.get(key)?.forEach((listener) => listener());
>   }
> }
> 
> export const localAsyncCacheAPI = new LocalAsyncCache();

This is a great code actually. Thank you for that!
I made some changes to the notifyListeners send the new value instead of only the key.
