### ISSUE TITLE
Podspec s.dependency error: Unable to find a specification `React-Core` 

### ISSUE THREAD

**Issue by wangxxxb** [react-native-async-storage/async-storage#457]
## Current behavior

```
[!] Unable to find a specification for `React-Core` depended upon by `RNCAsyncStorage`
```
## Expected behavior

Run `pod install` successfully

## Repro steps

```
1. react native cli init using latest RN
2. pod install async-storage

```

## Environment

- **Async Storage version**:  1.12.1
- **React-Native version**:0.63.3 
- **Platform tested**: IOS
- **Logs/Error that are relevant**: 

Current workaround from https://github.com/joltup/rn-fetch-blob/issues/402#issuecomment-513077800
Use `patch-package` to apply a quick patch.

Change `node_modules/@react-native-community/async-storage/RNCAsyncStorage.podspec`:
```diff
+  s.dependency 'React/Core'
-  s.dependency 'React-Core'
```

**Comment by wangxxxb** [comment]
Now that the upstream `React Native` has changed,  it seems many plugins have been effected by this refactoring.

**Comment by dishantwalia** [comment]
I also faced similar error while pod installation.

**Comment by dishantwalia** [comment]
I have figure out one solution for project which is running on RN version <=0.62

**Comment by tido64** [comment]
@wangxxxb, does changing it to `React` work for you as well?
```diff
-  s.dependency 'React-Core'
+  s.dependency 'React'
```
It looks like it was changed to fix autolinking in Xcode 12 in #442 so I'm not sure it's right either way. Looking at `react-native` source, I can't find any references to `React/Core` anywhere.

**Comment by stu-dev** [comment]
This PR is a regression for me (xcode 12.2, RN 0.63.3)

I do think it needs to be `s.dependency 'React-Core'` https://github.com/facebook/react-native/issues/29633#issuecomment-694187116

**Comment by tido64** [comment]
@stu-dev: Can you open a new issue with repro steps? I can't repro this locally.

```
% yarn react-native info
yarn run v1.22.10
$ /~/async-storage/node_modules/.bin/react-native info
info Fetching system and libraries information...
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 3.48 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.20.0 - /var/folders/qn/nx1nq2td23d22b1tx_t7rlsr0000gn/T/yarn--1607079042461-0.2666655578265764/node
    Yarn: 1.22.10 - /var/folders/qn/nx1nq2td23d22b1tx_t7rlsr0000gn/T/yarn--1607079042461-0.2666655578265764/yarn
    npm: 6.14.8 - ~/Source/async-storage/node_modules/.bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-27 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
    Python: 3.9.0 - /usr/local/opt/python/libexec/bin/python
  npmPackages:
    @react-native-community/cli: ^4.5.1 => 4.13.0
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-macos: 0.63.1 => 0.63.1
  npmGlobalPackages:
    *react-native*: Not Found
✨  Done in 8.65s.
```

**Comment by stu-dev** [comment]
@tido64 https://github.com/react-native-async-storage/async-storage/issues/509

**Comment by stu-dev** [comment]
@tido64 have you looked at the new issue?
