### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by thiago-ikeda-hesper** [react-native-async-storage/async-storage#459]
## Current behavior

Documentation link is broken.

## Expected behavior

Documentation link should redirect users to the documentation page.

## Repro steps

1. https://github.com/react-native-async-storage/async-storage#readme
2. Click on **documentation** link.

**Comment by Krizzu** [comment]
Fixed in https://github.com/react-native-async-storage/async-storage/pull/458
