### ISSUE TITLE
Documentation mismatch

### ISSUE THREAD

**Issue by lvonk** [react-native-async-storage/async-storage#469]
## Current behavior
Follow the instructions as described here: https://react-native-async-storage.github.io/async-storage/docs/install

```zsh
yarn add @react-native-async-storage/async-storage
npx pod-install
```

The use as described here https://react-native-async-storage.github.io/async-storage/docs/usage:

```js
import AsyncStorage from '@react-native-async-storage/async-storage';
```

This results in an error:

```
[Error: undefined Unable to resolve module `@react-native-async-storage/async-storage` from `pages/Page.js`: @react-native-async-storage/async-storage could not be found within the project.
```

Changing it to: `import AsyncStorage from '@react-native-community/async-storage';` resolves the issue

## Expected behavior

That the instructions work :-)

## Environment

- **Async Storage version**: "@react-native-community/async-storage": "^1.12.1",
- **React-Native version**: "react-native": "0.63.3",
- **Platform tested**: IOS

**Comment by tido64** [comment]
This should be fixed in #466. @Krizzu: Do you know when we can create a new release?

**Comment by Krizzu** [comment]
Documentation is already released (it's released whenever we do changes in `website/` dir)

**Comment by Krizzu** [comment]
Please use the latest version (v1.13.0+)
