### ISSUE TITLE
More client-friendly multiGet return value

### ISSUE THREAD

**Issue by wlycdgr** [react-native-async-storage/async-storage#476]
## Motivation

Currently, `multiGet([key1, key2, ...])` returns an array of `[key1, value1],...` arrays. What clients ?probably? usually want is to build an object from the returned values (for example when initializing a Redux store from storage on app startup). If the return value was already an object, clients would need to do less/no return value processing.

## Description

`multiGet` would now optionally return a `{ key1: value1, ....}` object instead of an array of arrays.

## New feature implementation

To ensure backwards compatibility, this would need to be implemented through a new `multiGet` variant or (and I think this next option is better as it keeps the API smaller and simpler) a new optional `returnAsObject` parameter that defaults to `false`.

If the community feels that this would be a good change, I can make a PR for it before the end of November.

**Comment by Krizzu** [comment]
That'd introduce a breaking change I don't want to include just yet. For now, you can use array destructuring to get the values.

**Comment by wlycdgr** [comment]
Thank you for taking a look @Krizzu . Why would this  be a breaking change? Can't the `multiGet` implementation branch on the types of the optional parameters?
