### ISSUE TITLE
AsyncStorage is null within jest file in expo project 

### ISSUE THREAD

**Issue by gingerdudley** [react-native-async-storage/async-storage#478]
## You want to:  
Hello. I am experiencing some problems regarding jest in my expo project. I used yarn to install jest and then created a test file to test out my App.js. After running "yarn test" I am getting an error that my AsyncStorage is null. I did some googling and read to install import AsyncStorage from "@react-native-community/async-storage"; but then I also read that this install doesn't work for expo. Now I am confused and wondering what I should do to fix this problem. I tried the suggested advice that came up on the terminal but none of them have fixed my problem. Thanks in advance 

## Details:
This is what my App.js file looks like right now: 

import React from "react";
import renderer from "react-test-renderer";
import AsyncStorage from "@react-native-community/async-storage";
//import { AsyncStorage } from "react-native";

import App from "./App";

describe("<App />", () => {
  it("has 1 child", () => {
    const tree = renderer.create(<App />).toJSON();
    expect(tree.children.length).toBe(1);
  });
});

**Comment by Krizzu** [comment]
Hey,
`@react-native-community/async-storage` has moved to this repo (react-native-async-storage), so [here are the installation docs](https://react-native-async-storage.github.io/async-storage/). And Yes, Expo is support in this version.

Once you get the library, [here are the docs about integration AsyncStorage with Jest runner](https://react-native-async-storage.github.io/async-storage/docs/advanced/jest).
