### ISSUE TITLE
NativeModule: AsyncStorage is null on Android

### ISSUE THREAD

**Issue by thertzelle** [react-native-async-storage/async-storage#479]
## Current behavior

Module does not work properly on android running via Android studio or on builds with gradle. Works great otherwise, just can't push out builds to users.

This is a regular react native project, without expo.

```
E/ReactNativeJS: Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.
    
    To fix this issue try these steps:
    
      • Run `react-native link @react-native-async-storage/async-storage` in the project root.
    
      • Rebuild and restart the app.
    
      • Run the packager with `--reset-cache` flag.
    
      • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app.
    
      • If this happens while testing with Jest, check out docs how to integrate AsyncStorage with it: https://react-native-async-storage.github.io/async-storage/docs/advanced/jest
    
    If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-async-storage/react-native-async-storage/issues
    , js engine: hermes
```

## Expected behavior

Android is able to run successfully.

## Repro steps

I followed the directions exactly, and since then have tried many of the other similar issue suggestions without any luck.

## Environment

- **Async Storage version**: `"@react-native-async-storage/async-storage": "^1.13.1",`
- **React-Native version**: 0.63.2
- **Platform tested**: iOS / Android
- **Logs/Error that are relevant**: See above during Android Studio build.

**Comment by thertzelle** [comment]
Additionally the link in the error `https://github.com/react-native-async-storage/react-native-async-storage/issues` is broken.

**Comment by Krizzu** [comment]
Hello,
> Additionally the link in the error
Thanks for pointing this out.

> Module does not work properly on android running via Android studio
RN CLI runs the same gradle tasks as Android Studio, so would need bit more info to debug here

**Comment by thertzelle** [comment]
My solution was to remove all of my react native modules yarn remove .... (including this one), re-build the Android folder and re-install.
