### ISSUE TITLE
React Native version support

### ISSUE THREAD

**Issue by amhinson** [react-native-async-storage/async-storage#483]
## You want to:  
Hello! I'm looking to use this package in another open source library and I'm wondering if there is a minimum version of React Native that this library supports, as that could affect our library's supported versions as well. I see in `package.json` we have this:
https://github.com/react-native-async-storage/async-storage/blob/bd2c08db2aa080e146b204a691b21d13ba57ad70/package.json#L58-L61

So I just wanted to confirm if `>=0.59` is the lowest supported version, or if earlier versions still work as well.

Thanks!

**Comment by Krizzu** [comment]
AFAIK, we started at 0.59 so it's confirmed working version. As far I'm concern, it should work on older versions as well (due to jetifier for Android), but did not test that.

**Comment by amhinson** [comment]
Ok perfect. Just what I was looking for. Thanks!
