### ISSUE TITLE
Clear up confusion about organization change

### ISSUE THREAD

**Issue by DomiR** [react-native-async-storage/async-storage#489]
## You want to:  
Hey, thanks for this lib. Could you clarify the change of the org? Why is this not managed by react-native-community anymore? I cannot find any info and reasoning about this change and would like some clarification.

**Comment by tido64** [comment]
Please take a look at [What repositories belong in React Native Community?](https://github.com/react-native-community/discussions-and-proposals/blob/master/partners/0001-organization-repository-policy.md), and the discussion here: https://github.com/react-native-community/discussions-and-proposals/issues/176#issuecomment-693569246
