### ISSUE TITLE
Does react-native-async-storage v1.13.2 support react-native-windows 0.63?

### ISSUE THREAD

**Issue by tarasvakulka** [react-native-async-storage/async-storage#490]
Does react-native-async-storage v1.13.2 support react-native-windows 0.63? Because I try to build on react-native-windows 0.63 via Visual Studio and get error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null
 
"react-native": "0.63.2",
"react-native-windows": "^0.63.0-0",
 "@react-native-async-storage/async-storage": "^1.13.2"

**Comment by tido64** [comment]
It should. We recently had an issue with it not building correctly (#448), but it was fixed in [v1.13.0](https://github.com/react-native-async-storage/async-storage/releases/tag/v1.13.0). Can you please provide more information and steps for how to reproduce the issue you're seeing?

**Comment by tarasvakulka** [comment]
> It should.

Should I do manual linking react-native-async-storage v1.13.2 for windows or it should link automatically? Because I didn't make manual linking process

**Comment by tarasvakulka** [comment]
@tido64 Info about my issue:
I build my project by VisualStudio, app start running and when metro bundle finished bundling process app crash and I see in console  [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null (see screenshot).
![Async error](https://user-images.githubusercontent.com/20745370/99289991-660ecd80-2846-11eb-8c40-056cdab2977c.jpg)

All my dependencies:
"dependencies": {
    "@react-native-async-storage/async-storage": "^1.13.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "5.9.7",
    "@react-navigation/native": "^5.8.9",
    "@react-navigation/stack": "^5.12.6",
    "axios": "0.19.0",
    "es6-symbol": "3.1.1",
    "i18next": "19.6.2",
    "lodash": "4.17.15",
    "lottie-react-native": "git+https://github.com/mandrigin/lottie-react-native-1.git#windows-support-csharp",
    "moment": "2.24.0",
    "prop-types": "15.7.2",
    "ramda": "0.26.1",
    "react": "16.13.1",
    "react-i18next": "11.7.0",
    "react-native": "0.63.2",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-iphone-x-helper": "1.2.1",
    "react-native-windows": "^0.63.0-0",
    "react-native-media-queries": "0.3.0",
    "react-native-reanimated": "^1.13.1",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.14.0",
    "react-native-snap-carousel": "3.8.0",
    "react-native-video": "^5.1.0-alpha8",
    "react-redux": "7.1.0",
    "redux": "4.0.4",
    "redux-devtools-extension": "2.13.8",
    "redux-thunk": "2.3.0",
    "uuid": "^8.3.1"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^1.1.0",
    "babel-plugin-transform-remove-console": "6.9.4",
    "babel-jest": "^25.1.0",
    "babel-eslint": "10.0.2",
    "eslint": "^6.5.1",
    "eslint-config-airbnb": "17.1.1",
    "eslint-plugin-import": "2.18.2",
    "eslint-plugin-jsx-a11y": "6.2.3",
    "eslint-plugin-react": "7.14.3",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.13.1"
  },

**Comment by Krizzu** [comment]
@tarasvakulka You need to go with manual linking, [you can find the docs here](https://react-native-async-storage.github.io/async-storage/docs/link#windows)

**Comment by flaviobvds** [comment]
I'm having the same issue and as I'm new to this, I wasn't able to link manually as @Krizzu recommended.
The instructions to link manually tell you to open your solution in Visual Studio, but so far I've only been using Visual Studio Code, in which I couldn't reproduce any of the steps in the doc. I even tried to download Visual Studio but it's a whole different software and I couldn't find my way through it in order to manually link it as the link instructs.

Can anyone help me? I`ve been looking for a solution for a week now, and I can't use AsyncStorage at all.
Thanks in advance.

**Comment by Krizzu** [comment]
cc @kaiguo, probably related to #494

**Comment by kaiguo** [comment]
@chrisglein

**Comment by ller2213** [comment]
I have the same question!

**Comment by jonthysell** [comment]
It looks like this should work once https://github.com/react-native-async-storage/async-storage/pull/494 is merged and published.
