### ISSUE TITLE
What is the per-value size limit? Is there a key name length limit?

### ISSUE THREAD

**Issue by CostachescuCristinel** [react-native-async-storage/async-storage#493]
## You want to:  
Ask question

## Details:
The docs report that there is a 6MB (default) total storage limit.
However, there is no indication whether there is any:
- key name length limit
- value length limit

Can you help me clarify those points?

**Comment by Krizzu** [comment]
This is the total recommended size of a whole storage file. Going over that limit could potentially cause some issues.

**Comment by Stevemoretz** [comment]
@Krizzu
You did not answer his question you just mentioned what he already knew, in android the file storage is not even used, it uses a database.

**Comment by dmitryame** [comment]
> @Krizzu
> You did not answer his question you just mentioned what he already knew, in android the file storage is not even used, it uses a database.

I'm assuming the mentioned database uses the underline file storage, so the same limits should apply
