### ISSUE TITLE
async-storage doesn't work on android 9.0

### ISSUE THREAD

**Issue by gwtjs** [react-native-async-storage/async-storage#495]
## Current behavior

async-storage doesn't work on android 9.0

when i close my app and restart, data is undefined

## Expected behavior

data always exists

## Repro steps

```
App.js

import AsyncStorage from '@react-native-async-storage/async-storage';

const saveData = (key, data) => {
  AsyncStorage.setItem(key, JSON.stringfy(data)).then(res=>{
    getData (key)
  }).catch(e=>console.log(e))
}

const getData = (key) => {
  return AsyncStorage.getItem(key).then(res=>{
    console.log(res);
    
    try {
      return JSON.parse(res)
    } catch (error) {
      return res
    }
  })
}
```
 i run saveData() successful and log is my saved data, but restart the app and run getData() method with the same key , the log is undefined;

## Environment

- **Platforms tested**:
  - [x] Android
  - [ ] iOS
  - [ ] macOS
  - [ ] Windows
- **AsyncStorage version**: 1.13.2
- **Environment**:
 "react-native": "0.63.3"
- **Logs/Errors that may be relevant**:

**Comment by mcanzerini** [comment]
A beta user of my app experience the same issue on android 9.0
Why did you close this issue ? Thanks

**Comment by spacewinds** [comment]
@mcanzerini 
I still experience this issue any workaround?

**Comment by rickydonald** [comment]
In iOS, it works fine, but on Android, AsyncStorage returns null. Any suggestions on that....
