### ISSUE TITLE
[@RNC/AsyncStorage]: NativeModule: AsyncStorage is null after expo eject

### ISSUE THREAD

**Issue by YuntongLi6543** [react-native-async-storage/async-storage#500]
Hi,

github source code here: https://github.com/Damon-Zhong/expo39-asyncstorage-bug/tree/master

My problem is as follows:

    1. Expo SDK 39.0.3
    2. Project is in bare workflow with expo eject.
    3. Async Storage is the only SDK used in the project, works fine in develop mode and simulator.
    4. After expo publish, app stuck at splash screen, error is:
       [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null
    5. manual link tried, not working.
    6. react-native link tried, not working
    7. pod install, not working

If need any information, please let me know.

Thanks. Do need help.

## Repro steps
github source code here: https://github.com/Damon-Zhong/expo39-asyncstorage-bug/tree/master

## Environment
- **AsyncStorage version**: 1.13.2
- **Environment**:
System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 9.24 GB / 15.93 GB
  Binaries:
    Node: 12.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: ~0.63.3 => 0.63.4

**Comment by israellopeztiscareno** [comment]
According to docs

https://react-native-async-storage.github.io/async-storage/docs/help/troubleshooting#rncasyncstorage-nativemodule-asyncstorage-is-null

Try expo publish --target managed

The default option target for publish is bare

**Comment by Krizzu** [comment]
I'm not familiar with expo, but can you use `expo publish` after you eject?
@brentvatne - mind having a look here? 🙏

**Comment by brentvatne** [comment]
> 3. Async Storage is the only SDK used in the project, works fine in develop mode and simulator.
> 4. After expo publish, app stuck at splash screen, error is:
   [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null

it sounds like you're trying to load it in expo client, or you're publishing with the wrong target. you can be explicit about it with `expo publish --target [managed|bare]` - if you want to open in expo client, you need to choose managed. otherwise, you need to choose bare. if you have more issues then please post to https://forums.expo.io/ 

@Krizzu - you can go ahead and close this
