### ISSUE TITLE
bundle release (apk) fail (compileReleaseJavaWithJavac)

### ISSUE THREAD

**Issue by zhang704** [react-native-async-storage/async-storage#501]
![image](https://user-images.githubusercontent.com/18161513/101146103-95e70f00-3655-11eb-9f9a-68190c6bd210.png)

i use
1. delete node_modules
2. yarn
3. ./gradlew assembleRelease

**Comment by tido64** [comment]
This is not an issue with AsyncStorage. Please see solution #496.
