### ISSUE TITLE
Obtaining tokens from async storage as null

### ISSUE THREAD

**Issue by lopeselio** [react-native-async-storage/async-storage#503]
## You want to:  
I want to get token for setting up automatic login in my react native app. I have written `getTokens` and `setTokens` functions as shown below:
```
export const getTokens = (cb) => {
    AsyncStorage.multiGet([
        '@NBA_App@token',
        '@NBA_App@refreshToken',
        '@NBA_App@expireToken',
        '@NBA_App@uid'
    ]).then(values => {
        cb(values);
    })
}

export const setTokens = (values, cb) => {
    const dateNow = new Date();
    const expiration = dateNow.getTime() + (3600* 1000)

    AsyncStorage.multiSet([
        ['@NBA_App@token', values.token],
        ['@NBA_App@refreshToken', values.refToken],
        ['@NBA_App@expireToken', expiration.toString()],
        ['@NBA_App@uid', values.uid]


    ]).then(response => {
        cb();
    })
}

```
## Details:
I am not able to get the tokens on reloading app using componentDidMount. I get the token array as 'null'.

![image](https://user-images.githubusercontent.com/43913734/101243572-4f61e500-3727-11eb-8012-70518ae33cba.png)

**Comment by Krizzu** [comment]
Hey @lopeselio 
We'd need more info about your env (RN version, Async Storage version etc.). Are you sure the values you save are not null?

**Comment by lopeselio** [comment]
Yes I am trying to save values which aren't null. I am using a bare react native app, version than 0.63

**Comment by Krizzu** [comment]
@lopeselio Can you provide a repo where you can reproduce the issue?

**Comment by lopeselio** [comment]
https://github.com/lopeselio/React-Native-NBA-app ... I did proceed further and implemented the auto-login for the app.

**Comment by tido64** [comment]
It looks like you're using a very [old version of React Native](https://github.com/lopeselio/React-Native-NBA-app/blob/main/package.json#L16), and you're using the [included version of Async Storage](https://github.com/lopeselio/React-Native-NBA-app/blob/b1a2764c253c2e3da06f6f53a35f65e2b422b841/app/utils/misc.js#L1). You're not using this module at all, so we can't really help you.
