### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by wabisabit** [react-native-async-storage/async-storage#506]
## Current behavior

When using async-storage-backend-web with react-native-web 0.14.9, the following runtime error occurs:

```
ReferenceError: require is not defined
eval
webpack-internal:///./node_modules/idb-keyval/dist/idb-keyval.mjs:2:30
Module../node_modules/idb-keyval/dist/idb-keyval.mjs
http://localhost:3000/static/js/1.chunk.js:1919:1
__webpack_require__
http://localhost:3000/static/js/bundle.js:849:30
fn
http://localhost:3000/static/js/bundle.js:151:20
    at eval (webpack-internal:///./node_modules/
react-native-community/async-storage-backend-web/build/index.js:18:18
./node_modules/@react-native-community/async-storage-backend-web/build/index.js
```

Since we don't need IndexedDB support, we removed the related code and it solved the issue for us.

## Expected behavior

There is no error

## Repro steps

Add the import `import WebStorage from '@react-native-community/async-storage-backend-web';`

## Environment

- **Platforms tested**:
  - [ ] Android
  - [ ] iOS
  - [x] macOS
  - [ ] Windows
- **AsyncStorage version**: 2.0.0-rc.3
- **Environment**:
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
    Memory: 4.12 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.19.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212 - /usr/bin/javac
    Python: 3.8.5 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

- **Logs/Errors that may be relevant**:

**Comment by tido64** [comment]
I think you should be using [`@react-native-async-storage/async-storage`](https://www.npmjs.com/package/@react-native-async-storage/async-storage). I don't think `@react-native-community/async-storage-backend-web` is supported any longer.

cc @Krizzu in case I'm mistaken.

**Comment by Krizzu** [comment]
Hey @wabisabit 

Unfortunately, `async-storage-backend-web` was a part of the experiment that is no longer continued. Please use [https://www.npmjs.com/package/@react-native-async-storage/async-storage](@react-native-async-storage/async-storage) package instead

**Comment by wabisabit** [comment]
Thank you for pointing me in the right way @tido64 and @Krizzu
