### ISSUE TITLE
Type com.reactnativecommunity.asyncstorage.AsyncStorageModule$5 is defined multiple times

### ISSUE THREAD

**Issue by Dharm3438** [react-native-async-storage/async-storage#508]
## Current behavior
I am not able to build a release for android its giving below error

Error: /home/mopharma/Downloads/working_hows_work/Copy of HOWS WORK 
 (1)/android/app/build/intermediates/transforms/FirebasePerformancePlugin/release/6/com/reactnativecommunity/asyncstorage/AsyncStorageModule$5.class, Type com.reactnativecommunity.asyncstorage.AsyncStorageModule$5 is defined multiple times: /home/mopharma/Downloads/working_hows_work/Copy of HOWS WORK (1)/android/app/build/intermediates/transforms/FirebasePerformancePlugin/release/6/com/reactnativecommunity/asyncstorage/AsyncStorageModule$5.class, /home/mopharma/Downloads/working_hows_work/Copy of HOWS WORK (1)/android/app/build/intermediates/transforms/FirebasePerformancePlugin/release/175/com/reactnativecommunity/asyncstorage/AsyncStorageModule$5.class

I already did clean rebuild project deleted the build and .gradle folders

also tried to exclude the package the package using the below code but then the app dosent works

        exclude group: 'com.facebook.react',module:'react-native-community-async-storage'

## Expected behavior

I can build my release for android

## Environment

- **Platforms tested**:
  - [x] Android
  - [ ] iOS
  - [ ] macOS
  - [ ] Windows
- **AsyncStorage version**: ^1.9.0
- **Environment**: Android
- **Logs/Errors that may be relevant**:

**Comment by tido64** [comment]
This is most likely not an issue with AsyncStorage, but with Firebase. Can you please see if this helps: https://github.com/firebase/firebase-android-sdk/issues/2142. Otherwise, please file an issue there.
