### ISSUE TITLE
Defined multiple times - Android

### ISSUE THREAD

**Issue by jawkhan** [react-native-async-storage/async-storage#515]
## Current behavior

When I try to build and run on Android, I get an issue that Async Storage has been defined multiple times.

## Expected behavior

Should allow me to build and run, without the above issue.

## Repro steps

Install async-storage for React Native via npm. Build and run app for android.

## Environment

- **Platforms tested**:
  - [x] Android
  - [ ] iOS
  - [ ] macOS
  - [ ] Windows
- **AsyncStorage version**: 1.13.2
- **Environment**:
System:
    OS: macOS 11.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 564.40 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.10 - ~/atom-projects/***-app/***/node_modules/.bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 26, 27, 28, 29
      Build Tools: 26.0.2, 28.0.3, 29.0.2
      System Images: android-26 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom_64, android-29 | Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
    Python: 2.7.15 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

- **Logs/Errors that may be relevant**: 
- Execution failed for task ':app:multiDexListDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Error while merging dex archives: 
     Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
     Type com.reactnativecommunity.asyncstorage.AsyncStorageModule$SerialExecutor$1 is defined multiple times: /Users/jawaad/atom-projects/***-app/***/node_modules/@react-native-async-storage/async-storage/android/build/intermediates/runtime_library_classes_jar/debug/classes.jar:com/reactnativecommunity/asyncstorage/AsyncStorageModule$SerialExecutor$1.class, /*/*/atom-projects/***-app/***App/node_modules/@react-native-community/async-storage/android/build/intermediates/runtime_library_classes_jar/debug/classes.jar:com/reactnativecommunity/asyncstorage/AsyncStorageModule$SerialExecutor$1.class

**Comment by tido64** [comment]
It looks like you have both `@react-native-community/async-storage` and `@react-native-async-storage/async-storage` installed. You only need the latter.

**Comment by aaryavrate** [comment]
I have only one installed plugin, but I still get the same error:
`
Type com.reactnativecommunity.asyncstorage.AsyncLocalStorageUtil is defined multiple times: /repo/node_modules/@react-native-async-storage/async-storage/android/build/.transforms/c9b366bec6c58b01af9a4f0b1b82207c/classes/classes.dex, /repo/android/app/build/intermediates/external_libs_dex/release/mergeExtDexRelease/classes3.dex`

**Comment by aaryavrate** [comment]
@tido64 In my case as above error shows, com.reactnativecommunity.asyncstorage is inside @react-native-async-storage/async-storage

I am using latest @react-native-async-storage/async-storage@16
