### ISSUE TITLE
Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null. 

### ISSUE THREAD

**Issue by ller2213** [react-native-async-storage/async-storage#516]
## Current behavior

**"react-native": "0.63.3",

yarn add @react-native-async-storage/async-storage
npx pod-install

import AsyncStorage from '@react-native-async-storage/async-storage';

yarn android**

I followed the step to install AsyncStorage  to my project. But when I import AsyncStorage from '@react-native-async-storage/async-storage',my project can't run and told me error .

The error is 'Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null'. 

my project's running environmental is android studio's emulator.

**Comment by Krizzu** [comment]
@ller2213 

Async Storage adds native dependencies, and because of that you need to re-install the app to make it work. Did you try to remove the app from emulator/device and retry? I assume `yarn android` is doing that for you?

**Comment by ller2213** [comment]
> @ller2213
> 
> Async Storage adds native dependencies, and because of that you need to re-install the app to make it work. Did you try to remove the app from emulator/device and retry? I assume `yarn android` is doing that for you?

I closed emulator and run my project, but it's still error.   whether you mean  I should yarn or npm install to re-install the app ?

**Comment by ller2213** [comment]
> @ller2213
> 
> Async Storage adds native dependencies, and because of that you need to re-install the app to make it work. Did you try to remove the app from emulator/device and retry? I assume `yarn android` is doing that for you?

Another computer  is ok, I will clean the running environmental ! Thanks for your help!
