### ISSUE TITLE
Is there anyway to migrate data from core async storage to community version?

### ISSUE THREAD

**Issue by Asadi123** [react-native-async-storage/async-storage#518]
In my released version, I was using core react-native async-storage and I changed in to community version in my developing version. The problem is when I test upgrading from old version to new version, all of the data saved in async-storage are gone. The reason I know it is deleted is, I stored my user data inside async-storage and they all are gone when new update is installed. When I try to migrate data manually, core async-storage does not have data inside it anymore. It only happens for sqlite android, ios working fine. Here is the code I use to migrate data manually.

`

    if (Platform.OS == "android") {
      const keys = await OldAsyncStorage.getAllKeys();

      if (keys) {
        console.warn("Migrate Started");

        OldAsyncStorage.multiGet(keys)
          .then((result) => {
            console.warn("Migrate got values" + result);

            if (result && result.length > 0) {
              console.warn("Transferring" + result);

              AsyncStorage.multiSet(result)
                .then(() => {
                  console.warn("Data Migration Success");

                  this._decideFirstScreen();
                })
                .catch((err) => {
                  console.warn("Error Uploaded");
                  this._decideFirstScreen();
                });
            }
          })
          .catch((err) => {
            console.warn("Error Uploaded");
            this._decideFirstScreen();
          });
      } else {
        console.warn("No Need to Migrate");

        this._decideFirstScreen();
      }
    } else {
      this._decideFirstScreen();
    }
  

`

## Details:
    @react-native-async-storage/async-storage: "^1.13.2",
    react-native: "0.62.2",
    old project react native: "0.59.10"

**Comment by Krizzu** [comment]
@Asadi123 
Actually, Community version is compatible with bundled AsyncStorage, so no need for migration. Have you tested it on fresh project? Maybe one of your dependencies uses AsyncStorage from the core, which is known for its race condition?

**Comment by Asadi123** [comment]
@Krizzu, yes, you are right, it was my fault. I was using another library for storage and didn't aware it.
