### ISSUE TITLE
Gracefully handle the case where inputs to multiSet are not of the type Array<Array<String>>

### ISSUE THREAD

**Issue by xiurobert** [react-native-async-storage/async-storage#519]
## Motivation
At present, React Native applications will crash when `AsyncStorage.multiSet` is called with invalid arguments, for example,  `AsyncStorage.multiSet(['a', 'b'], ['c', 'd'])`. Note that in this case, there are 2 arguments provided to the function for the `keyValuePairs` required to store as data. However, this happens to be a typo and the developer actually intended to wrap it with square brackets, but failed to do so. 

Since there is no error thrown, the application literally just crashes and makes debugging almost impossible.

## Description
An exception should be raised when the type of the inputs to the keyValuePairs argument of multiSet is incorrect, instead of simply letting the application crash.

## New feature implementation
Type comparison of the [first argument](https://github.com/react-native-async-storage/async-storage/blob/master/src/AsyncStorage.js#L135-L138) would be crucial in correcting this.

**Comment by kiranjd** [comment]
I would like to work on this

**Comment by tido64** [comment]
@kiranjd: Please go ahead and submit a PR 😃

**Comment by xiurobert** [comment]
@kiranjd Another possibility would be to handle the case where `multiSet` is called with n arguments

**Comment by kiranjd** [comment]
@xiurobert That approach might not work as the second arg could be passed as well. 
I'm thinking of checking if the second type is an array. If so, show the relevant warning message. What do you think?

**Comment by kiranjd** [comment]
As I looked to add regression tests, I see that `multiSet`, `muliGet`, and a few others are not covered in e2e tests. Hence, I have skipped tests as it would be outside the scope for the current PR. 

Maybe we can create adding tests as issues and then add them incrementally?
