### ISSUE TITLE
Storage is not retained after force quit and re-open of app

### ISSUE THREAD

**Issue by samtsai** [react-native-async-storage/async-storage#521]
## Current behavior

Items set via AsyncStorage seem to be cleared on apps that are forced quit and re-opened.

## Expected behavior

Storage should persist even if an app is forced quit and also with app updates (but I have not tested this scenario yet).

## Repro steps

Follow basic example code https://react-native-async-storage.github.io/async-storage/docs/api#useasyncstorage to get / set an item.

* on App load, `getItem`
* show a modal on first time loading the app and upon clicking the "Accept" button triggers the `setItem`
* switch out of the app
* come back and app state is remembered
* force quit
* re-open app
* modal dialog is shown again but shouldn't be if state is remembered

I've also added Sentry exception calls in the `catch` but not receiving any errors so I don't think AsyncStorage is failing.

## Environment

- **Platforms tested**:
  - [x] Android
  - [x] iOS
  - [ ] macOS
  - [ ] Windows
- **AsyncStorage version**: ^1.13.2
- **Environment**:
  
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 751.25 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.5.1 - /var/folders/36/vnmypcbj02xf8_c2fp8gnl700000gn/T/yarn--1610253002684-0.4976098686317718/node
    Yarn: 1.22.10 - /var/folders/36/vnmypcbj02xf8_c2fp8gnl700000gn/T/yarn--1610253002684-0.4976098686317718/yarn
    npm: 7.3.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Also using Expo SDK 40 in a managed workflow.

- **Logs/Errors that may be relevant**: 

Might be related to #517

**Comment by peracc** [comment]
Same here. It is somehow working on an Android emulator device and not working on a real android device (api 21).

**Comment by samtsai** [comment]
Works on iOS simulator as well, was able to confirm with logging to Sentry.

**Comment by samtsai** [comment]
Is this still true? https://react-native-async-storage.github.io/async-storage/docs/help/troubleshooting#rncasyncstorage-nativemodule-asyncstorage-is-null

This package will not work when using Expo in Managed workflow?

**Comment by peracc** [comment]
@samtsai I use bare workflow and still have this issue

**Comment by samtsai** [comment]
@peracc did this use to work for you? I have not used the library until now, I may try downgrading versions.

**Comment by peracc** [comment]
@samtsai Nope, I have not used it too

**Comment by peracc** [comment]
@samtsai Do you use redux-persist? Because I do. My case:

- App loads
- Start timer and save the state using 'redux-persist'
- App goes background, save the state directly using AsyncStorage.setItem('persist:<my_key', adaptToReduxPersist(state))
- App closes
- 'redux-persist' loads last persisted state.

I have to use backgroundTimer to save state when app is background. The problem is that 'redux-persist' uses setTimeout to persist state using AsyncStorage which (setTimeout) does not work in background, so I have to save the state directly using AsyncStorage. 
It is not the best solution (probably, not a good at all) but for me it is working now. But I'm still testing. 

**PS**
To set state directly in AsyncStorage I serialize the state like this: 
`function adaptToReduxPersist(mockValue) {
  // redux-persist converts total value and top-level properties to //string:
  // Es: {a: {foo: 'bar'}} -> {a: JSON.stringify({foo: 'bar'})} -> //JSON.stringify({a: JSON.stringify({foo: 'bar'})});
  // so in order for the tests to work properly, we need to simulate //this behavior
  const partialConversion = Object.keys(mockValue).reduce((acc, key) => {
    acc[key] = JSON.stringify(mockValue[key]);
    return acc;
  }, {});
  return JSON.stringify(partialConversion);
}`
[(source)](https://stackoverflow.com/questions/64953658/cypress-how-to-set-local-storage-using-redux-persist-lib-storage)

**Comment by samtsai** [comment]
Hm... interesting. My use case is fairly simple, no `redux-persist` just:

- check for existing storage key
- skip modal if it exists
- show modal if it doesn't exist
- user clicks button on modal and it saves to storage

So next time opening the app it should not show the modal, whether that's force quit, hopefully update will just work too, or bring app up from background.

**Comment by tido64** [comment]
@samtsai: Are you using Expo's managed workflow? If so, you cannot use this module as explained here: https://docs.expo.io/introduction/managed-vs-bare/. Otherwise, please provide a minimal repro if you want us to take a look.

**Comment by samtsai** [comment]
> @samtsai: Are you using Expo's managed workflow? If so, you cannot use this module as explained here: https://docs.expo.io/introduction/managed-vs-bare/. Otherwise, please provide a minimal repro if you want us to take a look.

Yes I am using managed workflow, it just wasn't clear in the docs that this project doesn't support managed.

Looks like I'll plan to `eject` and try it out that way.

**Comment by tido64** [comment]
To be clear, this is not AsyncStorage not supporting Expo's managed workflow. It's the other way around.

![Screenshot 2021-01-13 at 20 43 32](https://user-images.githubusercontent.com/4123478/104501628-44c92400-55e0-11eb-9302-5e7a15add041.png)

**Comment by samtsai** [comment]
It's also confusing because of https://expo.canny.io/feature-requests/p/continued-support-for-asyncstorage. I will ask the Expo group.

**Comment by Krizzu** [comment]
[Expo is supported through using a deprecated version of AsyncStorage](https://github.com/react-native-async-storage/async-storage/blob/master/src/RCTAsyncStorage.expo.js) (that comes with react-native itself). This was mainly to avoid confusion on which version should be used (community or bundled).

@samtsai Care to provide a code snippet/repo that can reproduce the issue?

**Comment by samtsai** [comment]
> [Expo is supported through using a deprecated version of AsyncStorage](https://github.com/react-native-async-storage/async-storage/blob/master/src/RCTAsyncStorage.expo.js) (that comes with react-native itself). This was mainly to avoid confusion on which version should be used (community or bundled).
> 
> @samtsai Care to provide a code snippet/repo that can reproduce the issue?

To my embarrassment, it was an implementation detail that caused this. Thanks for the clarification @Krizzu and @tido64  
I have it working now and published the app to production!

**Comment by tido64** [comment]
> [Expo is supported through using a deprecated version of AsyncStorage](https://github.com/react-native-async-storage/async-storage/blob/master/src/RCTAsyncStorage.expo.js) (that comes with react-native itself). This was mainly to avoid confusion on which version should be used (community or bundled).

Honestly, this causes more confusion than simply saying we bundle a copy of AsyncStorage and you should be using that version. Now we get an influx of people not understanding how this works and file a bug here instead of asking Expo forums.

**Comment by Krizzu** [comment]
> Honestly, this causes more confusion than simply saying we bundle a copy of AsyncStorage and you should be using that version. Now we get an influx of people not understanding how this works and file a bug here instead of asking Expo forums.

I hear ya - there was a lot of confusion regarding Async Storage becoming it's own module and Expo usage, hence the decision to "support" the platform.

**Comment by eddskt** [comment]
Hi @samtsai I'm having this problem, of "non-persistence" after force quit and re-open app but I'm not finding where I could be wrong, can you comment specifically where your mistake was?
I'm using Expo-Cli, and I did all the Store Data processes on documentation, but when I close and open the app, there's nothing there, even checking the logs. Thanks

**Comment by samtsai** [comment]
> Hi @samtsai I'm having this problem, of "non-persistence" after force quit and re-open app but I'm not finding where I could be wrong, can you comment specifically where your mistake was? I'm using Expo-Cli, and I did all the Store Data processes on documentation, but when I close and open the app, there's nothing there, even checking the logs. Thanks
> 
> I know it's been a while since this post, but remembering anything or path you took will help me a lot
> 
> Expo-Cli, Mac M1, iPhone 13 Simulator, iOS 15.5

I cannot remember the exact issue I had and without a code snippet of your need I won't really be able to provide much information. Async storage as in the examples works fine and we use Context providers to pass around some of the relevant information.

**Comment by SnowingFox** [comment]
> Hi @samtsai I'm having this problem, of "non-persistence" after force quit and re-open app but I'm not finding where I could be wrong, can you comment specifically where your mistake was?
> I'm using Expo-Cli, and I did all the Store Data processes on documentation, but when I close and open the app, there's nothing there, even checking the logs. Thanks
> 
> I know it's been a while since this post, but remembering anything or path you took will help me a lot
> 
> Expo-Cli, Mac M1, iPhone 13 Simulator, iOS 15.5

have u solve it?

**Comment by wnorris** [comment]
This may be relevant but no solution presented. Also weird it works for us in some places and not others.

https://github.com/react-native-async-storage/async-storage/issues/521
