### ISSUE TITLE
AsyncStorage is null

### ISSUE THREAD

**Issue by ivy-mihai** [react-native-async-storage/async-storage#525]
## Current behavior

I've installed the package and imported it into a component and I've received this error on the iOs simulator screen and android phone screen: [@RNC/AsyncStorage]: AsyncStorage is null.

## Expected behavior

I was expected to be able to use the library.

## Repro steps
1. expo install @react-native-async-storage/async-storage
2. expo start
3. write import AsyncStorage from '@react-native-async-storage/async-storage'; in App.js
4. The exception has been raised.
![image](https://user-images.githubusercontent.com/36970847/104858275-8b8f8480-5926-11eb-91df-8254113aca02.png)

## Environment

- **Platforms tested**:
  - [x] Android
  - [x] iOS
  - [x] macOS
  - [ ] Windows
- **AsyncStorage version**:     ^1.13.2
- **Environment**:
info Fetching system and libraries information...
System:
    OS: macOS 11.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.24 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.10 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
    react-native-macos: ^0.63.4 => 0.63.4 
  npmGlobalPackages:
    *react-native*: Not Found
mihaiivascu@mihais-mbp infinity-react-native-client %

**Comment by tido64** [comment]
Are you using Expo managed workflow? If so, you cannot use this module because it has native components. Please read Expo's documentation: https://docs.expo.io/introduction/managed-vs-bare/#workflow-comparison

**Comment by ivy-mihai** [comment]
> Are you using Expo managed workflow? If so, you cannot use this module because it has native components. Please read Expo's documentation: https://docs.expo.io/introduction/managed-vs-bare/#workflow-comparison

I've installed the package following expo documentation which has brought me here: https://docs.expo.io/versions/v40.0.0/sdk/async-storage/  

"expo install @react-native-async-storage/async-storage
Installing 1 other package using npm.
> npm install --save @react-native-async-storage/async-storage"

**Comment by tido64** [comment]
You might be able to find more help in Expo's forums, such as here: https://forums.expo.io/t/expo-40-rn-asyncstorage-nativemodule-asyncstorage-is-null/46757.

As this is not really bug with AsyncStorage, I'm closing this issue.

**Comment by ivy-mihai** [comment]
> You might be able to find more help in Expo's forums, such as here: https://forums.expo.io/t/expo-40-rn-asyncstorage-nativemodule-asyncstorage-is-null/46757.
> 
> As this is not really bug with AsyncStorage, I'm closing this issue.

Ok, thanks for the recommendations.
