### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by Prashoon123** [react-native-async-storage/async-storage#530]
## You want to:  

I want to add an **Installation** method in the README.md file.

## Details:

There should be an **Installation** method given in the [README.md](https://github.com/react-native-async-storage/async-storage/blob/master/README.md) file.

**Comment by Krizzu** [comment]
Hey, 

Installation is available in documentation, that's [linked in README.](https://react-native-async-storage.github.io/async-storage/docs/install/)

thanks

**Comment by Prashoon123** [comment]
Ok @Krizzu!
