### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by Prashoon123** [react-native-async-storage/async-storage#531]
#### The link to the documentation on the npm page is broken.
![image](https://user-images.githubusercontent.com/64588766/105376823-2d1d1b80-5c30-11eb-8bd9-9ab330d3d000.png)
![image](https://user-images.githubusercontent.com/64588766/105377106-78372e80-5c30-11eb-8f17-cd1fc845d41c.png)

## Expected behavior
The link should have worked.

**Comment by tido64** [comment]
This package was recently renamed: https://www.npmjs.com/package/@react-native-async-storage/async-storage

**Comment by Prashoon123** [comment]
Ok
