### ISSUE TITLE
Access Async-Storage data from the native container

### ISSUE THREAD

**Issue by awaldron** [react-native-async-storage/async-storage#534]
## You want to:  
Ask a question

## Details:
I'm building an app that will require some native functionality. I'm storing the auth token in AsyncStorage and I'd like the native app to be able to access that token. Is that possible?

**Comment by Krizzu** [comment]
Currently it's only available [for iOS only, through delegate](https://react-native-async-storage.github.io/async-storage/docs/advanced/brownfield)
