### ISSUE TITLE
  Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.

### ISSUE THREAD

**Issue by laibagill** [react-native-async-storage/async-storage#541]
## Current behavior

To fix this issue try these steps:

  • Run `react-native link @react-native-async-storage/async-storage` in the project root.

  • Rebuild and restart the app.

  • Run the packager with `--reset-cache` flag.

  • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app.

  • If this happens while testing with Jest, check out docs how to integrate AsyncStorage with it: https://react-native-async-storage.github.io/async-storage/docs/advanced/jest

If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-async-storage/react-native-async-storage/issues

[Tue Feb 09 2021 12:09:31.370]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

 These steps are not working infact giving error like autolinking is deprecated

**Comment by tido64** [comment]
Please don't delete the template when filing new issues. They're there so we can better help you.

- What version are you using?
- Provide information about your dev environment: Run `yarn react-native info` and paste the output here.
- Provide repro steps or a minimal project with the bug reproducible. We cannot help you if we can't repro this locally.

Are you using Expo? If so, please have a look in their forum instead: https://forums.expo.io/t/expo-40-rn-asyncstorage-nativemodule-asyncstorage-is-null/46757/4

**Comment by jiaxiangcheng** [comment]
I have the same problem with expo managed flow project. Last night was everything fun to run on my virtual devices and today at the morning is start to show:

Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.
To fix this issue try these steps:
  • Run `react-native link @react-native-async-storage/async-storage` in the project root.
  • Rebuild and restart the app.
  • Run the packager with `--reset-cache` flag.
  • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app.
  • If this happens while testing with Jest, check out docs how to integrate AsyncStorage with it: https://react-native-async-storage.github.io/async-storage/docs/advanced/jest

If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-async-storage/react-native-async-storage/issues

I can't run "yarn react-native info" then I ran "npm react-native info" and showed me this:
————————————————————————————————————————————————————————————————————————————————
npm help config                                                           info:7
npm help registry                                                         info:7
npm help package-lock-json                                                info:6
npm help package-json                                                     info:5
npm help npm                                                              info:4
npm help ls                                                               info:3
npm help view                                                             info:3
npm help developers                                                       info:3
npm help audit                                                            info:2
npm help fund                                                             info:2
————————————————————————————————————————————————————————————————————————————————
(run with -l or --long to see more context)

I am using:
"@react-native-async-storage/async-storage": "^1.13.4"
"expo": "~40.0.0"
"react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz"

I looked this link https://forums.expo.io/t/expo-40-rn-asyncstorage-nativemodule-asyncstorage-is-null/46757/4 but it doesn't help me. My metro.config.js is:

`const { getDefaultConfig } = require("metro-config");

module.exports = (async () => {
    const {
        resolver: { sourceExts, assetExts },
    } = await getDefaultConfig();
    return {
        transformer: {
            babelTransformerPath: require.resolve(
                "react-native-svg-transformer"
            ),
        },
        resolver: {
            assetExts: assetExts.filter((ext) => ext !== "svg"),
            sourceExts: [...sourceExts, "svg"],
        },
    };
})();
`

**Comment by tido64** [comment]
@jiaxiangcheng: You're supposed to import `getDefaultConfig` from `@expo/metro-config`, not `metro-config`. :)

**Comment by jiaxiangcheng** [comment]
> @jiaxiangcheng: You're supposed to import `getDefaultConfig` from `@expo/metro-config`, not `metro-config`. :)

Thanks for answering so quickly. I tried to change to: 
- const { getDefaultConfig } = require("@expo/metro-config");

And it still not working. It showed me:
![image](https://user-images.githubusercontent.com/17082256/107341583-750cc100-6abf-11eb-8a99-96348260bb77.png)

My version is "@expo/metro-config": "^0.1.54".

**Comment by tido64** [comment]
@jiaxiangcheng: Please ask in Expo's forums. I think you'll get better answers there. I have no experience with Expo myself.

**Comment by jiaxiangcheng** [comment]
> @jiaxiangcheng: Please ask in Expo's forums. I think you'll get better answers there. I have no experience with Expo myself.

I have resolved by changing these lines:

const { getDefaultConfig } = require("metro-config"); -> const { getDefaultConfig } = require("@expo/metro-config");

const { resolver: { sourceExts, assetExts }, } = await getDefaultConfig();  -> const { resolver: { sourceExts, assetExts }, } = await getDefaultConfig(__dirname);

Thanks for your idea to fix the problem!!!!
