### ISSUE TITLE
While running jest for project getting the error 

### ISSUE THREAD

**Issue by JatinPreetAxtria** [react-native-async-storage/async-storage#557]
Test suite failed to run

    [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.
To fix this issue try these steps:

      • Run `react-native link @react-native-async-storage/async-storage` in the project root.

      • Rebuild and restart the app.

      • Run the packager with `--reset-cache` flag.

      • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app.

      • If this happens while testing with Jest, check out docs how to integrate AsyncStorage with it: https://react-native-async-storage.github.io/async-storage/docs/advanced/jest

    If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-async-storage/react-native-async-storage/issues

      at Object.<anonymous> (node_modules/@react-native-async-storage/async-storage/lib/commonjs/AsyncStorage.native.js:17:9)
      at Object.<anonymous> (node_modules/@react-native-async-storage/async-storage/lib/commonjs/index.js:6:1)

## Expected behavior

test should run succesfully as it is not testing asyncstorage. 
## Repro steps

write test case  in app_test.js
test('add numbers',() => 
{
    expect(addnumber(1,2)).toEqual(3);
}
)

and run npm test

## Environment

- **Platforms tested**:
  - [ ] iOS
  
- **AsyncStorage version**: ^1.13.4

**Comment by Krizzu** [comment]
Guess you have to have a look at [jest integration docs](https://react-native-async-storage.github.io/async-storage/docs/advanced/jest)

**Comment by Krizzu** [comment]
hey, did it work for you or you need some help?

**Comment by JatinPreetAxtria** [comment]
no it doesn’t work

**Comment by Krizzu** [comment]
Can you share an example repository, where you can reproduce the issue?

**Comment by JatinPreetAxtria** [comment]
Please find the repo link
https://github.com/JatinPreetAxtria/AsyncStorageIssue/tree/main/SalesIQMobile

**Comment by tido64** [comment]
> @Krizzu: Guess you have to have a look at [jest integration docs](https://react-native-async-storage.github.io/async-storage/docs/advanced/jest)

@JatinPreetAxtria: Can you please follow the instructions as @Krizzu pointed out here?

**Comment by JatinPreetAxtria** [comment]
Try Above integration docx but still getting same error. 


 FAIL  __tests__/App-test.js
  ● Test suite failed to run

    @react-native-community/netinfo: NativeModule.RNCNetInfo is null. To fix this issue try these steps:

    • Run `react-native link @react-native-community/netinfo` in the project root.
    • Rebuild and re-run the app.
    • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
    • Check that the library was linked correctly when you used the link command by running through the manual installation instructions in the README.
    * If you are getting this error while unit testing you need to mock the native module. Follow the guide in the README.

    If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-netinfo

      at Object.<anonymous> (node_modules/@react-native-community/netinfo/lib/commonjs/internal/nativeInterface.ts:15:9)
      at Object.<anonymous> (node_modules/@react-native-community/netinfo/lib/commonjs/internal/state.ts:11:1)

 FAIL  js/test.js
  ● Test suite failed to run

    /Users/ab/Documents/SalesIQMobileBackup/SalesIQMobile/SalesIQMobile/node_modules/@react-navigation/stack/lib/commonjs/views/assets/back-icon.png:1
    �PNG


    SyntaxError: Invalid or unexpected token

      at Runtime._execModule (node_modules/jest-runtime/build/index.js:1157:58)
      at Object.<anonymous> (node_modules/@react-navigation/stack/lib/commonjs/index.tsx:13:3)

A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --runInBand --detectOpenHandles to find leaks.
Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        8.625s
Ran all test suites.
npm ERR! code 1
npm ERR! path /Users/ab/Documents/SalesIQMobileBackup/SalesIQMobile/SalesIQMobile
npm ERR! command failed
npm ERR! command sh -c jest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ab/.npm/_logs/2021-04-23T05_45_47_154Z-debug.log

**Comment by tido64** [comment]
> ```
> @react-native-community/netinfo: NativeModule.RNCNetInfo is null. To fix this issue try these steps:
> ```

That doesn't look like an AsyncStorage error. I'm going to close this issue now 😄
