### ISSUE TITLE
Increasing storage size without gradle.properties

### ISSUE THREAD

**Issue by mmahandev** [react-native-async-storage/async-storage#558]
## Motivation

I'm currently using Expo's managed workflow and I can't change the max storage size without switching to a bare workflow.

Is there a way we can change the max storage size without editing `gradle.properties` or just removing the size limit entirely?

## New feature implementation

Alternate way of editing max storage size or (preferably) removing the max size.

**Comment by tido64** [comment]
If you're using Expo, this module essentially just proxies back to the native module living in Expo. You should check Expo's forums for answers. That said, it doesn't look like it's possible according to this thread: https://forums.expo.io/t/increase-asyncstorage-size-using-expo/29516

**Comment by mmahandev** [comment]
@tido64 Is the file size not set right here? https://github.com/react-native-async-storage/async-storage/blob/87805694cc8ee07c594ef4c8f56caf4163acb498/android/src/main/java/com/reactnativecommunity/asyncstorage/ReactDatabaseSupplier.java#L104

Can't this be removed?

**Comment by tido64** [comment]
Like I said earlier, the Expo managed apps are not using this module directly. Even if we removed that line today, you won't be able to use it in Expo unless you eject.
