### ISSUE TITLE
Uninstalling the app does not clear storage

### ISSUE THREAD

**Issue by kafkas** [react-native-async-storage/async-storage#561]
This is a well-known issue that was previously tracked at #342 I have upgraded the module to the latest version and have added the `RCTAsyncStorageExcludeFromBackup` key with `true` value to `info.plist` exactly how it's described [here](https://react-native-async-storage.github.io/async-storage/docs/advanced/backup). The storage is still not wiped when the app is uninstalled.

**Comment by fedemartinm** [comment]
Hey @kafkas, same problem here.. how did you solve it?
thank you

**Comment by kafkas** [comment]
In my case, it turned out to be a problem with `react-native-keychain` which we were using alongside AsyncStorage so I closed the issue straight away.

**Comment by fedemartinm** [comment]
Oh, so it's another problem. thanks

**Comment by LucioHenrique512** [comment]
> In my case, it turned out to be a problem with `react-native-keychain` which we were using alongside AsyncStorage so I closed the issue straight away.

Hi @kafkas, how did you solve this?

**Comment by sLurPPPeRsTaR** [comment]
for those who still lookin this answer and stop by in this forum, i found the culprit hopefuly its help

![image](https://github.com/user-attachments/assets/35eef57a-146c-4ab2-8452-e09d4af83562)
