### ISSUE TITLE
Execution failed for task ':@react-native-async-storage:packageDebugAndroidTest'.

### ISSUE THREAD

**Issue by Quandm1195** [react-native-async-storage/async-storage#562]
Hello,
We are running a react native app using async-storage manual linkage. The build for android ("./gradlew app:assembleDebug assembleAndroidTest -DtestBuildType=debug") throws this error randomly:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':@react-native-async-storage:packageDebugAndroidTest'.
> 1 exception was raised by workers:
  java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: !directory.isDirectory()

This is quite annoying because it fails the build randomly in our CI which makes it not reliable. Is there any pointers that you can help?

We have tried to rm -rf node_modules and npm i, followed by gradlew clean. But the issue still persists. Thank you

**Comment by tamangsuresh** [comment]
I'm also facing this issue.

**Comment by Krizzu** [comment]
Hey @Quandm1195 

Can you tell me which version of AsyncStorage you use? Also, can you provide full stack for the error?

**Comment by tamangsuresh** [comment]
I solve this by deleting app, node_modules, clearing cache and building from android studio.

**Comment by RezaHabibi1001** [comment]
same problem here ,  please help

**Comment by xwiz** [comment]
Did you figure it out?

> same problem here , please help
