### ISSUE TITLE
Storage items persist after uninstall on Android device

### ISSUE THREAD

**Issue by mdbiscan** [react-native-async-storage/async-storage#569]
## Current behavior
I'm using AsyncStorage for persisted storage. I noticed (while debugging an unrelated issue with Expo SecureStore) that the key/value pairs are persisting after I've uninstalled the app from my device.

I've tried the following:

- Ran `./gradlew clean` in the android directory
- Rebuilt the android directory from scratch
- Removed all cache files and directories from the project (.gradle, .expo, etc)
- Used `AsyncStorage.clear()` and `AsyncStorage.removeItem()` 
- Used storage analyzers to search for data (didn't find anything)
- Manually removed storage and cache through Android Settings -> Apps & Notifications
- Uninstalled the app from the device 
- Deleted Expo Go app and removed it's storage and cache 

It is my understanding that uninstalling the app should also remove persisted storage. However, this issue goes beyond this assumption if I am incorrect.

The items always show up _after_ I uninstall and reinstall the app. Reloading the app does not have this same issue. I read through some old/closed issues here that showed others having this problem, with solutions that have not worked for me. Even after using `AsyncStorage.clear()` or `AsyncStorage.removeItem()`, the items will appear on every _new_ install, but only _after_ the app has been uninstalled from the device.

## Expected behavior

After new installation or removing them, the storage items should no longer exist on the device.

## Repro steps

1. Remove storage items with `AsyncStorage.clear()` or `AsyncStorage.removeItem()`
2. Delete app storage and cache in Android `Settings -> Apps & Notifications`
3. Uninstall the app from the device
4. Stop `react-native`
5. Run `./gradlew clean` in the android directory
6. Start `react-native` with `--reset-cache` flag
7. Run `react-native run-android` to install the app

## Environment

- **Platforms tested**:
  - [x] Android
  - [ ] iOS
  - [ ] macOS
  - [ ] Windows
- **AsyncStorage version**: 1.14.1
- **Expo version**: SDK40 (bare workflow)
- **Environment**: 
  System:
    OS: Linux 5.8 Pop!_OS 20.10
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 12.40 GB / 31.08 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.4/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.15.4/bin/npm
    Watchman: Not Found _(Watchman is global)_
  SDKs:
    Android SDK: Not Found _(it sure does, it's in my home directory)_
  IDEs:
    Android Studio: Not Found _(not using android studio)_
  Languages:
    Java: 11.0.10 - /usr/bin/javac
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ~0.63.4 => 0.63.4 
  npmGlobalPackages:
    *react-native*: Not Found _(uses npx version)_

**Comment by Krizzu** [comment]
Hey @mdbiscan , thanks for filling in all the details!

One thing that comes to my mind is Auto back up of user data, that's enabled by default for devices targeting Android API 23+. You mention that you search through old issue, so I guess you tried to disable it? (dunno if you have access to manifest file in Expo app)

Is your project ejected? Are you able to reproduce this on non-expo app (`react-native init`)? Could it be that some of the other dependencies doing the backup or maybe Expo is doing backups? cc @brentvatne

**Comment by mdbiscan** [comment]
@Krizzu thanks for the reply!

The project is ejected. I hadn't thought of Auto Backup. I read about automatic exclusion to iCloud for iOS devices, but didn't see one for Android. I will look into it.

**Comment by mdbiscan** [comment]
Looks like this setting in the `AndroidManifest.xml` file is on by default: `android:allowBackup="true"`

For future reference, this is the generated XML element:

```xml
  <application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher_round" android:allowBackup="true" android:theme="@style/AppTheme">
```
Setting this to false solves the issue. I'm not sure this is a good idea or not, as we also use keychain storage. I'm not sure if this backup feature also saves encrypted storage to the cloud.

Either way, thanks for pointing me in the right direction. I figured it might be some obtuse setting.

**Comment by Zhou-Bill** [comment]
ios has the same problem, how to solve in ios?

**Comment by Krizzu** [comment]
Did you try to disable iCloud backup? 
[documentation](https://react-native-async-storage.github.io/async-storage/docs/advanced/backup)

**Comment by Noitidart** [comment]
Hey @mdbiscan and @krizzu, does this apply to the Documents Directory pointed to by FileSystem.documentsDirectory? On iOS and Android?

I think I'm having some bugs due to this its just a hunch. I'm going to try to set that allowBackup to false in xml for Android, how could I do this for iOS?

Not using AsyncStorage but Expo filesystem - https://docs.expo.dev/versions/latest/sdk/filesystem/

**Comment by bryanltobing** [comment]
https://github.com/react-native-async-storage/async-storage/issues/569#issuecomment-808319211

i tried this in my current my project, and a repro project

both have `android:allowBackup="true"`

but only in my current project that the async storage data persist upon app uninstall and reinstall

in my repro project which is new expo project, data will be removed after i reinstall the app.

still not sure how to fix this

**Comment by yushanwebdev** [comment]
@mdbiscan, you saved my day
