### ISSUE TITLE
Should I be still using this package?

### ISSUE THREAD

**Issue by 16ntu1120** [react-native-async-storage/async-storage#570]
I found this package deprecated should I be still using it? Need suggestions.

**Comment by Krizzu** [comment]
Hey,

`AsyncStorage` is marked as `deprecated` in `React Native`, because it was extracted to a separate package (this repo). So ideally, if you used previously3 AsyncStorage from `react-native` package, you should use this one instead

**Comment by 16ntu1120** [comment]
@Krizzu okay thanks man
