### ISSUE TITLE
Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.

### ISSUE THREAD

**Issue by markegor** [react-native-async-storage/async-storage#572]
Hey! I have an error "**Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.**" =(
Even after i tried make every step by instruction: "Run `react-native link @react-native-async-storage/async-storage` in the project root." - i still have **the same problem**

**Comment by tido64** [comment]
Please don't delete the template when filing new issues. They're there so we can better help you.

- What version of AsyncStorage are you using?
- Provide information about your dev environment: Run `yarn react-native info` and paste the output here.
- Provide repro steps or a minimal project with the bug reproducible. We cannot help you if we can't repro this locally.

**Comment by markegor** [comment]
I have solve a problem by myself. Just delete "**./ios**" and "**./android**" folders and run "**npx react-native eject**" command

**Comment by TommyLeong** [comment]
> I have solve a problem by myself. Just delete "**./ios**" and "**./android**" folders and run "**npx react-native eject**" command

Are we suppose to `eject react native` to solve this issue? 🤔  I'm facing this issue too

**Comment by tido64** [comment]
You're supposed to set up Metro to also include `*.expo.js` files. Please see the Expo forum: https://forums.expo.io/t/expo-40-rn-asyncstorage-nativemodule-asyncstorage-is-null/46757/4

**Comment by TommyLeong** [comment]
Hm, I don't actually use Expo.

**Comment by tido64** [comment]
@TommyLeong: Please open a new issue and fill out all the details so we can better help you.
