### ISSUE TITLE
Access to async storage in Swift Extension / library not found

### ISSUE THREAD

**Issue by sinclas** [react-native-async-storage/async-storage#580]
## You want to:  
Hi,
Storage works great in React Native.  Now, I am extending some functionality of the IOS app to work in an application extension. This library was added using pods and I can reference the. "libRNCAsyncSAtorage.a" in build link but get a library not found issue.   I am on a MacBook Pro M1.  Always reference this since the build lib may have issues.  

Thanks!
S

**Comment by jamesdunay** [comment]
make sure to have the AsyncStorage pod added to your extension 

`target 'ShareExtension' do
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'
end`
