### ISSUE TITLE
Setup async-storage for macOS

### ISSUE THREAD

**Issue by nikgraf** [react-native-async-storage/async-storage#587]
## Current behavior

I followed the steps here https://react-native-async-storage.github.io/async-storage/docs/link/#macos

Everything until the 4th step is clear. Then I added the `libRNCAsyncStorage-macOS.a` in the `Build Phases`
of the target `desktop-macOS`.

When I run ` npx react-native run-macos` I get this error. What's odd is is that this is referencing the ios directory.

```
/node_modules/@react-native-async-storage/async-storage/ios/RNCAsyncStorage.h:10:9: fatal error: 'React/RCTBridgeModule.h' file not found
#import <React/RCTBridgeModule.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

## Expected behavior

Get 

## Repro steps

Can provide an example repo in case the above description doesn't help.

## Environment

- **Platforms tested**:
  - [ ] Android
  - [ ] iOS
  - [x] macOS
  - [ ] Windows
- **AsyncStorage version**: 1.15.2
- **Expo version**: 
- **Environment**:

```
System:
    OS: macOS 11.1
    CPU: (8) x64 Apple M1
    Memory: 294.54 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: ^0.63.0-0 => 0.63.23 
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Logs/Errors that may be relevant**:

**Comment by tido64** [comment]
@nikgraf If you're on 0.63, autolinking should just work. You don't need to do the manual steps.

**Comment by nikgraf** [comment]
ahhh right, I had to change `platform :macos, '10.14'` but then it worked. Thanks for the info!

**Comment by haveamission** [comment]
@nikgraf So you didn't have to link manually? This page seems to suggest you still seem to:

https://react-native-async-storage.github.io/async-storage/docs/link

Is this out of date?

**Comment by nikgraf** [comment]
correct

**Comment by mmazzarolo** [comment]
> ahhh right, I had to change `platform :macos, '10.14'` but then it worked. Thanks for the info!

+1, changing `platform :macos, '10.14'` in `Podfile` and running `pod install` auto-links correctly 👍
