### ISSUE TITLE
app crash when import asyncstorage

### ISSUE THREAD

**Issue by oguzhan10** [react-native-async-storage/async-storage#593]
I install "npm install @react-native-async-storage/async-storage" in my react-native app. When I import AsyncStorage, app crash. I cant open my app and also app does not give me an error. I don't know why?
API 30;
Android 11.0;
react-native version:0.63.4;
npm version: 6.14.9

I download my app to my phone and I expand the error and it is;
java lang runtime unable to instantiate java.lang.runtime instance, java.lang.ClassNıtFoundExecption: Didn't find class" com.appname."

import AsyncStorage from '@react-native-async-storage/async-storage';

When I also install other packages for example fontawesome or react-native-vector-icons

**Comment by tido64** [comment]
Please don't delete the template when filing new issues. They're there so we can better help you.

- What version are you using?
- Provide information about your dev environment: Run `yarn react-native info` and paste the output here.
- Provide repro steps or a minimal project with the bug reproducible. We cannot help you if we can't repro this locally.
