### ISSUE TITLE
 [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null

### ISSUE THREAD

**Issue by JigmeLodey** [react-native-async-storage/async-storage#596]
## Environment

- **Platforms tested**:
  - [x] Android
  - [ ] iOS
  - [ ] macOS
  - [x] Windows
- **AsyncStorage version**: 
- **Expo version**: 
- **Environment**:
  
- **Logs/Errors that may be relevant**:

**Comment by tido64** [comment]
Please fill out the template when filing new issues. They're there so we can better help you.

- What version are you using?
- Provide information about your dev environment: Run `yarn react-native info` and paste the output here.
- Provide repro steps or a minimal project with the bug reproducible. We cannot help you if we can't repro this locally.

**Comment by ZincPartnersDev** [comment]
having the same behavior. upgraded Expo from sdk 39 to sdk 41 and this is what's happening
<img width="372" alt="iPhone_12_Pro_Max" src="https://user-images.githubusercontent.com/68075456/116914256-7cec8500-ac18-11eb-856c-fda3c7f2ddcb.png">

same codebase with SDK 39 works.

**Comment by tido64** [comment]
For all Expo related issues, please use Expo's forums. This one in particular might be of interest: https://forums.expo.io/t/expo-40-rn-asyncstorage-nativemodule-asyncstorage-is-null/46757

**Comment by JigmeLodey** [comment]
i am using react-native and testing in android, since i have implement this storage i have getting issue, i tried all way like removing node module and resting my react cache still having same problem

**Comment by ZincPartnersDev** [comment]
Found the root cause for my problem, not an issue with this plugin BUT third party plugin that require it:
As of Expo SDK 41  @react-native-community/async-storage got renamed to @react-native-async-storage/async-storage. There's a plugin that hasn't updated their code to point to the right one. Now that I see my screenshot, it's clear.

**Comment by tido64** [comment]
> i am using react-native and testing in android, since i have implement this storage i have getting issue, i tried all way like removing node module and resting my react cache still having same problem. I using NX with React native

@JigmeLodey: You still need to fill out the template. We don't know what your set up looks like.

- What version are you using?
- Provide information about your dev environment: Run `yarn react-native info` and paste the output here.
- Provide repro steps or a minimal project with the bug reproducible. We cannot help you if we can't repro this locally.

Is this what NX refers to: https://github.com/nrwl/nx-react-native? Have you tried reaching out to them?

**Comment by spuerto-rico** [comment]
I experience the same in my React Native 59.9. anyone solve this already?

**Comment by amandwivedi07** [comment]
Please Help Getting the same issue

**Comment by AbutoJoshua** [comment]
I have the same issue but I initialized my project with expo and not necessarily react native. How can I solve that?
<img width="1234" alt="Screen Shot 2021-08-08 at 10 55 50 AM" src="https://user-images.githubusercontent.com/29531690/128638007-f80aaee6-6d0a-4374-b362-738dfd944999.png">

**Comment by tido64** [comment]
@spuerto-rico: You're using a two year old version of React Native. Recent improvements such as auto-linking should solve your issue without having to messing around with your project file. If you're unable to update, I'd have a look at how to [manually link](https://react-native-async-storage.github.io/async-storage/docs/link) into your project.

@AbutoJoshua: If you're using Expo, please ask in the Expo forum. This thread is probably a good start: https://forums.expo.io/t/expo-40-rn-asyncstorage-nativemodule-asyncstorage-is-null/46757/4

In general, Expo does not really using this library. It is compatible, but the code isn't used. You're using the binaries that come with Expo SDK. If you're having issues with it, please ask in the Expo forum. We cannot help you.

If you're not using Expo, we need your full system information and repro steps to help you. In most cases, it's a setup issue and not a bug in AsyncStorage. Reading the documentation on how this works might help you: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
