### ISSUE TITLE
Unable to get any item with `getItem`

### ISSUE THREAD

**Issue by EricWiener** [react-native-async-storage/async-storage#604]
## Current behavior
Unable to retrieve values with `getItem`

When using the following code:
```
import AsyncStorage from '@react-native-async-storage/async-storage';

  let storageKey = 'persist:root';
  console.log("Getting stored state", storageKey);
  (async () => {
    console.log('about to call async');
    try {
      let res = await AsyncStorage.getItem('persist:root');
      console.log("res", res);
    } catch(e) {
      // error reading value
      console.log(e);
    }
  })();

  console.log("passed here");
  AsyncStorage.getAllKeys((err, keys) => {
    AsyncStorage.multiGet(keys, (error, stores) => {
      stores.map((result, i, store) => {
        console.log({ [store[i][0]]: store[i][1] });
        return true;
      });
    });
  });
```

The top chunk never prints out an error or a result. I just get:
```
Getting stored state persist:root
about to call async
passed here
```

It just continues onto the bottom chunk where it correctly prints values:
```
{"persist:root": ...}
```

## Expected behavior
The item should be returned when using `await AsyncStorage.getItem('persist:root')`

## Repro steps
See above.

## Environment

- **Platforms tested**:
  - [ ] Android
  - [x] iOS
  - [ ] macOS
  - [ ] Windows
- **AsyncStorage version**: ^1.15.4
- **Environment**:
```
System:
    OS: macOS 11.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 24.73 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.3.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 26, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.1 => 0.64.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
- **Logs/Errors that may be relevant**:

**Comment by tido64** [comment]
Not exactly sure what you're trying to do. Have you tried adding `await` here?
```js
  await (async () => {
    console.log('about to call async');
    try {
      let res = await AsyncStorage.getItem('persist:root');
      console.log("res", res);
    } catch(e) {
      // error reading value
      console.log(e);
    }
  })();
```

**Comment by inysojcgcg** [comment]
I'm having the same issue after updating to RN 0.64, both `async-storage` and `react-native-keychain` libraries used to work fine on our app with previous versions of RN and using Hermes engine on Android... now with RN 0.64 both libs have stopped working, I tried disabling the Hermes engine on both platforms but it didn't fix the issue. I also found this https://hermesengine.dev/docs/language-features/#miscellaneous-incompatibilities I wonder if this is related to Hermes implementation of promise; still digging...

**Comment by kylanhurt** [comment]
Yeah mine is also having issues!

**Comment by BeudyZlip** [comment]
same issue :(

**Comment by Thibault-34** [comment]
Same here after upgrading to RN 0.64. It just look like the promise is never resolved. Tested for both Android and IOS with same issue.

**Comment by BeudyZlip** [comment]
I solved my problem
For my part I use react-native-web and I had the 'core-js' library that I was able to delete for my case

**Comment by jpolo** [comment]
For our case, it seems metro `inlineRequires: true` seems to trigger that bug `inlineRequires: false` (in metro.config.js) is OK. Pretty high tradeoff to pay to make this work...

**Comment by Thibault-34** [comment]
Any new on this issue? Someone find a way to use the inline requires with async-storage?

**Comment by tido64** [comment]
If you're having issues with Metro, you should file issues here: https://github.com/facebook/metro/issues/new

**Comment by EricWiener** [comment]
Created issue https://github.com/facebook/metro/issues/682. Could everyone please vote/comment on it to get it some attention

**Comment by raquelmsmith** [comment]
So does this mean that I effectively can't use this library if I'm on RN 0.64? I don't want to change metro config.

**Comment by BunnyTheLifeguard** [comment]
Try something like:
```js
<Button onPress={() => getData('@key').then((value) => console.log(value))} />
```

when calling your function in the component.
