### ISSUE TITLE
 [Error: com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.String] 

### ISSUE THREAD

**Issue by govind1530** [react-native-async-storage/async-storage#605]
react version:-     
         "react": "17.0.1",

          react-native version:-
         "react-native": "0.64.1",

          Libeary Version:-
         "@react-native-async-storage/async-storage": "^1.15.4"

system info

System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 1.33 GB / 7.91 GB
  Binaries:
    Node: 15.8.0 - C:\Program Files\nodejs\node.EXE      
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.5.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    Visual Studio: 16.7.30523.141 (Visual Studio Community 2019)
  Languages:
    Java: 1.8.0_211
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.1 => 0.64.1
    react-native-windows: Not Found
    npmGlobalPackages:
    *react-native*: Not Found

whenever setItem function call 
[Error: com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.String] 
this is error apperieng

**Comment by tido64** [comment]
Please don't delete the template when filing new issues. They're there so we can better help you.

- What version are you using?
- Provide information about your dev environment: Run `yarn react-native info` and paste the output here.
- Provide repro steps or a minimal project with the bug reproducible. We cannot help you if we can't repro this locally.
