### ISSUE TITLE
Why is async-storage deprecated in RN officially?

### ISSUE THREAD

**Issue by heeroduo** [react-native-async-storage/async-storage#606]
## You want to:  

I just wanna know why some functions like async-storage is deprecated in RN.

## Details:

Okay I know I can use it through react-native-community and there are some other ways to use a local storage.

But I just know why Facebook RN team remove some functions from RN when they update RN.

Not only async-storage, but also many functions. They remove it and say 'you can use it through community package'

I think, there are some reasons surely. But they don't explain it. So may I know why they did it? 

I just wanna know it.

**Comment by tido64** [comment]
Please have a look at these threads for answers:
- [Why repository was moved out from react-native-community?](https://github.com/react-native-async-storage/async-storage/discussions/507)
- [What is the difference between this package and @react-native-community/async-storage?](https://github.com/react-native-async-storage/async-storage/discussions/603)

The maintainers of AsyncStorage do not work for Facebook. We are maintaining this in our free time. If you have any questions for Facebook, I would suggest you go and ask them.
