### ISSUE TITLE
Row too big to fit into CursorWindow

### ISSUE THREAD

**Issue by daniel1up** [react-native-async-storage/async-storage#617]
## Current behavior

Hello everyone,

I was using expo and I didn't faced any error while using AsyncStorage but after eject from Expo I have the issue:

```
Possible Unhandled Promise Rejection (id: 3):
Error: Row too big to fit into CursorWindow requiredPos=0, totalRows=1
convertError@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:138878:24
map@[native code]...
```

The error is showing when I call:
`const appData = await AsyncStorage.getItem('@MakinaIMEAppDATA');`

I just need to know why is working on Expo and why not in bare workflow, and what should i do to solve the issue.

Best regards

## Expected behavior

To work fine exactly as in Expo managed.

## Environment

- **Platforms tested**:
  - [ ] Android
- **AsyncStorage version**: ^1.15.5
- **React Native**: ~0.63.4

**Comment by Krizzu** [comment]
Hey,

This error will be thrown if you try to read a data larger than 2MB at once (some sources say 1MB, but that's different per Android device). Expo uses AsyncStorage from React Native directly, so it has the same limitation. Are you use you use the same big data in both cases?

I suggest to either chop down data into smaller chunks (different entries) or use File system to deal with blobs.

**Comment by daniel1up** [comment]
Hello @Krizzu,

Thanks for the reply. Yes, I use the the same big data with Expo managed and Expo eject. I didn't understand why it was happening. But, I have solved this by increasing the size of CursorWindow, I found the solution in another ask by someone else. I am writing the solution below if is needed.

Tried to add these lines inside _onCreate_ method in MainApplication.java:

```
try {
      Field field = CursorWindow.class.getDeclaredField("sCursorWindowSize");
      field.setAccessible(true);
      field.set(null, 100 * 1024 * 1024); //100MB
    } catch (Exception e) {
      if (BuildConfig.DEBUG) {
        e.printStackTrace();
      }
    }
```

Don't forget to import these classes:

```
import android.database.CursorWindow;
import java.lang.reflect.Field;
```

**Comment by kkureli** [comment]
> Hello @krizzu,
> 
> Thanks for the reply. Yes, I use the the same big data with Expo managed and Expo eject. I didn't understand why it was happening. But, I have solved this by increasing the size of CursorWindow, I found the solution in another ask by someone else. I am writing the solution below if is needed.
> 
> Tried to add these lines inside _onCreate_ method in MainApplication.java:
> 
> ```
> try {
>       Field field = CursorWindow.class.getDeclaredField("sCursorWindowSize");
>       field.setAccessible(true);
>       field.set(null, 100 * 1024 * 1024); //100MB
>     } catch (Exception e) {
>       if (BuildConfig.DEBUG) {
>         e.printStackTrace();
>       }
>     }
> ```
> 
> Don't forget to import these classes:
> 
> ```
> import android.database.CursorWindow;
> import java.lang.reflect.Field;
> ```

thanks!
