### ISSUE TITLE
Could not save data: account [Error: [AsyncStorage] Passing null/undefined as value is not supported. If you want to remove value, Use .remove method instead. Passed value: undefined Passed key: account ]

### ISSUE THREAD

**Issue by Surojitsing62** [react-native-async-storage/async-storage#620]
Could not save data: account [Error: [AsyncStorage] Passing null/undefined as value is not supported. If you want to remove value, Use .remove method instead.
Passed value: undefined
Passed key: account
]

**Comment by tido64** [comment]
Please don't delete the template when filing new issues. They're there so we can better help you.

- What version are you using?
- Provide information about your dev environment: Run `yarn react-native info` and paste the output here.
- Provide repro steps or a minimal project with the bug reproducible. We cannot help you if we can't repro this locally.

**Comment by chrisbobbe** [comment]
@Surojitsing62, look closely at the error message. It looks like it's giving you a suggestion: "If you want to remove value, Use .remove method instead." Have you tried that? What happens if you do?
