### ISSUE TITLE
[iOS] setItem from native code

### ISSUE THREAD

**Issue by er1cAk** [react-native-async-storage/async-storage#621]
## You want to:  
I would like to set item in async storage from the native side, how am I able to do it?

## Details:
My [AppDelegate.m](https://gist.github.com/er1cAk/4253cec7f8cd1851b7852e7f7fa17dd0)

**Comment by tido64** [comment]
Please see this discussion: https://github.com/react-native-async-storage/async-storage/discussions/539#discussion-2709632
