### ISSUE TITLE
Async Storage sets to null after some API calls. 

### ISSUE THREAD

**Issue by ibtisamarif831** [react-native-async-storage/async-storage#622]
So, I have stored token in Async storage and on a specific view of React Native App, the API is being called to fetch data on everyt time I navigate to it.
After coming to that specific view after 10 times, the app redirects to login screen and the Async storage is set to null. I have fixed the issue by just calling the API once but I cannot understand the behavior of Async storage.
As you can see above, I am logging async storage on every call but suddenly it gets null. 
PS: API data is not stored in storage, only the token is there.

![Storage null](https://user-images.githubusercontent.com/34893993/123216328-d5d2ee00-d4e2-11eb-97a9-4e072c600fad.png)

- **Platforms tested**:
  - [x] Android
  - [x] iOS

- **AsyncStorage version**:    "@react-native-async-storage/async-storage": "^1.13.2",
- **Environment**:
  
    System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
    Memory: 7.38 GB / 15.88 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    Visual Studio: Not Found
  Languages:
    Java: 16.0.1
    Python: 2.7.9
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
 
It is my first time opening issue, let me know if you need more information.

**Comment by Krizzu** [comment]
Hey @ibtisamarif831 ,

Do you remove the storage at some point in your app? Or maybe you override it? Maybe the data you get back is null and it's being saved to storage, hence disappearance ?

Are you using React Native to write Windows app? Or you develop Android app?

> It is my first time opening issue, let me know if you need more information.

It'd be great if you could stick to the template for the issues

**Comment by ibtisamarif831** [comment]
> Hey @ibtisamarif831 ,
> 
> Do you remove the storage at some point in your app? Or maybe you override it? Maybe the data you get back is null and it's being saved to storage, hence disappearance ?
> 
> Are you using React Native to write Windows app? Or you develop Android app?
> 
> > It is my first time opening issue, let me know if you need more information.
> 
> It'd be great if you could stick to the template for the issues

The only function being called to empty storage is logout one and it is not called on this specific view. The view I am talking about has no link with Async storage. The behavior is really weird

**Comment by Krizzu** [comment]
Screenshot does not tell me much of what's happening in the code. 

Async Storage does not wipe the data without explicitly calling methods to do so. I suspect that the data you try to save is not always what you think it is or maybe you call `logout` in other places you did not expect it to call?

**Comment by ibtisamarif831** [comment]
> Screenshot does not tell me much of what's happening in the code.
> 
> Async Storage does not wipe the data without explicitly calling methods to do so. I suspect that the data you try to save is not always what you think it is or maybe you call `logout` in other places you did not expect it to call?

Man I wish I code publish the code here. The project terms and conditions does not allow me 😒 Maybe we can communicate over a private channel?

**Comment by tido64** [comment]
It would be great if you could create a minimal repro and push that to GitHub.

**Comment by nl-danish** [comment]
I'm having the same issue, how do i make sure that it is not because of the version that my async storage is?
I'm using "@react-native-async-storage/async-storage": "^1.15.14",

The tokens are being set when the user opens the app and login on the login page, but on the later trials we already have a checker on different screens like (Splash, Home), to get the values, but they are being set to null and that's why the user from splash to gets navigated back to the login page.

And, i've also checked that i'm not clearing any cookies or the items on the local storage.
