### ISSUE TITLE
Not Able to clear all Asynchronous storage while app install in IOS

### ISSUE THREAD

**Issue by Bharanitharan06** [react-native-async-storage/async-storage#627]
### Discussed in https://github.com/react-native-async-storage/async-storage/discussions/624

<div type='discussions-op-text'>

<sup>Originally posted by **Bharanitharan06** June 29, 2021</sup>
Hi, Am developing react native Application for **Android** and **IOS** and am using ** AsyncStorage.** for store some data. If user install and login with my app then session will created. if User uninstall and again he install my app I want to delete he's old session and want to create the new session but AsyncStorage. data is not cleared its maintained with old data.

In Android I fixed with **allowBackup** in **AndroidMainfest.xml** file. but **IOS** I don't know how to fix. give some ideas for it.

## Details:
</div>

**Comment by Krizzu** [comment]
Let's continue in the discussion
