### ISSUE TITLE
Clarification on Clearing AsyncStorage and Possible Timing Issue

### ISSUE THREAD

**Issue by rpattcorner** [react-native-async-storage/async-storage#632]
## You want to:  
Clear AsyncStorage to ensure there are no old records for the **currently running expo/rn app**, then write new records that have been read from an earlier backup of the same app.  In short, securely restore a backup without affecting any other apps

## Details:
Working in expo in dual (IOS/Android) environments

* Clearing with AsyncStorage.clear() works as expected
* However the Documentation around clear() suggest that invoking it directly may likely remove records for other Expo or React-Native apps on a user's device.  Is that correct?  If so, I'd certainly want to avoid that outcome.
* The documentation suggests a workaround ... using this:
```
const safeClearAsyncStorage = async () => {
    AsyncStorage.getAllKeys()
        .then(keys => AsyncStorage.multiRemove(keys))
        .then(() => console.log('Safely cleared Async Storage'));
}
```

When I use safeClearAsyncStorage the first record of the restored file is not written correctly or at all.  I see this by writing each record then reading them back:
```
        await safeClearAsyncStorage();
        // await AsyncStorage.clear();
        for (const record of json_records) {
            await AsyncStorage.setItem(record[0], record[1])
            const readback = await AsyncStorage.getItem(record[0])
            console.log(record[1], readback)
        }
```
In the code above the readback variable is always null (in debugger and console) for the first record, which is a stringified object, and from this I conclude that the first record was either not written, or written then somehow cleared.  Other records (some strings, some stringified objects) read back fine.

If I uncomment AsyncStorage.clear() and comment out the safeClear ... all works as expected.

Could there be a timing issue?  Am I misunderstanding something fundamental about how the two styles of Clear work, or the process or chaining of the async calls?

What's the recommended process for a clear and restore of this nature that affects only the app executing the code?

**Comment by Krizzu** [comment]
Hey @rpattcorner 

With this library, Expo uses deprecated version of Async Storage, directly from React Native. What it means, it still uses `NSDocumentDirectory` path, which every app has its own copy (@tido64 please correct me if I'm wrong here).

I think the documentation should be changed, since clearing Async Storage **will not** affect other RN apps data on the system.
