### ISSUE TITLE
Getting AsyncStorage is null

### ISSUE THREAD

**Issue by amandwivedi07** [react-native-async-storage/async-storage#636]
## New feature implementation

> 
![erro1](https://user-images.githubusercontent.com/86069078/126936993-e5fe1e37-f1ef-4527-ad6d-ae2fb1ad55b8.PNG)
![asssync](https://user-images.githubusercontent.com/86069078/126937079-bce0048a-99d5-4250-bd3d-f47ae042579b.PNG)

**Comment by tido64** [comment]
Please see https://github.com/react-native-async-storage/async-storage/issues/572.
