### ISSUE TITLE
Can I use "next" storage with Expo?

### ISSUE THREAD

**Issue by isocra** [react-native-async-storage/async-storage#638]
## You want to:  
Ask if it's possible to use the `next` storage implementation with Expo managed flow to build a React Native app for engineers out in the field.

## Details:
I'm using Expo managed flow and Expo bundles, well makes easily available, this AsyncStorage plugin. I'm also using an Apollo offline cache to manage when the device is offline. But I'm getting reports of `database or disk is full` errors.

So is there anything I can put in the app.json or elsewhere so that AsyncStorage uses the `next storage implementation` and does that fix the space issue? I don't get any errors from iOS devices, only Android

**Comment by Krizzu** [comment]
Hey @isocra 

Unfortunately, no, it's not possible. `database or disk is full` is interesting one - do you see this on different Android devices or just one?
