### ISSUE TITLE
Size limit for each key / value

### ISSUE THREAD

**Issue by Stevemoretz** [react-native-async-storage/async-storage#639]
## You want to:  

Guys I need some help figuring out something about async storage.
on android it has a 6mb limit, I want to know what is its each key value pair limits for each key how big can be the value?

 ## Details:

If it uses a database I think the limit will be the database column max size limit :(

**Comment by Krizzu** [comment]
For Android, SQLite is used, so [SQLite limits are appropriate](https://www.sqlite.org/limits.html). There's also an Android OS limitation on how big the data can be while reading from the DB (CursorWindow limitation) and that's around 2MB. I'm yet to find out why 6MB is a limit on Android, but I from what I've been testing, it can handle more than that (like normal SQLite). Maybe it was related to different storage used back when AsyncStorage used RockDB under the hood? You can increase this limit [by following instructions here](https://react-native-async-storage.github.io/async-storage/docs/advanced/db_size).
