### ISSUE TITLE
ld: library not found for -lRNCAsyncStorage

### ISSUE THREAD

**Issue by codakkk** [react-native-async-storage/async-storage#656]
## Repro steps

Create a new project -> yarn add -> pod install -> yarn ios -> errors.

## Environment

- **Platforms tested**:
  - [ ] Android
  - [x] iOS
  - [ ] macOS
  - [ ] Windows
- **AsyncStorage version**: ^1.15.5
- **Environment**:
System:
    OS: macOS 11.2.3
    CPU: (8) arm64 Apple M1
    Memory: 346.30 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v14.17.3/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
    Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /Users/coda/.rvm/gems/ruby-3.0.1/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 30, 31
      Build Tools: 29.0.2, 31.0.0
      System Images: android-31 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.1 => 0.64.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
- **Logs/Errors that may be relevant**: 
`ld: library not found for -lRNCAsyncStorage
clang: error: linker command failed with exit code 1 (use -v to see invocation)

objc[29699]: Class AMSupportURLConnectionDelegate is implemented in both ?? (0x200310188) and ?? (0x11494c2b8). One of the two will be used. Which one is undefined.
objc[29699]: Class AMSupportURLSession is implemented in both ?? (0x2003101d8) and ?? (0x11494c308). One of the two will be used. Which one is undefined.
** BUILD FAILED **
`

**Comment by tido64** [comment]
I cannot repro this on my Intel MacBook, and I don't have an M1 to test on. Maybe this umbrella issue will help you: https://github.com/facebook/react-native/issues/31941

**Comment by codakkk** [comment]
> I cannot repro this on my Intel MacBook, and I don't have an M1 to test on. Maybe this umbrella issue will help you: [facebook/react-native#31941](https://github.com/facebook/react-native/issues/31941)

I've solved this and I don't know what worked, to be honest. 
I spent a whole day trying to figure out what was the problem and didn't find. 
Next day, it just worked lol

**Comment by tido64** [comment]
Thanks for letting us know. Feel free to update this issue if you figure out what went wrong, for future reference.
