### ISSUE TITLE
Compatibility with React Native 0.65

### ISSUE THREAD

**Issue by mikrobestie** [react-native-async-storage/async-storage#658]
## You want to:  
Hi, yesterday a new version of RN was made publicly available, is the current version 1.15.6 compatible? Because there is a warning when installing 
`warning " > @react-native-async-storage/async-storage@1.15.6" has incorrect peer dependency "react-native@^0.60.6 || ^0.61.5 || ^0.62.2 || ^0.63.2 || ^0.64.0 || 1000.0.0".`

Can I just ignore it for now?

**Comment by tido64** [comment]
You can ignore warning. If your app is working as intended, there's nothing to worry about. I will update the package. Thanks for raising the issue. 😄

**Comment by mikrobestie** [comment]
Many thanks!
