### ISSUE TITLE
Error in jest test after version 1.15.6

### ISSUE THREAD

**Issue by gabriel11447** [react-native-async-storage/async-storage#660]
## Current behavior

When running jest with `async-storage 1.15.6` I get the following error:

![image](https://user-images.githubusercontent.com/37315220/129918803-091ed972-026f-47df-9974-6c4304635a94.png)

## Expected behavior

It's expected this error not to occur, because if I run the test with `async-storage 1.15.5` it works correctly, as shown in the image:

![image](https://user-images.githubusercontent.com/37315220/129919497-57796a61-37c1-4f1a-b810-a10e83c967de.png)

There's some error still happening, but it's expected and there's no connection with this issue.

## Repro steps

- Install  latest version (1.15.6) of `@react-native-async-storage/async-storage`
- Make the jest mock at setupFiles.js accordingly to the documentation
- Run some test that need the mock

## Environment

- **Platforms tested**:
  - [x] Android
  - [ ] iOS
  - [ ] macOS
  - [ ] Windows
- **AsyncStorage version**: 1.15.6
- **Environment**:
```
 System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 6.47 GB / 15.84 GB
  Binaries:
    Node: 14.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\node_modules\yarn\bin\yarn.CMD    
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30
      Build Tools: 29.0.2, 29.0.3, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    Visual Studio: 16.10.31410.357 (Visual Studio Enterprise 2019)
  Languages:
    Java: 11.0.11 - C:\Program Files\OpenJDK\openjdk-11.0.11_9\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by tido64** [comment]
Thanks for reporting this. Can you please check if this solves the issue: https://github.com/react-native-async-storage/async-storage/pull/661

**Comment by gabriel11447** [comment]
Yes, this solves the problem.
