### ISSUE TITLE
Jest transform issue after upgrade to the latest version

### ISSUE THREAD

**Issue by moonjava2005** [react-native-async-storage/async-storage#664]
After I upgrade to the latest React-Native (version 0.65.0) and AsyncStorage to 1.15.5, I got this issue on unit test

Do you guys know how to fix this?

`import mergeOptions from 'merge-options';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
       6 | const { window } = jsdom
       7 |
    >  8 | import mockAsyncStorage from '@react-native-async-storage/async-storage/jest/async-storage-mock'
         | ^
       9 |
      10 | jest.mock('@react-native-async-storage/async-storage', () => mockAsyncStorage)
      11 |

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1479:14)
      at Object.<anonymous> (setup-jest.js:8:1)`

**Comment by tido64** [comment]
Can you check if the fix in #660 solves your issue?
