### ISSUE TITLE
remove usages of `jcenter()`

### ISSUE THREAD

**Issue by dlwo159** [react-native-async-storage/async-storage#666]
WARNING:: Please remove usages of `jcenter()` Maven repository from your build scripts and migrate your build to other Maven repositories.
This repository is deprecated and it will be shut down in the future.
See http://developer.android.com/r/tools/jcenter-end-of-service for more information.
Currently detected usages in: project ':react-native-async-storage_async-storage'

**Comment by tido64** [comment]
Duplicate of #610.
