### ISSUE TITLE
Lost asyncstorage data when use migration Expo for expo SDK 41 with android 9 Xiaomi

### ISSUE THREAD

**Issue by agoqui** [react-native-async-storage/async-storage#667]
## Current behavior

 When you migrate an eject project to expo SDK 40 ou SDK 41 with an android 9 (Xiaomi), you lost the content of data because the sqlite structure contain 3 files: 
 - RKStorage-scoped-experience-myapp
 - RKStorage-scoped-experience-myapp-wal
 - RKStorage-scoped-experience-myapp-shm
 
And when the AsyncStorageExpoMigration is running, the most recently file is renamed but we lost the -wal and -shm.
All the aysncStorage datas are lost 😭

## Expected behavior

Have you an idea to resolve this problem, please? 🙏 

## Environment

- **Platforms tested**:
  - [ ] Android 9 , Xiaomi
 
- **AsyncStorage version**:  1.15.6
- **Expo version**: Expo SDK40 or SDK41
- **Environment**:
  
`
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 905.04 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.9.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.14 - ~/dev/mob/rn-kizeoforms/node_modules/.bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ~0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
`

**Comment by tido64** [comment]
This is unrelated to AsyncStorage. I think you need to file your issue here: https://github.com/expo/expo.

**Comment by ClemArt** [comment]
@tido64 There seems o be a misunderstanding here, it's not about the version of the expo SDK, but about the migration that is included in this repo (class AsyncStorageExpoMigration.java) that is supposed to migrate the database files from the expo naming to something more maintainable.

On a Xiaomi with android 9, the database is split in a main file, a -wal file and a -shm file. The migration does not take into account this kind of setup, and thus crashed, resulting in a loss of data.

Is there any way we can look into this so that the migration can cover databases created with both -journal and -wal settings ?

Many thanks !

**Comment by agoqui** [comment]
@tido64 , your AsyncStorageExpoMigration  is perfect when the database is a file and a -journal on android, and perfect for IOS.
But if the database is split on 3 files (RKStorage-scoped-experience-..., RKStorage-scoped-experience-...-wal and RKStorage-scoped-experience-...-shm),  you rename the most recently file and delete the others. But the -wal file is very important to rename too.

Maybe have you an idea to resolve that with an android configuration? 

Many thanks.

**Comment by tido64** [comment]
Sorry, is this for migrating from Expo 40 to Expo 41? Or from Expo to bare workflow?

@brentvatne, @EvanBacon: Is this something for you?

**Comment by agoqui** [comment]
Sorry, it's bare workflow and i use Expo 37  and i try to migrate  to expo 40 and newer. The asyncStorage expo migration it's ok for many Android but not Android using wal files on SQLite databases.

**Comment by EvanBacon** [comment]
@agoqui, I don't have access to a Xiaomi device -- would you be willing to open a PR to implement the proposed changes?

**Comment by agoqui** [comment]
@EvanBacon , tomorrow i try to fix it and i purpose a PR. Thanks for your answers @tido64 and @EvanBacon

**Comment by EvanBacon** [comment]
@agoqui if this works as advertised, then it looks good to me!

**Comment by Krizzu** [comment]
@agoqui Hey, thanks for contributing! I've checked the code and at first glance it look fine. One thing to note is that the WAL mode is enabled by default on Android 9 and up, so I'll still keep the journal-file-skip code.

Another approach to migration would be performing a `wal checkpoint` - an operation that forces write from WAL to DB file. We already do that on AsyncStorage migration to Next storage on Android
[Related code here](https://github.com/react-native-async-storage/async-storage/blob/master/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncLocalStorageUtil.java#L145-L178)
