### ISSUE TITLE
Flipper plugin

### ISSUE THREAD

**Issue by lbaldy** [react-native-async-storage/async-storage#669]
I wrote a plugin for Async Storage for Flipper because I couldn't find a nice plugin providing basic CRUD operations.

The plugin is available here: https://github.com/lbaldy/flipper-plugin-async-storage-advanced

And I thought it could be worth for me and AsyncStorage to mention this in the readme.

I wasn't sure if I should open a PR with a README update or evem if this GH issue is valid, so please let me know if by any chance I missed something and I am violating the contributing guidelines.

**Comment by tido64** [comment]
Sorry for the late reply.

@Krizzu how do you feel about adding a section in the README with tools that might be useful to folks? There are probably other Flipper plugins out there as well that we could add here.

**Comment by Krizzu** [comment]
Hey,
@lbaldy sorry for late response - this look great! I'd be more than happy to have a section in README/website to include community packages

**Comment by lbaldy** [comment]
Great, I will open a MR today or over the weekend.
