### ISSUE TITLE
[Windows] AsyncStorage hangs now - not before

### ISSUE THREAD

**Issue by tero-paananen** [react-native-async-storage/async-storage#671]
`AsyncStorage` hangs quite easily when building and running with latest **Visual Studio 16.11.x**. Happens in debug and release builds.

My issue about problems with latest Visual Studio https://github.com/microsoft/react-native-windows/issues/8581

I have to investigate that more. `RNCAsyncStorage multiSet` does not response to js await call it get stuck.

Does anyone else noted something?

Problem started now - maybe after some Windows update or something. Same src code that before, does not work anymore.

## Env

Visual Studio 16.11.2
"@react-native-async-storage/async-storage": "^1.15.7",
"react-native-windows": "0.62.22",
"react": "^16.14.0",

**Comment by tero-paananen** [comment]
I unistalled VS 16.10 and installed 16.9 and i still has this problem - should not. I have investigated this more and try to clean my env maybe better.

**Comment by tero-paananen** [comment]
There is no error - i would say so. We store lot of data into AsyncStorage and it took time. I will re-open issue if i noted something new.

**Comment by tero-paananen** [comment]
I had error with `react-native-storage` where i had to add some additional `await` strings to wait asynchronous calls into` storage.js`  `_saveToMap(params)` and there 

```
await this.setItem('map_' + currentIndex, data);
await this.setItem('map', JSON.stringify(m));
```

Change is mandatory for some reason now. No idea why this was not needed before.

**Comment by tero-paananen** [comment]
I am using `AsyncStorage` with `react-native-storage` 
```
new Storage({
  storageBackend: AsyncStorage,
  defaultExpires: null,
  size: 1000 * 10,
});
```

**Comment by tero-paananen** [comment]
Maybe i open this issue, this is good to know....

**Comment by tido64** [comment]
I'm going to close this as it sounds like this is an issue with `react-native-storage` and not AsyncStorage. If you feel this is wrong, feel free to reopen with more details on how to repro this using AsyncStorage only.
