### ISSUE TITLE
Can't upgrade to RN 0.66

### ISSUE THREAD

**Issue by rafwell** [react-native-async-storage/async-storage#682]
## Current behavior

Can't upgrade to react native 0.66

## Expected behavior

Upgrade to react native 0.66

## Repro steps

Try to install this package with RN 0.66

## Environment

- **AsyncStorage version**: 1.15.8
- **Expo version**: Bare project
- **Environment**:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react-native@0.66.0
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.66.0" from the root project
npm ERR!   peer react-native@">=0.65.0-rc.0 || 0.0.0-*" from @react-native-community/cli@6.0.0
npm ERR!   node_modules/@react-native-community/cli
npm ERR!     @react-native-community/cli@"^6.0.0" from react-native@0.66.0
npm ERR!   12 more (@react-navigation/drawer, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.0.0-0 || ^0.60.6 || ^0.61.5 || ^0.62.2 || ^0.63.2 || ^0.64.0 || ^0.65.0 || 1000.0.0" from @react-native-async-storage/async-storage@1.15.8
npm ERR! node_modules/@react-native-async-storage/async-storage
npm ERR!   @react-native-async-storage/async-storage@"^1.15.8" from the root project
```
- **Logs/Errors that may be relevant**:

**Comment by yusufsaylam** [comment]
> @krizzu `npm i @react-native-community/async-storage@latest ` doesn't seem to work
> 
> ```
> ╰─$ npm i @react-native-community/async-storage@latest          
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: @onin/app@0.0.1
> npm ERR! Found: react@17.0.2
> npm ERR! node_modules/react
> npm ERR!   react@"17.0.2" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer react@"^16.8" from @react-native-community/async-storage@1.12.1
> npm ERR! node_modules/@react-native-community/async-storage
> npm ERR!   @react-native-community/async-storage@"1.12.1" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR! 
> ```
> 
> Edit my bad seems to work with
> 
> ```
>  npm i @react-native-async-storage/async-storage 
> ```

This command did not work for me.

React version : 18.1.0
react-native version : 0.68.2

**Comment by shtefanilie** [comment]
> > @krizzu `npm i @react-native-community/async-storage@latest ` doesn't seem to work
> > ```
> > ╰─$ npm i @react-native-community/async-storage@latest          
> > npm ERR! code ERESOLVE
> > npm ERR! ERESOLVE unable to resolve dependency tree
> > npm ERR! 
> > npm ERR! While resolving: @onin/app@0.0.1
> > npm ERR! Found: react@17.0.2
> > npm ERR! node_modules/react
> > npm ERR!   react@"17.0.2" from the root project
> > npm ERR! 
> > npm ERR! Could not resolve dependency:
> > npm ERR! peer react@"^16.8" from @react-native-community/async-storage@1.12.1
> > npm ERR! node_modules/@react-native-community/async-storage
> > npm ERR!   @react-native-community/async-storage@"1.12.1" from the root project
> > npm ERR! 
> > npm ERR! Fix the upstream dependency conflict, or retry
> > npm ERR! this command with --force, or --legacy-peer-deps
> > npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> > npm ERR! 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Edit my bad seems to work with
> > ```
> >  npm i @react-native-async-storage/async-storage 
> > ```
> 
> This command did not work for me.
> 
> React version : 18.1.0 react-native version : 0.68.2

Did someone manage to fix this? I'm currently experiencing this also on 
`react: 17.0.2`
`"@react-native-async-storage/async-storage": "1.15.8",`

**Comment by coreybruyere** [comment]
@shtefanilie Did you ever resolve this? Running into the same issue on 

react: 17.0.2
"@react-native-async-storage/async-storage": "1.19.3",
