### ISSUE TITLE
Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.

### ISSUE THREAD

**Issue by ghost** [react-native-async-storage/async-storage#689]
## Current behavior
My app was running smoothly but suddenly it's not opening. It's shown me some errors.
`Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.`
`Run `react-native link @react-native-async-storage/async-storage` in the project root.`
`Rebuild and restart the app.`
etc
I installed the AsyncStorage via npm `i @react-native-async-storage/async-storage --save` this command. That time it was working fine but now it's not working. I mean my app is not opening. 
**I have read the documentation**
In my package.json file my react-native is 0.66 so I don't need to use the link command. If I use the link command it's show me some other error like **make sure your package has been installed something like that**. Then if I use this command `npm install @react-native-async-storage/async-storage --save` then the link command it's say linked successfully but it removes my other library. Then if I install my other library it shows me some other errors. 

## Environment

- **Platforms tested**:
  - [ ] Android

**Comment by tido64** [comment]
Please don't delete the template when filing new issues. They're there so we can better help you. You have provided no code snippets or any error messages, making it impossible for us to know what's wrong. That said, none of what you're describing sounds like an issue with AsyncStorage itself.
