### ISSUE TITLE
NativeModule: AsyncStorage is null, with @RNC/AsyncStorage

### ISSUE THREAD

**Issue by vibincp** [react-native-async-storage/async-storage#696]
### What happened?

<img width="1680" alt="Screen Shot 2021-10-22 at 2 59 30 pm" src="https://user-images.githubusercontent.com/65582764/138430927-3bc54290-8050-433c-8e50-389051b62221.png">

### Version

1.15.9

### What platforms are you seeing this issue on?

- [ ] Android
- [X] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
System:
    OS: macOS 11.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 728.45 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.0 - /usr/local/bin/node
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: 2021.10.11.00 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
  IDEs:
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^4.2.4 => 4.2.4 
    react: 16.8.3 => 16.8.3 
    react-native: 0.60.0 => 0.60.0 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

### Steps to Reproduce

1.Build Success
2.Issue is generated while running in simulator
Dear @Krizzu  im stuck with this from 5 days

**Comment by shanky-gupta** [comment]
I am facing same problem in android. Is there any solution for this.

`/ReactNativeJS: Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.`

**Comment by james-nguyen-goldenowl** [comment]
I am facing same problem in expo when run ios simulator. I need solution. Can you help me?

**Comment by pagreczner** [comment]
I get this issue when I run an `eas build` of an app that is running through expo managed workflow. When I run via the expo go app on a device and also on a simulator, there are no issues. It's only once I create an image via eas build.

I'd rather not have to eject, but is that the only option here for using this library and working with react native through expo?

**Comment by pagreczner** [comment]
> I get this issue when I run an `eas build` of an app that is running through expo managed workflow. When I run via the expo go app on a device and also on a simulator, there are no issues. It's only once I create an image via eas build.
> 
> I'd rather not have to eject, but is that the only option here for using this library and working with react native through expo?

Update: Was able to change the expo `metro.config.js` to include
```
defaultConfig.resolver.assetExts.push('expo.js');
defaultConfig.resolver.sourceExts.push('expo.js');
```

Did not need to eject. And the build then worked fine in both simulator and via TestFlight.

**Comment by james-nguyen-goldenowl** [comment]
Ok. Thanks. Everything is working fine.

Vào 19:40, Th 5, 11 thg 11, 2021 Peter Greczner ***@***.***>
đã viết:

**Comment by adeyeanqar** [comment]
Hi @pagreczner . I don't know anything about metro.config.js so I read on how to customize it, Done that now - created the file in my root directory. I tried the above, but it didn't work. What is expo.js? Should I create that file?

> > I get this issue when I run an `eas build` of an app that is running through expo managed workflow. When I run via the expo go app on a device and also on a simulator, there are no issues. It's only once I create an image via eas build.
> > I'd rather not have to eject, but is that the only option here for using this library and working with react native through expo?
> 
> Update: Was able to change the expo `metro.config.js` to include
> 
> ```
> defaultConfig.resolver.assetExts.push('expo.js');
> defaultConfig.resolver.sourceExts.push('expo.js');
> ```
> 
> Did not need to eject. And the build then worked fine in both simulator and via TestFlight.

**Comment by miguelitolaparra** [comment]
Hello

Have you been able to fix this iOS bug?

I have installed together with React-Native 0.59.10. , "yarn add @ react-native-community / async-storage" and followed the manual link documentation, but I can't get it to work.
When I try to install Pod, (pod install), I also get the error:

**`[!] Unable to find a specification for `React-Core` depended upon by` RNCAsyncStorage``**

```
You have either:
  * out-of-date source repos which you can update with `pod repo update` or with` pod install --repo-update`.
  * mistyped the name or version.
  * not added the source repo that hosts the Podspec to your Podfile.

```
They are several days looking for a solution online, and I can not find anyone who has corrected this problem.

Can you give any advice?
Thanks

**Comment by Krizzu** [comment]
ah, that might be due the dependency change for later RN version? As far as I remember, it used to be `React` and it changed to `React-Core`. 

Could you try to confirm if it would work, if you change it `React` inside your `node_modules/@react-native-async-storage` ?

**Comment by miguelitolaparra** [comment]
> ah, ¿eso podría deberse al cambio de dependencia para la versión posterior de RN? Por lo que recuerdo, solía ser `React`y cambió a `React-Core`.
> 
> ¿Podría intentar confirmar si funcionaría, si lo cambia `React`dentro de su `node_modules/@react-native-async-storage`?
Thanks. @Krizzu . The problem is that I don't know which file I need to modify, could you tell me which file we need to modify?
Thanks

**Comment by miguelitolaparra** [comment]
Thanks. @MMM. The problem is that I don't know which file I need to modify, could you tell me which file we need to modify?
Thanks

**Comment by Krizzu** [comment]
`node_modules/@react-native-async-storage/RNCAsyncStorage.podspec`

```diff
- s.dependency 'React-Core'
+ s.dependency 'React'
```

**Comment by miguelitolaparra** [comment]
I made the change you suggested to me, @Krizzu  but I get an error that does not allow the App to run:


```
'React / RCTBridgeModule.h' file not found

/Volumes/MIguelApps/REACT-NATIVE/MANDALA/project-15-nov Diciembre-2021/misDibujitos/node_modules/@react-native-async-storage/async-storage/ios/RNCAsyncStorage.h:10:9: 'React / RCTBridgeModule .h 'file not found
```

I have tried several things before coming back to you, but nothing works.

When install. `yarn add @ react-native-async-storage / async-storage`, I got another error for stop Xcode and make changes:

Error I show in the screenshot. Then make the suggested changes to the RCTCxxBridge.mm file:

**Change of :**

```
- (NSArray <RCTModuleData *> *) _ initializeModules: (NSArray <id <BridgeModule>> *) modules
                               withDispatchGroup: (dispatch_group_t) dispatchGroup
                                lazilyDiscovered: (BOOL) lazilyDiscovered
```

**To the next:**

```

- (NSArray <RCTModuleData *> *) _ initializeModules: (NSArray <Class> *) modules
                               withDispatchGroup: (dispatch_group_t) dispatchGroup
                                lazilyDiscovered: (BOOL) lazilyDiscovered
```

But I am getting the error that the screenshot shows.
For this I found several solutions but none worked

I do not know what I can do

**Comment by Krizzu** [comment]
I think you either upgrade to 60+ RN version or downgrade AsyncStorage (probably to v1.13.2). There are constant changes happening to RN, so staying up to date is always encouraged.

**Comment by miguelitolaparra** [comment]
> Creo que puede actualizar a la versión 60+ RN o degradar AsyncStorage (probablemente a v1.13.2). Hay cambios constantes en RN, por lo que siempre se recomienda mantenerse actualizado.
Thanks. I am working with a template that RN already had. 0.59.10. I don't know what the consequences of updating RN will be. Still, I will do all the tests to correct this.

I will communicate the achievements here when I finish
Thanks

**Comment by miguelitolaparra** [comment]
> Creo que puede actualizar a la versión 60+ RN o degradar AsyncStorage (probablemente a v1.13.2). Hay cambios constantes en RN, por lo que siempre se recomienda mantenerse actualizado.


Thanks. I am working with a template that RN already had. 0.59.10. I don't know what the consequences of updating RN will be. Still, I will do all the tests to correct this.

I will communicate the achievements here when I finish
Thanks

**Comment by Krizzu** [comment]
You can use this tool, because there's much more than just bumping version in `package.json`

https://react-native-community.github.io/upgrade-helper/

**Comment by miguelitolaparra** [comment]
Very interesting.
I will take some time to study this tool, it is really interesting.
Now I see how much I still have to learn in the React Native world.
Thanks
