### ISSUE TITLE
redundant getItem callback calls.

### ISSUE THREAD

**Issue by mojtabaasadi** [react-native-async-storage/async-storage#700]
### What happened?

Im not sure this happens because of `react-native-async-storage` or not but having latest version of `react-native=0.66.1` and `react-navigation=6.2.5` getItem success callback get called whenever some events get emitted in  app like navigation routes change in react navigation

### Version

1.15.9

### What platforms are you seeing this issue on?

- [X] Android
- [X] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
Node: 14.18.1 - ~\AppData\Local\Temp\yarn--1635683227669-0.5004923376339399\node.CMD         Yarn: 1.22.5 - ~\AppData\Local\Temp\yarn--1635683227669-0.5004923376339399\yarn.CMD      
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20210110.135312.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
  SDKs:
    Android SDK:      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_282
    Python: 3.9.6
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:    *react-native*: Not Found
```

### Steps to Reproduce

having react-native=0.66.1 and some event listenings like react-navigation route change

**Comment by tido64** [comment]
Do you have a minimal repro of this? It sounds like you're fetching AsyncStorage in a hook that gets triggered when you navigate. AsyncStorage itself throws away the callback once it's been called, so this doesn't make any sense.
