### ISSUE TITLE
iOS:-  Error: Failed to create storage directory.Error Domain=NSCocoaErrorDomain Code=512 

### ISSUE THREAD

**Issue by ahmed-projects** [react-native-async-storage/async-storage#701]
### What happened?

**Facing problem only in iOS, not in android.** 

Failed to create storage directory.Error Domain=NSCocoaErrorDomain Code=512 "The file “%40amdig%2Fcenflex-puraskar” couldn’t be saved in the folder “ExponentExperienceData”." UserInfo={NSFilePath=/var/mobile/Containers/Data/Application/B8974F4F-B2F1-432C-AEEA-29C3127761C5/Documents/ExponentExperienceData/%40amdig%2Fcenflex-puraskar, NSUnderlyingError=0x281ea1dd0 {Error Domain=NSPOSIXErrorDomain Code=20 "Not a directory"}}

### Version

tried with these versions 1.15.9 , 1.15.5, 1.13.2

### What platforms are you seeing this issue on?

- [ ] Android
- [X] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz
    Memory: 1.09 GB / 7.74 GB
  Binaries:
    Node: 14.17.4 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.64.2 => 0.64.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

import AsyncStorage from "@react-native-async-storage/async-storage";

useEffect(async () => {
    try {
      console.log('test started')
      await AsyncStorage.setItem("testKey", 'testValue');

    } catch (e) {
      console.log(e, 'setItem test error ')
    }

  }, [])

**Comment by ahmed-projects** [comment]
@tido64    **I tried with below two options** 

"expo": {
    "name": "Cenflex Puraskar",
    "slug": "cenflex-puraskar",
    "version": "4.1.2",
    "orientation": "portrait",
    "icon": "./assets/appIcon.png",
    "splash": {
      "image": "./assets/appIcon.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "description": "",
    "ios": {
    "icon": "./assets/appIcon.png",
    "bundleIdentifier": "com.domain.Cenflex",
    "buildNumber": "4.1.2"
    },
    },


"expo": {
    "name": "Cenflex Puraskar",
    "slug": "cenflex-puraskar",
    "version": "4.1.2",
    "orientation": "portrait",
    "icon": "./assets/appIcon.png",
    "splash": {
      "image": "./assets/appIcon.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "description": "",
    "ios": {
    "icon": "./assets/appIcon.png",
    "bundleIdentifier": "com.domain.cenflex-puraskar",
    "buildNumber": "4.1.2"
    },
    },

**Comment by tido64** [comment]
Sorry, I don't have much experience with Expo, but it doesn't look like your bundle identifier is being set. The error message you have there implies that your identifier is something like `@amdig/cenflex-puraskar`, which is not a valid identifier.

**Comment by ahmed-projects** [comment]
@tido64 earlier with same configuration there was no issue. After updating async-storage lib and expo I'm facing this error

**Comment by tido64** [comment]
I think you need to figure out where `@amdig/cenflex-puraskar` is coming from. Maybe @EvanBacon can help you.

**Comment by ahmed-projects** [comment]
@EvanBacon  any help?

**Comment by ahmed-projects** [comment]
I tried with many things but when I **### reinstalled the Expo Go app in iPhone** and bug isn't there.
