### ISSUE TITLE
EXPO Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.

### ISSUE THREAD

**Issue by adeyeanqar** [react-native-async-storage/async-storage#709]
### What happened?

Hi, I use expo to build my app, I just recently upgrade from SDK 38 to SDK 41, I looked at the depreciations.. But I keep getting this error

`Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.

To fix this issue try these steps:

• Run react-native link @react-native-community/async-storage in the project root.

• Rebuild and restart the app.

• Run the packager with --reset-cache flag.

• If you are using CocoaPods on iOS, run pod install in the ios directory and then rebuild and re-run the app.

• If this happens while testing with Jest, check out docs how to integrate AsyncStorage with it: https://react-native-community.github.io/async-storage/docs/advanced/jest

If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-async-storage/issues

Invariant Violation: "main" has not been registered. This can happen if:

Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
A module failed to load due to an error and AppRegistry.registerComponent wasn't called.`
I tried customizing metro.config.js (I created this file as I didn't have it before and tried to tweak it with response I say), But I noticed that my expo actually came with babel.config.js (I don't know if that's a problem). I have tried all the tweak I saw and its not working still. Please I need urgent help as I have a deadline.

### Version

1.13.0

### What platforms are you seeing this issue on?

- [ ] Android
- [X] iOS
- [ ] macOS
- [X] Windows
- [ ] web

### System Information

```true
System:
    OS: Windows 10 10.0.16299
    CPU: (4) x64 Intel(R) Core(TM) i3-5010U CPU @ 2.10GHz
    Memory: 1.96 GB / 7.88 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.1.3 - ~\AppData\Roaming\npm\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    Visual Studio: 16.6.30204.135 (Visual Studio Community 2019)
  Languages:
    Java: 15.0.1 - C:\Program Files\Java\jdk-15.0.1\bin\javac.EXE
    Python: 3.10.0 - C:\Python310\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: ^0.63.4 => 0.63.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

1. Upgrade EXPO from 39 to 41
2.

**Comment by haveamission** [comment]
Also seeing this issue upon upgrading to Expo SDK 43.

Did you find a solution to this?

**Comment by adeyeanqar** [comment]
Yes I found a solution, The problem was with `@react-native-community/async-storage` . So I just deleted the "async-storage" folder from node_modules. And it worked. Although you can use Expo SecureStore if you still have the problem

**Comment by codaDevDan** [comment]
We use aws-amplify for our auth,  which depends on @react-native-community/async-storage. Is there any way to use the library in a managed project? We'd really prefer not to eject or have to change auth providers.

**Comment by milon27** [comment]
- delete everything from node_modules
- delete the package-lock.json file
- clear all data/cache from expo go app.
- use  "@react-native-async-storage/async-storage": "1.15.0" this exact version
- npm install agin.
- npm run android

i solved the issue this way. you can also try

**Comment by MichaelGorski** [comment]
I had the same issue Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null. This happened after installing aws-amplify.

I'm using Expo SDK 44, EAS Build.

I tried a lot of things like written on the page, clean cache, pod install, remove node_modules, changing the versions etc. but didn't resolve the problem.
This one was also my approach: https://react-native-async-storage.github.io/async-storage/docs/help/troubleshooting/#ios-cocoapods-issues 

**For people wondering how I solved it,**
just make a new build and all my issues were gone! It saves a lot of time.

**Comment by kurtisdevv** [comment]
Hi, I've been having the same issue but managed to sort it today. Hopefully helps you guys out if it's similar to mine:

  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.3 => 0.67.3
    react-native-windows: Not Found

First installed the Azure Auth using the below:

https://github.com/vmurin/react-native-azure-auth#readme
'yarn add react-native-azure-auth'

Then upgraded my react-native-async-storage to 1.16.1.

https://react-native-async-storage.github.io/async-storage/docs/install
'yarn add @react-native-async-storage/async-storage'

Ran 'npx react-native start --reset-cache' after installing and it now works.

Make sure you don't have the community version of async installed also.
