### ISSUE TITLE
iOS: Failed to create storage directory.Error

### ISSUE THREAD

**Issue by Ashutosh-Tiwari** [react-native-async-storage/async-storage#722]
### What happened?

Getting an error as soon as I integrated the plugin into my expo SDK 43 project.
The log shows something like this:

`[Error: Failed to create storage directory.Error Domain=NSCocoaErrorDomain Code=512 "The file “%40ashutosh-ats%2FPitchAI_Mobile” couldn’t be saved in the folder “ExponentExperienceData”." UserInfo={NSFilePath=/Users/dsk-1019/Library/Developer/CoreSimulator/Devices/C2EE8CE1-6CD9-4E00-AB4F-8C0D8F50C423/data/Containers/Data/Application/5B916692-FD88-4641-9729-61E9AFB6BAE4/Documents/ExponentExperienceData/%40ashutosh-ats%2FPitchAI_Mobile, NSUnderlyingError=0x600000ce5590 {Error Domain=NSPOSIXErrorDomain Code=20 "Not a directory"}}]`

For the first time when I save something like a token in the AsyncStorage, it saves and also prints when doing getItem but all of a sudden on the next subsequent requests of getItem I don't get anything, and when I try to save using setItem then the above error is thrown.

In used expo install for installing the plugin.

### Version

~1.15.0

### What platforms are you seeing this issue on?

- [ ] Android
- [X] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
System:
    OS: macOS 11.5.2
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 544.69 MB / 20.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 29.0.2, 29.0.3, 30.0.0, 30.0.2
      System Images: android-25 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.3 => 0.64.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

1. Create a typescript project with expo SDK 43.0.0
2. Install the plugin using expo install
3. Import to the place of use and try doing setItem and getItem.

[Note: Not sure why but in a sample app having SDK 43.0.2, everything seems to work. But in my project with SDK 43.0.0, it is pretty much messed up.]

**Comment by adiakritos** [comment]
@Ashutosh-Tiwari [Ashutosh-Tiwari](https://github.com/Ashutosh-Tiwari) did you figure out this error?

**Comment by brennanleez-coder** [comment]
@adiakritos @Ashutosh-Tiwari Hi guys, am now facing the same error but i encountered this error while reinitialising my whole expo project. Have yall found a fix? If not, we could definitely hop onto a call and figure this out together

**Comment by georgeka98** [comment]
I am also facing the same issue. Did anyone manage to fix it? The only difference I have with the OP is that I am using an M2 Mac.

**Comment by jordanful** [comment]
Uninstalling and reinstalling Expo Go on the Simulator 'fixed' it for me.

**Comment by kemalcelikturk** [comment]
the basic way,delete Expo App on ios Simulator  or android Emulator.

and start with npx expo start and choose what you need,

expo will reinstalled. and probably your problem ll be solved.
