### ISSUE TITLE
Add `excludeKeys` option to `AsyncStorage.clear()`

### ISSUE THREAD

**Issue by alea12** [react-native-async-storage/async-storage#725]
### Proposal

There are cases where you'd like to clear everything from AsyncStorage, but except for some keys.
In such cases, I write something like this:

```ts
// example: Logout flow. I want to clear everything but keep the "LAST_LOGIN_METHOD"
const lastLoginMethod = await AsyncStorage.getItem("LAST_LOGIN_METHOD")
await AsyncStorage.clear()
await AsyncStorage.setItem("LAST_LOGIN_METHOD", lastLoginMethod)
```

It'd be straightforward to tell the method to exclude some keys selectively.

```ts
await AsyncStorage.clear(excludeKeys: ["LAST_LOGIN_METHOD"])
```

### Implementation Details

I believe this is possible by adding some code to [`src/AsyncStorage.js`](https://github.com/react-native-async-storage/async-storage/blob/b2fd6308056bde5b804dcad665ac9acadffbce56/src/AsyncStorage.js), using already implemented methods: `getAllKeys` & `multiRemove`. I'd be happy to send a PR if this seems to make sense 🙂

**Comment by Maker-Mark** [comment]
This could be cool. But you could do that now by multiRemove. If you just want all the keys but [x,y], you could get all the keys, and just remove [x,y] from the set, and then do multiRemove on the rest of those keys.

**Comment by krizzu** [comment]
Hey @alea12,
Like you already mentioned (and @Maker-Mark hinted), you can use a combination of `getAllKeys` and `multiRemove` to achieve that goal.
I'd omit adding a method to cover the case that can be done with already available api.

**Comment by krizzu** [comment]
Closing, as this can be achieved by provided API.

**Comment by alea12** [comment]
I'm sorry for the late reply! Noted with thanks :)

**Comment by Ridwan226** [comment]
I think it can be done

const keys = await AsyncStorage.getAllKeys();
const valuesToRemove = ['language', 'country'];
const filteredArray = keys.filter(value => !valuesToRemove.includes(value));

then send it to

AsyncStorage.multiRemove(filteredArray)
