### ISSUE TITLE
Syntax Error in Docs

### ISSUE THREAD

**Issue by b-a-merritt** [react-native-async-storage/async-storage#729]
https://react-native-async-storage.github.io/async-storage/docs/usage/

Reading object value
``` Javascript
const getData = async () => {
  try {
    const jsonValue = await AsyncStorage.getItem('@storage_Key')
    return jsonValue != null ? JSON.parse(jsonValue) : null;
  } catch(e) {
    // error reading value
  }
}
```

It should say `return jsonValue !== null ? JSON.parse(jsonValue) : null;` not `!=`

**Comment by tido64** [comment]
Can you explain why this is a "syntax error"? To my knowledge, `!=` is perfectly valid JavaScript.

**Comment by b-a-merritt** [comment]
Hey,
I’m sorry. I was really tired from working all day.
I don’t know what I was thinking besides having a brain-dump.
It’s valid
