### ISSUE TITLE
4 moderate severity vulnerabilities

### ISSUE THREAD

**Issue by vinay-khatri** [react-native-async-storage/async-storage#730]
### What happened?

NPM audit found found 4 moderate severity vulnerabilities.
All vulnerabilities are inside ansi-regex package that async storage uses.
Please fix these as `npm audit fix` failed to fix these.

### Version

1.15.14

### What platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx
    Memory: 2.77 GB / 10.66 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.18.2 - /usr/bin/node
    Yarn: Not Found
    npm: 6.14.15 - /usr/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 30, 31
      Build Tools: 29.0.2, 30.0.2, 31.0.0
      System Images: android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.3 => 0.66.3 
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

`npm i @react-native-async-storage/async-storage`

`npm audit`

**Comment by tido64** [comment]
AsyncStorage doesn't use `ansi-regex`. You can find out who pulled in the package by running `npm ls ansi-regex`.
