### ISSUE TITLE
Does clear() really remove content from other apps (as mentioned in the docs)?

### ISSUE THREAD

**Issue by guiccbr** [react-native-async-storage/async-storage#735]
### What happened?

I need to clear all of the data from my react-native application that was persisted with the AsyncStorage. By reading the docs it seems that `clear()` is unsafe and should not be used because it affects other clients.

https://react-native-async-storage.github.io/async-storage/docs/api#clear

> Removes whole AsyncStorage data, for all clients, libraries, etc. You probably want to use removeItem or multiRemove to clear only your App's keys.

Is that really true? If so, isn't that a huge issue? Basically any React-Native app that calls clear() will wipe the AsyncStorage of other apps without notice.

I haven't found any other issue talking about that, so either I'm missing something or just the docs are outdated/unclear right?

### Version

1.15.15

### What platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
N/A
```

### Steps to Reproduce

N/A

**Comment by guiccbr** [comment]
great, thanks @Krizzu

**Comment by krizzu** [comment]
So I was wrong and I did re-read the statement in docs and they're up to date.

**Comment by conoremclaughlin** [comment]
> So I was wrong and I did re-read the statement in docs and they're up to date.

@krizzu does this mean it's UNSAFE to use? This line is a bit confusing. Thanks for the help!

**Comment by krizzu** [comment]
It is safe to use if you want **completely** remove all data stored in AsyncStorage in one go. If one of your dependency uses AsyncStorage too, you're basically saving to the same storage, meaning if you call `clear` you clear it for both parties. This is something addressed in next version, still wip

**Comment by frahman5** [comment]
@krizzu So can another app on the phone clear our app's AsyncStorage by calling clear? Or is a clear invocation only deleting AsyncStorage for the calling app and its dependencies?

**Comment by Toissincera** [comment]
It's okay, let's go back and forth a couple more times before the dev can clear up whether my simple task app can nuke the entire async storage, nooooo worries.

**Comment by Toissincera** [comment]
> This is also confusing me, and [other people](https://medium.com/overlander/clearing-app-data-with-react-native-and-asyncstorage-18fb555029e7).
> 
> I think the docs are saying: AsyncStorage.clear will clear all your app data and any persisted data from libraries you've installed in your app. It does not affect other apps.
> 
> In which case, it should be safe to call AsyncStorage.clear() on logout, when I want to clear all user data for my app.
> 
> [@krizzu](https://github.com/krizzu) Is that accurate?

Not krizzu, but yes. AsyncStorage.clear() will perma-delete everything in your app, and only in your app, including things you might want to persist - like dark/light theme preference etc.
Plus, it's bad code practice, because if you don't define what is being deleted - just wiping it clean - how will other devs know what auth data you deleted? And what if AsyncStorage.clear() was accidentally called by another function?

I personally checked on my phone. Its safe to use, for your use case.
