### ISSUE TITLE
react-native 0.67.1

### ISSUE THREAD

**Issue by dlwo159** [react-native-async-storage/async-storage#740]
### Proposal

npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.0.0-0 || 0.60 - 0.66 || 1000.0.0" from @react-native-async-storage/async-storage@1.15.15

**Comment by alaintalk** [comment]
yeah they need to update rn and react version

**Comment by psmbitw** [comment]
same problem

Could not resolve dependency:
react-native@"^0.0.0-0 || 0.60 - 0.66 || 1000.0.0" from @react-native-async-storage/async-storage@1.15.15
node_modules/@react-native-async-storage/async-storage
@react-native-async-storage/async-storage@"*" from the root project
