### ISSUE TITLE
Types problem in  AsyncStorage when using WalletConnect in RN Dapp

### ISSUE THREAD

**Issue by ritvij14** [react-native-async-storage/async-storage#745]
### What happened?

![image](https://user-images.githubusercontent.com/51456744/152108545-c0a8c82e-bf36-448f-a54a-d96b97c99ec4.png)

### Version

1.15.17

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
info Fetching system and libraries information...
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 117.61 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.6.0 - ~/.nvm/versions/node/v16.6.0/bin/node
    Yarn: 1.22.17 - ~/Desktop/Projects/Huddle01-React-Native/node_modules/.bin/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v16.6.0/bin/npm
    Watchman: 2021.11.08.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8092744
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.6 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

I tried using `AsyncStorageLib` that was suggested by intellisense and also `AsyncStorage` mentioned in docs here https://react-native-async-storage.github.io/async-storage/docs/usage#importing

I am new to React Native so any help is appreciated.

**Comment by tido64** [comment]
This has nothing to do with AsyncStorage, the package. You need to implement the `IAsyncStorage` interface that `WalletConnect` expects, which may be implemented using AsyncStorage, but are completely unrelated. The names just happened to be similar.
