### ISSUE TITLE
AsyncStorage.getItem returns wired value

### ISSUE THREAD

**Issue by rockstar0711** [react-native-async-storage/async-storage#749]
Hello. Team, 

I am using Context/Asyncstorage for state management. 
I store the data which returned from server to the Asyncstorage.

```JAVASCRIPT
getData.then(
    res => AsyncStorage.setItem('user', JSON.stringify(res.data))
)
```

And I set the global state named user in Global provider like below.

```JAVASCRIPT
const [userState, userDispatch] = useReducer(
   user, userInitialState, 
   async () => {
      const storedUserData = await AsyncStorage.getItem('user');
      return storedUserData != null ? JSON.parse(storedUserData) : userInitialState;
   },
);
```

and Here is get the userState on other component

```JAVASCRIPT
const SomeComponent = () => {
   const {userState} = useContext(GlobalContext);

   useEffect ( () => {
      console.log(userState.name);   // undefined
      console.log(userState._W.name);   // sammie (correct)
   }, [])

   return <View></View>
}

```

The problem is first console state return undefined because the **userState** looks like this

```JSON
{
   "_U": 0,
   "_V": 1,
   "_W": {
      "name": "sammie",
      "email": "sammie@test.com",
      "phone": "123123123"
   },
   "_X": 0,   
}
```

Expected value is 

```JSON
{
   "_U": 0,
   "_V": 0,
   "_W": 0,
   "_X": 0,
   "name": "sammie",
   "email": "sammie@test.com",
   "phone": "123123123"   
}
```

I tried with other state for the test. and when I set the state in useEffect hook like below, it returns like as above.
```JAVASCRIPT
   useEffect ( () => {
      storeTheme('light')(themeDispatch);   // store the light mode to the global theme state
   }, [])
```
This theme state's data structure did not changed like as above.
I am absolutely wired about this. Please give me some advice what I am wrong. I don't know how to tag with help. so just submitted new issue here.
Thanks for any advise.

**Comment by krizzu** [comment]
Hey @rockstar0711 

The issue you see is not related to AsyncStorage, but rather the fact that you provide an async function as your reducer. Async functions always return a promise (that's what you see in console, object with _U, _V keys).
