### ISSUE TITLE
MultiRemove fails on Windows

### ISSUE THREAD

**Issue by tero-paananen** [react-native-async-storage/async-storage#755]
### What happened?

MultiRemove fails in this row in Windows:

https://github.com/react-native-async-storage/async-storage/blob/a1be0508271b58c878cd2a1041fbb410383df2c5/windows/code/DBStorage.cpp#L524

fix is to call `CHECK_SQL_OK(BindString(statement, i + 1, keys[i]));` 

`sqlite3_bind_text` returns `SQLITE_OK`  see more from https://www.sqlite.org/c3ref/bind_blob.html 

### Version

1.15.15

### What platforms are you seeing this issue on?

- [X] Windows

### System Information

```true
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 17.89 GB / 31.90 GB
  Binaries:
    Node: 12.22.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.31829.152 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: 0.65.1 => 0.65.1
    react-native-windows: 0.65.9 => 0.65.9
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

Try to remove from storage

**Comment by tero-paananen** [comment]
https://www.sqlite.org/c3ref/bind_blob.html 

`sqlite3_bind_text` returns `SQLITE_OK`

**Comment by tero-paananen** [comment]
> @vmoroz: Can you please have a look? Or forward this to someone who can?

I would be good to fix this soon

**Comment by vmoroz** [comment]
@tero-paananen, @tido64 thank you for reminding! Sorry, it completely dropped off my radar. I will fix it this week.

**Comment by vmoroz** [comment]
@tero-paananen, thank you for reporting the issues!
It seems that there is nothing else to do besides fixing the use of the macro as it mentioned in the issue.
Do not hesitate to submit a PR for issues like this in future.  :)
