### ISSUE TITLE
indexedDB support on V1

### ISSUE THREAD

**Issue by nabilfreeman** [react-native-async-storage/async-storage#771]
### Proposal

I noticed that development of v2 has stalled and as a result the web version of async storage still uses `localStorage`.

I've noticed two drawbacks when working on larger RN projects:

1) 5mb hard limit on local storage
2) Synchronous nature of local storage blocks thread

I managed to override things in a very crude way using this gist which attempts to quickly wrap a localStorage API with IndexedDB:

https://gist.github.com/wilsonpage/01d2eb139959c79e0d9a

And a very messy `patch-package` on `node_modules/@react-native-async-storage/async-storage/lib/module/AsyncStorage.js`!

which unblocked me on the 5mb storage limit. IndexedDB actually has a much, much larger limit in most circumstances:

https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria

Is this something that's been discussed before, and something the team would be open to integrating?

Thanks! Nabs

### Alternatives

I noticed that `localForage` has a very mature `localStorage`-like API that uses IndexedDB and Session storage behind the scenes.

https://localforage.github.io/localForage/

As a 3rd party library I assume some webpack trickery would be needed to integrate this with `react-native-web`

### Implementation Details

I think using the gist as a foundation, plus implementing some sort of flag on the main AsyncStorage import, it would be possible to extend the methods here:

https://github.com/react-native-async-storage/async-storage/blob/master/src/AsyncStorage.ts#L72

To support both localStorage and IndexedDB.

Perhaps the flag could look something like this:

```
import AsyncStorage from '@react-native-async-storage/async-storage`;

AsyncStorage.useWebIndexedDb = true;

// proceed to use get/setters exactly as previously
```

**Comment by nabilfreeman** [comment]
:(

**Comment by krizzu** [comment]
Hey @nabilfreeman, sorry that this got closed.
I haven't had time to refer to your enhancement yet, but I think IndexedDB should be replaced with local storage. One reason is storage limit, second it that LocalStorage is sync. I checked localForge before and it looks like a good candidate to use. 

We'd have to think about few bits, like transition from current implementation to new one (migration), how to enable it (feature flag?) and any differences in localStorage vs indexedDB.

**Comment by krizzu** [comment]
There's plan to add IndexedDB to the second version of AsyncStorage. I'll post more updates soon 😃

**Comment by deanmraz** [comment]
Hey @krizzu, is there any update on IndexedDB?

**Comment by ansh** [comment]
Is there any update here? @krizzu 

IndexedDB is a must have in 2025.

**Comment by nabilfreeman** [comment]
Update: I recently dropped async storage after hitting limits on Android and moved to `expo-file-system`. Actually it turns out that `localForage` is implemented in file system too!

I'm not 100% on how it works yet but this package is a dependent of the main library: `localforage-expo-filesystem-driver`.

I'll edit this comment with a final retro. One of the outcomes might be dropping async storage altogether on all platforms sadly.
