### ISSUE TITLE
Unexpected token after type declaration

### ISSUE THREAD

**Issue by mirzaam786** [react-native-async-storage/async-storage#778]
I have this issue when i run from XCode onto an IOS 11 debug simulator. Is there an issue with type declarations ?

/node_modules/@react-native-async-storage/async-storage/src/index.ts: Unexpected token (2:12)

  1 | import AsyncStorage from './AsyncStorage';
> 2 | import type { AsyncStorageHook, AsyncStorageStatic } from './types';
    |                         ^
  3 | 
  4 | export { useAsyncStorage } from './hooks';
  5 | export type { AsyncStorageStatic } from './types';

**Comment by tido64** [comment]
Please don't delete the template when filing new issues. They're there so we can better help you.

Do you have a repro of this issue anywhere we can look at? In general, your Babel config should already contain the TypeScript plugin to strip out type annotations and so on. It looks like it's not being applied here, so the config would be the first thing I'd look at.

**Comment by nauderuan** [comment]
I also get this error from version v1.16.0 "migrate from Flow to TypeScript".
v1.15.17 works fine.
Our project does not use TypeScript so maybe that is the issues.

**Comment by fermyth** [comment]
I also got the same problem where the compiler can not recognize 
"import type " 
in the async storage ts file.

There are 2 ways i can recommend you to do to solve the problem :
1. Remove all the "type " in "import type "  in all ts file in asyncstorage src folder (and i mean all files that has "import type" ) . now if you compile the the code, it will run smoothly.
2. the "import type " function is not recognize in earlier version of babel metro, so what i did is i open my package.json file and change babel version to the latest.
    "@babel/core": "7.9.6",
    "@babel/runtime": "7.9.6",
  recompile the program and it should working now :) .

please try on your project and hope it helps :)

**Comment by codemaker2015** [comment]
Try the following steps to resolve the issue,

- `npm install @babel/core@^7.9.0`
- `npm install @babel/runtime@^7.9.2`
- `npm install typescript@^3.8.3`
- `rm -rf node_modules`
- `npm install`
- Uninstall app in emulator/phone.
- `npm start -- --reset-cache`
