### ISSUE TITLE
ERR! Could not resolve dependency

### ISSUE THREAD

**Issue by HristoS** [react-native-async-storage/async-storage#791]
### What happened?

When i am taring to install with react-native react-native@"0.68.0"  , i've got 
npm ERR! While resolving: carassistant@0.0.1
npm ERR! Found: react-native@0.68.0
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.68.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.0.0-0 || 0.60 - 0.67 || 1000.0.0" from @react-native-a
npm ERR! node_modules/@react-native-async-storage/async-storage
npm ERR!   @react-native-async-storage/async-storage@"*" from the root project

### Version

1.17.2

### What platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [ ] macOS
- [X] Windows
- [ ] web

### System Information

```true
PS C:\Repositories\FE\CarAssistant> npm install @react-native-async-storage/async-sto
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: carassistant@0.0.1
npm ERR! Found: react-native@0.68.0
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.68.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.0.0-0 || 0.60 - 0.67 || 1000.0.0" from @react-native-a
npm ERR! node_modules/@react-native-async-storage/async-storage
npm ERR!   @react-native-async-storage/async-storage@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hristo.stoev\AppData\Local\npm-cache\_logs\2022-03-31T13_58_44_
PS C:\Repositories\FE\CarAssistant>
                                  > npm install @react-native-async-storage/async-sto
>>
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: carassistant@0.0.1
npm ERR! Found: react-native@0.68.0
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.68.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.0.0-0 || 0.60 - 0.67 || 1000.0.0" from @react-native-a
npm ERR! node_modules/@react-native-async-storage/async-storage
npm ERR!   @react-native-async-storage/async-storage@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hristo.stoev\AppData\Local\npm-cache\_logs\2022-03-31T14_03_41_527Z-debug-0.log
```

### Steps to Reproduce

run npm install @react-native-async-storage/async-storage with react-native@"0.68.0"

**Comment by varemenos** [comment]
@tido64 sorry to bump a closed issue but im experiencing the same issue, but granted it's for an unreleased version of RN. Is there a way to unblock installations of the package for release candidates without nagging the maintainers to add support before an official RN release?

I'm trying to set up my app with 0.71-rc0 but npm (v9) refuses to install async storage because it cannot resolve the RN dependency `react-native@"^0.0.0-0 || 0.60 - 0.70 || 1000.0.0"`). The only 2 workarounds I've found so far are either downgrading npm to v6 or(--legacy-peer-deps) but that's harders to fiddle with in a CI or a colleague's machine.

**Comment by tido64** [comment]
> @tido64 sorry to bump a closed issue but im experiencing the same issue, but granted it's for an unreleased version of RN. Is there a way to unblock installations of the package for release candidates without nagging the maintainers to add support before an official RN release?
> 
> I'm trying to set up my app with 0.71-rc0 but npm (v9) refuses to install async storage because it cannot resolve the RN dependency `react-native@"^0.0.0-0 || 0.60 - 0.70 || 1000.0.0"`). The only 2 workarounds I've found so far are either downgrading npm to v6 or(--legacy-peer-deps) but that's harders to fiddle with in a CI or a colleague's machine.

We can probably bump that number up to 0.71. Feel free to submit a PR if you can/have time. I won't be able to until next week at the earliest.

**Comment by varemenos** [comment]
I opened #870
