### ISSUE TITLE
macOS minimum supported version

### ISSUE THREAD

**Issue by samkpo** [react-native-async-storage/async-storage#797]
### What happened?

I want to build the project with macOS version 10.13 , but the minimum version seems to be 10.14.
Is there any reason for it to be the minimum one? Will I encounter some issues lowering it to 10.13?

### Version

1.17.3

### What platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [X] macOS
- [ ] Windows
- [ ] web

### System Information

```true
.
```

### Steps to Reproduce

.

**Comment by tido64** [comment]
The last update for macOS 10.13 was in November 2020. Apple has ended support for it. I don't think you'll hit any issues if you still want to build for 10.13, but you're basically on your own if you do. I hope that answers your questions.
