### ISSUE TITLE
React 18 compatibility

### ISSUE THREAD

**Issue by diegoalvarezb** [react-native-async-storage/async-storage#801]
### Proposal

With the new version of React (18) this package is not compatible.

It should be great to make it compatible with this new version.

**Comment by tido64** [comment]
Hi, I'm not sure I understand this issue. AsyncStorage does not use react at all. Why would it be incompatible with React 18?

**Comment by tido64** [comment]
Which react-native version are you using? react-native does not support react 18 yet. 0.69 will, but it's not out. When it is, we will update this package.

**Comment by diegoalvarezb** [comment]
Got it! Thanks!

**Comment by ecureuill** [comment]
```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @react-native-community/async-storage@1.12.1
npm ERR! Found: react@18.0.0
...
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8" from @react-native-community/async-storage@1.12.1
npm ERR! node_modules/@react-native-community/async-storage
npm ERR!   @react-native-community/async-storage@"^1.12.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peer react@"^16.8" from @react-native-community/async-storage@1.12.1
npm ERR!   node_modules/@react-native-community/async-storage
npm ERR!     @react-native-community/async-storage@"^1.12.1" from the root project
```

**Comment by eakeyson1** [comment]
Any update on this? React Native is now at v70 and I receive the same error as @ecureuill

**Comment by EvanKoe** [comment]
error expo-cli@6.0.5: The engine "node" is incompatible with this module. Expected version ">=12 <=16". Got "18.9.0"
error Found incompatible module.

**Comment by maxymczech** [comment]
@tido64 the dependency is literally in the `package.json`: https://github.com/react-native-async-storage/async-storage/blob/df99c4e89fcdeadb35dc1a03b094cd10c2b79872/package.json#L87

**Comment by tido64** [comment]
> @tido64 the dependency is literally in the `package.json`:
> 
> https://github.com/react-native-async-storage/async-storage/blob/df99c4e89fcdeadb35dc1a03b094cd10c2b79872/package.json#L87

That's under `devDependencies`. It's only installed when you're working inside AsyncStorage. It does not get installed when you're just consuming the package.

**Comment by paddymccallan** [comment]
> Which react-native version are you using? react-native does not support react 18 yet. 0.69 will, but it's not out. When it is, we will update this package.

I believe this is the the case now. Seeing this issue too

**Comment by tido64** [comment]
@nabilfreeman: Please see my answer here: https://github.com/react-native-async-storage/async-storage/issues/801#issuecomment-1269942275

Also, `@react-native-community/async-storage` is deprecated. This package has been renamed to `@react-native-async-storage/async-storage`.

**Comment by nabilfreeman** [comment]
@tido64 thanks, I spotted that I was installing the wrong dependency a few minutes after posting. I wonder if this is the pitfall a few people have fallen into?

Installing `@react-native-async-storage/async-storage` worked as expected! 🎉

**Comment by tido64** [comment]
Package managers should be warning you when you install. You won't be able to search for the package on npm, and there's a huge banner when you open the link directly:

![image](https://github.com/react-native-async-storage/async-storage/assets/4123478/5cab534e-00a0-4d72-b46a-cd3dbb7545d7)

I'm not sure what else we can do at this point 😅

**Comment by nabilfreeman** [comment]
I don't think it's a big deal, it's only old farts like me who have the RN community one in muscle memory 😜

**Comment by Durotemy** [comment]
![Screen Shot 2023-08-19 at 8 08 57 AM](https://github.com/react-native-async-storage/async-storage/assets/90837486/61a968af-ccc4-46e8-8f8b-6de5d7aaa337)

i honestly dont know why this fails to work
