### ISSUE TITLE
setItem crashes app if value is a number

### ISSUE THREAD

**Issue by scd8418** [react-native-async-storage/async-storage#809]
### What happened?

The function below will crash the app every time. 
 
 await AsyncStorage.setItem('@welcome', 10)

The function should either return an error or simply convert the number to a string. 

The problem has been further documented by other users on StackOverflow

https://stackoverflow.com/questions/48234708/asyncstorage-setitem-crashes-ios-every-time-works-perfectly-on-android-expo

### Version

1.16.1

### What platforms are you seeing this issue on?

- [ ] Android
- [X] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
    Memory: 343.53 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_45 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.3 => 0.64.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

Insert the function below into any program.

 await AsyncStorage.setItem('@welcome', 10)

**Comment by krizzu** [comment]
AsyncStorage accepts only `strings` as values, it's described [in its API](https://react-native-async-storage.github.io/async-storage/docs/api#setitem). It is so that you provided already serialized data.

**Comment by scd8418** [comment]
An app crash hardly seems like a good way to handle an error condition.
