### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by dzienisz** [react-native-async-storage/async-storage#816]
### Proposal

Where is Changelog for this project? Can we generate it?

**Comment by krizzu** [comment]
Here:
[CHANGELOG file](https://github.com/react-native-async-storage/async-storage/blob/master/CHANGELOG.md)

and here:
[releases](https://github.com/react-native-async-storage/async-storage/releases)

**Comment by dzienisz** [comment]
what about changelog before 1.15.X ??
