### ISSUE TITLE
mergeItem does not work with typescript

### ISSUE THREAD

**Issue by jruebl** [react-native-async-storage/async-storage#818]
### What happened?

I can not use "mergeItem" when using Typescript:

"Merges an existing key value with an input value, assuming both values are stringified JSON."

Is there any suggestion or maybe a workaround?

### Version

1.17.6

### What platforms are you seeing this issue on?

- [ ] Android
- [X] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
Mac Book Pro
```

### Steps to Reproduce

Use mergeItem in combination with Typescript.

**Comment by krizzu** [comment]
Hey,

can you post the code you're trying to use? Also, please do not skip issue template.

**Comment by jayfunk** [comment]
I believe this issue is the same as #826 https://github.com/react-native-async-storage/async-storage/issues/826
