### ISSUE TITLE
AsyncStorage has been extracted from react-native core ...

### ISSUE THREAD

**Issue by jamesbond-7** [react-native-async-storage/async-storage#819]
### What happened?

Hey Folks,
I have installed **@react-native-async-storage/async-storage** package. Upon importing AsyncStorage as below - 
import AsyncStorage from "@react-native-async-storage/async-storage";

I'm getting warning "AsyncStorage has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-async-storage/async-storage' instead of 'react-native'. See https://github.com/react-native-async-storage/async-storage". Although, I've imported Async Storage from "@react-native-async-storage/async-storage".
Apart that, I have given try  reinstalling again. Still error prompts back.

![async-storage-error](https://user-images.githubusercontent.com/42155161/175971320-42db6177-2e01-4bf4-a07e-68f1ea5fd600.PNG)

### Version

1.17.7

### What platforms are you seeing this issue on?

- [X] Android
- [X] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.16299
    CPU: (4) x64 Intel(R) Core(TM) i3-4010U CPU @ 1.70GHz
    Memory: 619.20 MB / 3.94 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: 15.9.28307.557 (Visual Studio Community 2017)
  Languages:
    Java: 1.8.0_144 - /c/Program Files/Java/jdk1.8.0_144/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.2 => 0.68.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.69.0 is now available (your project is running on v0.68.2).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.69.0.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.68.2.
info To upgrade, run "react-native upgrade"
```

### Steps to Reproduce

1) Install package: @react-native-async-storage/async-storage
2) import AsyncStorage from "@react-native-async-storage/async-storage";

**Comment by tido64** [comment]
If you look at the stack trace, it looks like `@firebase/auth` is pulling it in:

![Screenshot 2022-06-27 at 19 10 08](https://user-images.githubusercontent.com/4123478/175997339-c6e08c86-2258-4bdb-abbf-112c44f247ad.png)

**Comment by jamesbond-7** [comment]
@tido64 thanks man. I cross checked.
