### ISSUE TITLE
-(void)multiRemove:(NSArray<NSString *> *)keys callback:(RCTResponseSenderBlock)callback is not available in RNCAsyncStorage.h

### ISSUE THREAD

**Issue by ihiteshkumarp** [react-native-async-storage/async-storage#825]
### What happened?

-(void)multiRemove:(NSArray<NSString *> *)keys callback:(RCTResponseSenderBlock)callback is not available in RNCAsyncStorage.h

This method to required to remove items.

### Version

1.17.7

### What platforms are you seeing this issue on?

- [ ] Android
- [X] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
iOS mobile app
```

### Steps to Reproduce

Check this file https://github.com/react-native-async-storage/async-storage/blob/master/ios/RNCAsyncStorage.h

**Comment by tido64** [comment]
@ihiteshkumarp are you asking if this method can be added to the header?
