### ISSUE TITLE
Cant get string in return of encrypted values 

### ISSUE THREAD

**Issue by androdat** [react-native-async-storage/async-storage#843]
### What happened?

const getData = async key => {
  try {
    const value = await AsyncStorage.getItem(key);
    if (value !== null) {
      // value previously stored
      console.log({value});
      return value;
    }
  } catch (e) {
    // error reading value
  }
};

console.log({value}) this prints the normal string  but 
MY FUNCTION RETURNS  {"_h": 0, "_i": 0, "_j": null, "_k": null} instead of string value.

### Version

1.17.10

### What platforms are you seeing this issue on?

- [X] Android
- [X] iOS
- [X] macOS
- [X] Windows
- [X] web

### System Information

```true
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 1.67 GB / 11.83 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-212.5712.43.2112.8609683
    Visual Studio: Not Found
  Languages:
    Java: 11.0.15
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.1 => 0.70.1
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

na

**Comment by tido64** [comment]
Hi @androdat, you didn't show the code where you printed the return value of your function or provided a repro, but if I had to guess, it looks like you logged the `Promise` instead. Did you await it before logging the value?

**Comment by krizzu** [comment]
Seems like this is related to dev error rather than AsyncStorage. Please reopen if we're mistaken.

**Comment by alejup21** [comment]
I have the same problem, someone knows how is the way to correctly declare this?

**Comment by fantasyinfo** [comment]
i also get same error
 just use like this it will work 100%

  console.log(
            AsyncStorage.getItem('UserData')
              .then(data => {
                console.log(` Data from Promise ${data}`);
              })
              .catch(e => {
                console.log(e);
              }),
          );



give me a like if its work, its my first time to do some contribution, if i got like, i will also do this in future ok

**Comment by fantasyinfo** [comment]
> I have the same problem, someone knows how is the way to correctly declare this?

  console.log(
            AsyncStorage.getItem('UserData')
              .then(data => {
                console.log(` Data from Promise ${data}`);
              })
              .catch(e => {
                console.log(e);
              }),
          );

**Comment by gaoxiaosong1113** [comment]
app.js

```
const getLock = async () => {
    let lock;
    try {
      lock = await AsyncStorage.getItem('lock');
      console.log(isLock, 'app-lock-111'); // { _h: 0, _i: 0, _j: null, _k: null }
    } catch (e) {
      // save error
    }
    return lock;
  };

  const isLock = getLock();
  console.log(isLock, 'app-lock');  // { _h: 0, _i: 0, _j: null, _k: null }
```
output  Hahaha

**Comment by androdat** [comment]
Guys all of this is happening because we are not waiting for the promise to get resolved the function returns a promise use await or .then you will not face this issue anymore

**Comment by wasswaenockmale** [comment]
export async function getLocalCart(){
    // retrieve data from the local storage.
     await AsyncStorage.getItem('cartItemList').then(item => {
        // console.log(item)
        if(item != null){
            console.log(item)
            return JSON.parse(item)
        }else{
            return []
        }
    }).catch(e => {
        console.log(e);
    })
}

const data = getLocalCart();
console.log(data)  // { _h: 0, _i: 0, _j: null, _k: null } is the output

**Comment by oosunkeye** [comment]
> wait AsyncStorage.getItem('lock');

@androdat  paste your working code, I am still facing the same issue
