### ISSUE TITLE
Android app crashes without logs, adb logcat shows [Didn't find class "com.reactnativecommunity.asyncstorage.AsyncStoragePackage"]

### ISSUE THREAD

**Issue by raphaelmsr** [react-native-async-storage/async-storage#848]
### What happened?

On a fresh install, removed node_modules and played multiple times between yarn & npm; every build for Android crashes  (runs fine on iOS)
Using Expo SDK 46 and the version 1.17.10 of the package (every previous version has the same bug)
I had to manually link the package as to what's written in the Manual Linking page in the API.
This should be completely automatic and somehow only this package has this issue.

### Version

1.17.10

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
info Fetching system and libraries information...
System:
    OS: macOS 12.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.56 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
    Watchman: 2022.08.08.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.6 => 0.69.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

Install "@react-native-async-storage/async-storage": "^1.17.10", call the package in App.js,  run `npx expo run:android`

**Comment by raphaelmsr** [comment]
Expo *does* allow for native modules since Expo 44 I guess

The error is exactly whats written in the title, sorry about that `Didn't find class "com.reactnativecommunity.asyncstorage.AsyncStoragePackage" `

It looks like React Native 0.69 breaks lots of packages’ autolinking. 

https://github.com/getsentry/sentry-react-native/issues/2267

https://github.com/andpor/react-native-sqlite-storage/issues/522

Dont know if related; but I have used AsyncStorage in the past, in Expo; and never had to manually link anything

**Comment by raphaelmsr** [comment]
Here is a reproductive example; and it does crash the same way. 

1. `npx create-expo-app my-app-async && cd my-app-async`
2. `expo install @react-native-async-storage/async-storage`
3. Changing App.js to
```
import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View, Button } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';

export default function App() {

  const storeData = async (value) => {
    try {
      await AsyncStorage.setItem('@storage_Key', value)
    } catch (e) {
      // saving error
    }
  }
  
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <Button onPress={()=>storeData("Test")} >TEST</Button>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});


```

4. `export ANDROID_SDK_ROOT="~/Library/Android/sdk"; npx expo run:android `

Crashes without logs in the Debugger, only in `adb logcat`

I am not sure whether it is actually an Expo bug, I believe it is related to RN 0.69

**Comment by krizzu** [comment]
Thanks for the repro steps. I manage to get up and running, without manual linking. So all is good on my side.

I see that you got it working too, so that's good! Feel free to close the issue.

**Comment by raphaelmsr** [comment]
No thats not what I meant haha
I removed the package *then* everything worked fine; but I need it!
I just double-checked in case something was wrong with my environment or with the Expo template; I checked without packages if it would build and run and it did

**Comment by krizzu** [comment]
I ran the expo app with your steps just fine, so probably it's your dev env?

**Comment by raphaelmsr** [comment]
Wow really ? Somehow I had to downgrade Expo version to SDK 45 it still didn't work, downgraded again to SDK 44 and now it works like it should
Thanks a million for trying to repro the steps; I'm glad it works actually. It means your package is fine
Although I have *no idea* how to debug my environment ... Haha

Thanks again, shall I close ?

**Comment by krizzu** [comment]
Maybe try to clone your project again and then install everything? You can also try to do `yarn cache clean` to be sure that yarn will fetch packages again.

Yes, feel free to close
