### ISSUE TITLE
AsyncStorage is null

### ISSUE THREAD

**Issue by AdurintiAshok** [react-native-async-storage/async-storage#857]
### What happened?

I am creating a Native module and have the AsyncStorage package installed.
I'm getting an error saying that AsyncStorage is null after installing this native module in my React Native application.
Please provide any suggestions you have on this.

### Version

1.17.10

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
OS: macOS 12.6
    CPU: (10) x64 Apple M1 Pro
    Memory: 33.51 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.20.0/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
    Watchman: 2022.10.10.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 24, 29, 30, 31, 32
      Build Tools: 28.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0
      System Images: android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^9.2.1 => 9.2.1 
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.3 => 0.70.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

###

**Comment by magaro98** [comment]
same problem!

**Comment by AdurintiAshok** [comment]
@krizzu I followed your instructions but still it is throwing same error.
Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.

**Comment by Kitketovsky** [comment]
@krizzu I also tried reinstalling the library and it turned out to the same error
[@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.

`
{
  "name": "traffic-dojo-webview",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "dev:build": "eas build --platform android --profile development",
    "dev:build:start": "eas build:run --platform android --latest",
    "dev": "npx expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-native-firebase/analytics": "^18.1.0",
    "@react-native-firebase/app": "^18.1.0",
    "@supabase/supabase-js": "^2.26.0",
    "expo": "~48.0.18",
    "expo-dev-client": "^2.2.1",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "~1.4.4",
    "react": "18.2.0",
    "react-native": "0.71.8",
    "react-native-url-polyfill": "^1.3.0",
    "@react-native-async-storage/async-storage": "1.17.11"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}
`
