### ISSUE TITLE
I cannot get iCloud backup to work

### ISSUE THREAD

**Issue by Fischaela** [react-native-async-storage/async-storage#859]
### What happened?

**What did you expect to happen?**

I was expecting my apps redux store which uses `@react-native-async-storage/async-storage` to be backed up. So when users uninstall the app, the data will be saved in iCloud as a backup. And when a user reinstalls the app, the backup will be applied and the redux stores data is available in the app.

### Version

1.17.10

### What platforms are you seeing this issue on?

- [ ] Android
- [X] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 252.14 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/michaelalehr/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.4 => 0.69.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

**What did you do?**

I updated `info.plist` like described in the docs:

```
<key>RCTAsyncStorageExcludeFromBackup</key>
<false/>
```

Then I used `@react-native-async-storage/async-storage` it as the storage of my persistent redux store:

```
const persistConfig = {
  key: 'root',
  version: 1,
  storage: AsyncStorage,
  blacklist: blacklistPaths,
}
```

I also added iCloud to the Capabilities in Xcode:

<img width="556" alt="Screenshot_2022-11-03_at_11_42_36" src="https://user-images.githubusercontent.com/3409561/199701134-44798c96-f6b9-442b-8180-cc7c098f6b98.png">

**What did happen?**

Testing it in a simulator and on a real device via TestFlight, I cannot see any data saved to the iCloud. 

<img width="594" alt="Screenshot_2022-11-03_at_11_47_39-2" src="https://user-images.githubusercontent.com/3409561/199702850-d6e33a94-db6c-45c2-8b2a-5c3f788750d9.png">

When uninstalling and reinstalling the app, the data is not backed up.

Do you have any idea what I am doing wrong? 
Cheers, Michaela

**Comment by Fischaela** [comment]
Any updates here? Can anyone help?

**Comment by graemegeorge** [comment]
@Fischaela having the same issue here did you get anywhere with it?

**Comment by rachellauyui** [comment]
@Fischaela Hey, I have the same issue. Wonder if you have managed to get it working? Thanks!

**Comment by Fischaela** [comment]
@rachellauyui @graemegeorge I did not manage to make it work. You?

**Comment by floki-92** [comment]
same issue here

**Comment by Uroosaajaz** [comment]
I am facing same issue any update about this?
