### ISSUE TITLE
[Android] Again, Project with path ':@react-native-community_async-storage' could not be found in project ':app'.

### ISSUE THREAD

**Issue by connercharles** [react-native-async-storage/async-storage#867]
### What happened?

Same problem as: https://github.com/react-native-async-storage/async-storage/issues/221 but the solutions do not work for me. I had both of the suggest lines already in the different files. 

Followed https://react-native-async-storage.github.io/async-storage/docs/link#android and ran `./gradlew assembleRelease`
Got:
```
* What went wrong:
A problem occurred evaluating project ':app'.
> Project with path ':@react-native-async-storage' could not be found in project ':app'.
```

`"react-native": "0.70.3"`

### Version

1.17.10

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
Followed https://react-native-async-storage.github.io/async-storage/docs/link#android and ran `./gradlew assembleRelease`
Got:

* What went wrong:
A problem occurred evaluating project ':app'.
> Project with path ':@react-native-async-storage' could not be found in project ':app'.
```
```


### Steps to Reproduce

Followed https://react-native-async-storage.github.io/async-storage/docs/link#android and ran `./gradlew assembleRelease`

**Comment by krizzu** [comment]
With RN 0.70, manual linking is not required. Remove the code and rebuild the app, should be fine

**Comment by krizzu** [comment]
Closing, please reopen if need further help
