### ISSUE TITLE
'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by huynhbinh6** [react-native-async-storage/async-storage#873]
### What happened?

Hi guys, I faced this issue with: 
**React Native: 0.70  and "@react-native-async-storage/async-storage": "1.17.10"**
Anyone else faced same me? 
<img width="856" alt="Screen Shot 2022-11-15 at 03 39 19" src="https://user-images.githubusercontent.com/85099321/201761302-e6b3bb6f-d62a-4c74-935b-eb21956887cd.png">

### Version

1.17.10

### What platforms are you seeing this issue on?

- [ ] Android
- [X] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 97.63 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.9.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.1 - /opt/homebrew/bin/npm
    Watchman: 2022.09.26.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.1 => 0.70.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

I followed this link but when I installed the package and ran **pod install**  linking automation not working and I did Manual linking ---> got this issue

Link: https://react-native-async-storage.github.io/async-storage/docs/link

**Comment by krizzu** [comment]
Can you explain what exactly you mean by `automation linking not working`?
Please reverse the manual step and try again by running `pod install` and let me know if you get any issues with it

**Comment by huynhbinh6** [comment]
> Can you explain what exactly you mean by `automation linking not working`? Please reverse the manual step and try again by running `pod install` and let me know if you get any issues with it

I followed this doc: https://react-native-async-storage.github.io/async-storage/docs/install/
and see [CLI auto-link feature] when building the app, but when I built the app I got a problem with libraries, it look like linking the libraries to the app ( I ran pod install after installing the package )

**Comment by huynhbinh6** [comment]
solved
