### ISSUE TITLE
package javax.annotation does not exist

### ISSUE THREAD

**Issue by hiepledge** [react-native-async-storage/async-storage#881]
### What happened?

AsyncLocalStorageUtil.java: 

> package javax.annotation does not exist
> package com.facebook.react.bridge does not exist
> cannot find symbol class ReadableArray
> cannot find symbol class Nullable

### Version

1.17.11

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2022.09.19.00 - /usr/local/bin/watchman
 
IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

### Steps to Reproduce

npx react-native run-android

**Comment by greis** [comment]
Found this workaround and it fixed this issue for me https://stackoverflow.com/questions/74364683/package-com-facebook-react-bridge-does-not-exist-react-native-android-build-issu

**Comment by hiepledge** [comment]
>
