### ISSUE TITLE
Brownfield - Swift integration issue with setting value(s)

### ISSUE THREAD

**Issue by lostchopstik** [react-native-async-storage/async-storage#882]
### What happened?

I am attempting to utilize the brownfield methods in my Swift code, but almost every method returns an error. The error, from what I can gather online, indicates that there is something missing on the source Objective-C side like an `@objc` call on the methods.

The error I am getting is:
`
Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<RNCAsyncStorage 0x6000028d7030> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key lastChannel.'
`

And this happens when calling the method like this:
``` swift
// At the top of the file
private let storage = RNCAsyncStorage()

// In my init method
super.init()

self.storage.methodQueue.async {
    self.storage.setValue("channel", forKeyPath: "lastChannel")
}
```

I've tried `setValuesForKeys` and `multiSet` but got the same error

### Version

1.17.11

### What platforms are you seeing this issue on?

- [ ] Android
- [X] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
info Fetching system and libraries information...
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 111.00 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.8.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.18.0 - /opt/homebrew/bin/npm
    Watchman: 2022.08.22.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.3 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

Run the methods mentioned above in Swift code.

The only method I can successfully use is `multiGet` which I use for other data fetching.

**Comment by lostchopstik** [comment]
Just as a side note, it would be super cool if the docs had anything about using the library in Swift instead of only Objective-C. The Kotlin integration was so much smoother!

**Comment by tido64** [comment]
Hi @lostchopstik, I'm not sure where you got those method signatures from. You can find the header file here: https://github.com/react-native-async-storage/async-storage/blob/master/ios/RNCAsyncStorage.h

I haven't tried this myself, but you can probably call `multiSet` like this:

```swift
self.storage.multiSet([["key", "value"]]) { 
  print("done")
}
```

**Comment by lostchopstik** [comment]
@tido64  thank you! I got the signatures from XCode autocompletion. Here was the code that worked, I just had to add a discard to the completion:
``` swift
self.storage.multiSet([["lastChannel", "{\"channelId\": 5}"]]) { _ in
   print("done")
}
```
