### ISSUE TITLE
DB.init wont start in "@react-native-async-storage/async-storage": "^1.15.16", 

### ISSUE THREAD

**Issue by Eredoqo** [react-native-async-storage/async-storage#885]
### What happened?

Database Sqlite wont start in RN app IOS, the app don't read the tables, in Android is correctly functionality.

Using expo version 41,
react version 17.0.2,
react-native version 0.67.3,
"expo-sqlite": "~9.1.0",

### Version

1.15.16

### What platforms are you seeing this issue on?

- [ ] Android
- [X] iOS
- [X] macOS
- [ ] Windows
- [ ] web

### System Information

```true
[Error: Error code 1: no such table: <table name>]
 WARN  Possible Unhandled Promise Rejection (id: 0):
"Cannot find foreign key!"
```

### Steps to Reproduce

"@react-native-async-storage/async-storage": "^1.15.16",

**Comment by tido64** [comment]
AsyncStorage has nothing to do with `expo-sqlite`. Please file an issue over at Expo instead: https://github.com/expo/expo/issues
