### ISSUE TITLE
I can't build debug and release app on android with targetSdkVersion 31

### ISSUE THREAD

**Issue by AngelDev727** [react-native-async-storage/async-storage#887]
### What happened?

> Task :app:processReleaseMainManifest FAILED
[:@react-native-async-storage] /Volumes/MyDATA/Project/2022/07/xanababy-mine/node_modules/@react-native-async-storage/async-storage/android/build/intermediates/merged_manifest/release/AndroidManifest.xml Warning:
        Package name 'com.reactnativecommunity.asyncstorage' used in: :@react-native-async-storage, :react-native-async-storage_async-storage.
[:react-native-community-netinfo] /Volumes/MyDATA/Project/2022/07/xanababy-mine/node_modules/@react-native-community/netinfo/android/build/intermediates/merged_manifest/release/AndroidManifest.xml Warning:
        Package name 'com.reactnativecommunity.netinfo' used in: :react-native-community-netinfo, :react-native-community_netinfo.
/Volumes/MyDATA/Project/2022/07/xanababy-mine/android/app/src/main/AndroidManifest.xml:38:9-54:20 Error:
        android:exported needs to be explicitly specified for element <activity#com.stripe.android.payments.StripeBrowserLauncherActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseMainManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 4 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD FAILED in 1m 28s
126 actionable tasks: 117 executed, 9 up-to-date
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Version

1.17.11

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
info Fetching system and libraries information...
(node:9391) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 12.6.1
    CPU: (8) x64 Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz
    Memory: 12.15 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.3 - /xanababy-mine/node_modules/.bin/npm
    Watchman: 2022.11.14.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

When build android app using react-native run-android, I am getting the errors.

> Task :app:processReleaseMainManifest FAILED
[:@react-native-async-storage] /Volumes/MyDATA/Project/2022/07/xanababy-mine/node_modules/@react-native-async-storage/async-storage/android/build/intermediates/merged_manifest/release/AndroidManifest.xml Warning:
        Package name 'com.reactnativecommunity.asyncstorage' used in: :@react-native-async-storage, :react-native-async-storage_async-storage.
[:react-native-community-netinfo] /Volumes/MyDATA/Project/2022/07/xanababy-mine/node_modules/@react-native-community/netinfo/android/build/intermediates/merged_manifest/release/AndroidManifest.xml Warning:
        Package name 'com.reactnativecommunity.netinfo' used in: :react-native-community-netinfo, :react-native-community_netinfo.
/Volumes/MyDATA/Project/2022/07/xanababy-mine/android/app/src/main/AndroidManifest.xml:38:9-54:20 Error:
        android:exported needs to be explicitly specified for element <activity#com.stripe.android.payments.StripeBrowserLauncherActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseMainManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 4 invalid unit(s) of work during this build to ensure correctness.

**Comment by krizzu** [comment]
You're issue is related to Stripe, not AsyncStorage

> Error:
android:exported needs to be explicitly specified for element <activity#com.stripe.android.payments.StripeBrowserLauncherActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for android:exported when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

**Comment by AngelDev727** [comment]
Thank you for you feedback.
But I didn't get this when using targetSdkVersion 31

**Comment by AngelDev727** [comment]
I have solved this problem by add this section on AndroidManifest.xml

        <activity
            android:name="com.stripe.android.payments.StripeBrowserLauncherActivity"
            tools:replace="android:launchMode"
            android:launchMode="standard" 
            android:exported="true"
            tools:node="merge"/>

Thank you, krizzu

**Comment by krizzu** [comment]
Targeting SDK 31 requires all app component to declare explicitly `exported` property, so that's good fix
