### ISSUE TITLE
Migration doesn't work on core react native v0.60.6 to react-native-async-storage/async-storage v1.17.8

### ISSUE THREAD

**Issue by killmyrene** [react-native-async-storage/async-storage#888]
### What happened?

We're currently in the process to upgrade our app to use the core react native dependencies from v0.60.6 -> v0.69.7 and use the react-native-async-storage/async-storage v1.17.8 so naturally the new async storage will be used for storage purposes. Unfortunately the data stored doesn't get migrated over to the new storage.

I found out that the location is different between two versions. The v0.60.6 version has its storage stored in "Library/AsyncStorage.txt" while the latest version of the async/storage v1.17.8 is stored in Library/Application Support/[AppID]/RCTAsyncLocalStorage_V1/manifest.json. The current codebase doesn't handle this scenario hence why the migration doesn't work for me

<img width="570" alt="Screen Shot 2022-12-15 at 12 55 13 PM" src="https://user-images.githubusercontent.com/3467628/207933695-d8c4eec9-d78b-4c6f-aea3-3545b78377cf.png">

Thoughts on how to do this migration process? Do i need to create a custom native bridge to handle the migration myself?

I did try to use this code on react side to handle migration but the result implies that the old storage doesn't exist
```

import AsyncStorage from '@react-native-async-storage/async-storage';
import { AsyncStorage as OldAsyncStorage } from 'react-native';

OldAsyncStorage.getAllKeys().then((keys) => {
      console.log(keys); //returns empty keys
      return OldAsyncStorage.multiGet(keys)
          .then((result) => {
            console.log(result);
          });
    });

```

### Version

1.17.8

### What platforms are you seeing this issue on?

- [ ] Android
- [X] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
info Fetching system and libraries information...
System:
    OS: macOS 12.3
    CPU: (10) arm64 Apple M1 Max
    Memory: 152.81 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 19.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - /opt/homebrew/bin/npm
    Watchman: 2022.11.28.00 - /opt/homebrew/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 30, 31, 33
      Build Tools: 28.0.3, 30.0.3, 31.0.0, 33.0.1
      System Images: android-33 | Google APIs ARM 64 v8a
      Android NDK: 21.3.6528147
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8092744
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.6 => 0.60.6
npm notice 
npm notice New major version of npm available! 8.19.3 -> 9.2.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.2.0
npm notice Run npm install -g npm@9.2.0 to update!
npm notice
```

### Steps to Reproduce

1. Have the app first run under the react-native v0.60.6
2. Run app, store a key-value pair into the AsyncStorage imported from 'react-native'. Then exit the app
3. Have the same app upgrade its react-native version to 0.69.7 and include react-native-async-storage/async-storage v1.17.8
4. Run app, get AsyncStorage imported from 'react-native-async-storage/async-storage' and fetch the same key-value pair.

Expected should be to get the same key-value pair as the old version of the app

**Comment by krizzu** [comment]
Hey, the migration is in place for some time already. [Here's the code](https://github.com/react-native-async-storage/async-storage/blob/master/ios/RNCAsyncStorage.m#L284). The point is, you have to stop using AsyncStorage from `react-native`, as the migration checks when the last time the original file was used and make decision to migrate based on that (and do remove files).

Looking at [RN 0.60 code](https://github.com/facebook/react-native/blob/0.60-stable/React/Modules/RCTAsyncLocalStorage.m#L19-L20), I don't know where `AsyncStorage.txt` comes from.

**Comment by killmyrene** [comment]
Like i said in the opening ticket, we are in a process of using the latest async storage from the community package and again like i said, the migration doesn't work as its not looking for the AsyncStorage.txt. Even in that v0.60 it doesn't create the RNCAsyncLocalStorage_V1/manifest.json file. The code at the end demonstrates that it doesn't pull anything from the old data.

Its the same thing with android. v0.60 creates the files/AsyncStorage.txt in files folder while the community package uses the databases/RKStorage under the databases folder.

The additional context i can give is we use the You.I framework alongside react native, since we are heavily dependent on making the custom UI and native modules

**Comment by tido64** [comment]
As @krizzu pointed out, the AsyncStorage module in react-native@0.60 also wrote to `manifest.json`: https://github.com/facebook/react-native/blob/0.60-stable/React/Modules/RCTAsyncLocalStorage.m#L20

In fact, this filename hasn't changed since it was introduced in 0.14: https://github.com/facebook/react-native/commit/221ddd3cfeee9ac80d4a40d140699050b1402b43#diff-75bf08c717b2fbe3f38f03559729179746ed28f3a0efb202a017d51d17fae94c

Are you sure `AsyncStorage.txt` wasn't created by something else? Does this You.I framework override the destination perhaps?

**Comment by krizzu** [comment]
My point was that we have kept everything from `AsyncStorage` pre 0.60 and added migrations on top of that. 
> Its the same thing with android. v0.60 creates the files/AsyncStorage.txt in files folder while the community package uses the databases/RKStorage under the databases folder.

For Android, it was always RKStorage sqlite file, not .txt file
