### ISSUE TITLE
Task merge release generate proguard files failed

### ISSUE THREAD

**Issue by pixsolution** [react-native-async-storage/async-storage#889]
### What happened?

Hello! when I try to build apk I get the following error
![Captura de Pantalla 2022-12-21 a la(s) 2 56 14 p  m](https://user-images.githubusercontent.com/47191848/208988462-bd379139-44c4-46e2-aff4-0ba03888f303.png)
In the emulator everything works fine without errors, what could it be? the version of RN is 0.68.5

### Version

1.17.11

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
System:
  OS: macOS 12.4
  CPU: (8) arm64 Apple M1
  Memory: 158.86 MB / 8.00 GB
  Shell: 5.8.1 - /bin/zsh
 Binaries:
  Node: 16.16.0 - /usr/local/bin/node
  Yarn: 1.22.19 - ~/Desktop/carpeta sin título/SaludVitale/node_modules/.bin/yarn
  npm: 8.13.2 - /opt/homebrew/bin/npm
  Watchman: Not Found
 Managers:
  CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
 SDKs:
  iOS SDK:
   Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
  Android SDK: Not Found
 IDEs:
  Android Studio: 2021.3 AI-213.7172.25.2113.9123335
  Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
 Languages:
  Java: 17.0.1 - /usr/bin/javac
 npmPackages:
  @react-native-community/cli: Not Found
  react: 17.0.2 => 17.0.2
  react-native: 0.68.5 => 0.68.5
  react-native-macos: Not Found
 npmGlobalPackages:
  *react-native*: Not Found
pixsolution@Mac-mini-de-PixSolution SaludVitale %
```

### Steps to Reproduce

trying to generate apk

**Comment by tido64** [comment]
Hi, do you have the full build log? There's nothing in the screenshot that you provided.
