### ISSUE TITLE
getting null while using @react-native-community/async-storage' in ios

### ISSUE THREAD

**Issue by azudi001** [react-native-async-storage/async-storage#892]
### What happened?

while using getItem() in ios to get the storage value, I keep gettin "null"

### Version

1.17.11

### What platforms are you seeing this issue on?

- [ ] Android
- [X] iOS
- [X] macOS
- [ ] Windows
- [ ] web

### System Information

```true
import AsyncStorage from '@react-native-async-storage/async-storage';

export default AddtoStorage = async (name, data) => {
  let prevCart
  try {
    prevCart = await AsyncStorage.getItem(name);
    console.log("prev-cart",prevCart)
  } catch (e) {
    console.log(e);
  }
  try {
    await AsyncStorage.setItem(name, JSON.stringify([JSON.parse(prevCart), data]).flat());
  } catch (e) {
    console.log(e);
  }
};
```

### Steps to Reproduce

import AsyncStorage from '@react-native-async-storage/async-storage';

then set storage :
 try {
    await AsyncStorage.setItem(name, JSON.stringify([JSON.parse(prevCart), data]).flat());
  } catch (e) {
    console.log(e);
  }

try getting the storage:
try {
    prevCart = await AsyncStorage.getItem(name);
    console.log("prev-cart",prevCart)
  } catch (e) {
    console.log(e);
  }
  
And the output:
 LOG : null

**Comment by tido64** [comment]
> `JSON.stringify([JSON.parse(prevCart), data]).flat()`

Is this returning a valid value for you? As far as I know, there's no such thing as `flat()` on the String object.

**Comment by marouane-edghoughi** [comment]
@tido64  I'm facing the same issue with AsyncStorage.getItem(key). Here is my code:

`export const getCredentials = async () => {
    try {
        const user = await AsyncStorage.getItem('user')

        console.log(JSON.parse(user))

        if (user !== null) {
            let credentials = {}

            credentials.refreshToken = user.refreshToken
            credentials.accessToken = user.accessToken
            credentials.expirationTime = user.accessTokenExpiry

            return credentials
        } else {
            return null
        }
    } catch (error) {
        console.log('Error getting credentials: ' + error)
    }
}`

Please note that I am persisting data using Redux Persist (the latest release) and I dispatch data to redux store. I tested setting the user and getting it, it actually works but I didn't figure out what's wrong with getting the key. I'm also using the package to log out with AsyncStorage, the funniest thing is that it works, I mean removing the user with AsyncStorage.removeItem('user') but getting it is always returing null. I would appreciate any help, thanks.

**Comment by tido64** [comment]
@marouane-edghoughi: I don't know redux-persist. I can't see any issues with setting and getting values as you can see below:

```js
  useEffect(() => {
    const reproKey = "repro-891";
    AsyncStorage.getItem(reproKey)
      .then((value) => {
        if (value) {
          console.log(`AsyncStorage.getItem -> ${value.substring(0, 16)}...`);
        } else {
          console.log("AsyncStorage.getItem -> undefined");
        }
        return value;
      })
      .then((value) => {
        if (!value) {
          const chars =
            "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
          const charsLen = chars.length;
          const data = [];
          while (data.length < 8000) {
            data.push(chars.charAt(Math.floor(Math.random() * charsLen)));
          }
          const value = data.join("");

          AsyncStorage.setItem(reproKey, value);

          console.log(`AsyncStorage.setItem -> ${value.substring(0, 16)}...`);
        } else {
          AsyncStorage.removeItem(reproKey);
          console.log("AsyncStorage.removeItem");
        }
      });
  }, []);
```

Log:

```
 LOG  Running "Example" with {"rootTag":91,"initialProps":{}}
 LOG  AsyncStorage.getItem -> SVQ3Y7ECPLvE47hu...
 LOG  AsyncStorage.removeItem
 LOG  Running "Example" with {"rootTag":101,"initialProps":{}}
 LOG  AsyncStorage.getItem -> undefined
 LOG  AsyncStorage.setItem -> qDMT9RMN5exdHgD9...
 LOG  Running "Example" with {"rootTag":111,"initialProps":{}}
 LOG  AsyncStorage.getItem -> qDMT9RMN5exdHgD9...
 LOG  AsyncStorage.removeItem
 LOG  Running "Example" with {"rootTag":121,"initialProps":{}}
 LOG  AsyncStorage.getItem -> undefined
 LOG  AsyncStorage.setItem -> mDNj59FLOssvqm3D...
```

(app was restarted here)

```
 BUNDLE  ./index.js

 LOG  Running "Example" with {"rootTag":1,"initialProps":{}}
 LOG  AsyncStorage.getItem -> mDNj59FLOssvqm3D...
 LOG  AsyncStorage.removeItem
```

If you have a proper repro for this issue, please post it. Otherwise, we don't have enough information to help you.

**Comment by WahidN** [comment]
I'm also having this issue using react-native 0.71.1 and asyncStorage version 1.17.11

This is the code I use
```
import AsyncStorage from '@react-native-async-storage/async-storage';

export const Storage = {
  setValue(key: string, value: (typeof JSON.stringify.arguments)[0]) {
    return AsyncStorage.setItem(key, JSON.stringify(value));
  },

  getValue(key: string) {
    return AsyncStorage.getItem(key).then((value) => (value ? JSON.parse(value) : null));
  },

  removeValue(key: string) {
    return AsyncStorage.removeItem(key);
  },
};

```

This is what i'm getting back when logging the value from getItem
```
{ storageValue: { _h: 0, _i: 0, _j: null, _k: null } }
```

It was working before the updates

**Comment by MaximKing1** [comment]
Im also getting issues:
```js
import AsyncStorage from '@react-native-async-storage/async-storage';

export async function checkAuthConfirmation() {
  // Example to show you how i save it
  try {
    await AsyncStorage.setItem(
      '@authConfirmed',
      JSON.stringify({
        shownPopup: true,
      })
    );
  } catch (err) {
    console.error(err);
  }

  // Fetching the data
  return await AsyncStorage.getItem('@authConfirmed').then(
    (value) => JSON.parse(value) || {}
  );
}
  ```

Which produces a `null` output also on iOS.
