### ISSUE TITLE
iOS RCTAsyncLocalStorage_V1 folder still showing under Documents

### ISSUE THREAD

**Issue by AdriBee** [react-native-async-storage/async-storage#897]
### What happened?

I have been reading through the issues and I am still lost (rookie RN).
This case is only for IOS devices because in android we can save files in many other locations but in IOS it is only allowing to save files in Documents directory.

From my App, users should be able to  download json files, and I am storing these files in Documents directory,
i am allowing this in info plist so user can access and open the Downloaded files.

UIFileSharingEnabled

UISupportsDocumentBrowser

LSSupportsOpeningDocumentsInPlace

We were using an older version of async-storage, but we have updated it to the lastest (1.17.11). From what I read, looks like there is been ongoing efforts to migrate the location of the folder RCTAsyncLocalStorage_V1 ( in which all the locally stored data is there in a manifest.json file) to the Support directory. I just built the app again with the lastest version (uninstalling it from my device and re-building from scratch) and looks like the folder is still under Documents (including the manifest.json that contains confidential information). 
This allows user to see all the raw data that can be used to do some hacking or playing around with things.

Am I missing something? Do we have to change function names? 
Here is a snippet on how we are using the API:

import AsyncStorage from "@react-native-async-storage/async-storage";

export const storeData = async (key, value) => {
  try {
    const jsonValue = JSON.stringify(value);
    await AsyncStorage.setItem(key, jsonValue);
  } catch (e) {
    // saving error
    Sentry.captureException(e);
  }
};

Any help or guidance will be greatly appreciated! :) 

### Version

1.17.11

### What platforms are you seeing this issue on?

- [ ] Android
- [X] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
System:
    OS: macOS 12.6.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 32.07 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.3.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.2.0 - /usr/local/bin/npm
    Watchman: 2022.12.12.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15.1 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.5 => 0.63.5
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

react-native: 0.63.5
async-storage: 1.17.11

import AsyncStorage from "@react-native-async-storage/async-storage";

export const storeData = async (key, value) => {
  try {
    const jsonValue = JSON.stringify(value);
    await AsyncStorage.setItem(key, jsonValue);
  } catch (e) {
    // saving error
    Sentry.captureException(e);
  }
};

And this is saved on the Documents folder. I would like for it to be on the Support one so that we can use the Documents folder to allow users to access it.

**Comment by krizzu** [comment]
AS used to write to Documents folder (and current AS provided from `react-native`), but for a long time now the [migration to Application Support takes place on instance init.](https://github.com/react-native-async-storage/async-storage/blob/master/ios/RNCAsyncStorage.m#L422). Old Documents/ directories are cleared during that migration process.

If you mix this library with AS from `react-native`, then you'll see a condition race of creating a folders in Documents/ and migrating them/deleting to Application Support

**Comment by AdriBee** [comment]
Yup, but at least on my side, it was not doing the migration. I uninstalled the app on my ios device, then generated a  new build with 1.17.11, and installed the app. This brand new app did not have any folder inside Documents and it still generated the folder inside Documents. Since you mention that it takes place during init, I think the logic would have been: Check if folder exists, since it returns null (does not exist) then generate only on AS. But that has not been the case.

The patch I did was going to [this file] (https://github.com/react-native-async-storage/async-storage/blob/master/ios/RNCAsyncStorage.m#L422:~:text=//%20Get%20the,NO)%3B) and switching the NO for  a YES and the YES for a NO (on lines 435 and 442 respectively). That solved the problem and the folder is not created in Documents anymore. It is only created on AS now. 

I think I should have add that I don't want to do any sort of migration, I just want to have the Storage folder located in AS instead of Documents. The files I save in RCTAsyncLocalStorage_V1 are related to the user's session and they do not contain long-term data on them. 

Hope this helps troubleshooting, also, keep in mind I am a script kitty in RN and C.

**Comment by AdriBee** [comment]
> Yup, but at least on my side, it was not doing the migration. I uninstalled the app on my ios device, then generated a new build with 1.17.11, and installed the app. This brand new app did not have any folder inside Documents and it still generated the folder inside Documents. Since you mention that it takes place during init, I think the logic would have been: Check if folder exists, since it returns null (does not exist) then generate only on AS. But that has not been the case.
> 
> The patch I did was going to [this file](https://github.com/react-native-async-storage/async-storage/blob/master/ios/RNCAsyncStorage.m#L422:~:text=//%20Get%20the,NO) and switching the NO for a YES and the YES for a NO (on lines 435 and 442 respectively). That solved the problem and the folder is not created in Documents anymore. It is only created on AS now.
> 
> I think I should have add that I don't want to do any sort of migration, I just want to have the Storage folder located in AS instead of Documents. The files I save in RCTAsyncLocalStorage_V1 are related to the user's session and they do not contain long-term data on them.
> 
> Hope this helps troubleshooting, also, keep in mind I am a script kitty in RN and C.

Hello, what I did here does not really solve the problem since it looks like the app is unable to fins the AS folder. 

It is still not behaving as expected. The library keeps creating the V1 folder inside Documents, which ends up being accessible for the user. The folder is never cleaned up (I tried force quitting the app and getting back on, but it does not clear it). 

Any advice will be appreciated :)

**Comment by JatinBhuva** [comment]
I'm facing the same issue on version 1.19.0, any solution?

**Comment by nullmicgo** [comment]
I also have this issue , any solution ? Thanks
