### ISSUE TITLE
Cannot read property 'setItem' of undefined

### ISSUE THREAD

**Issue by ElbinBinil** [react-native-async-storage/async-storage#899]
### What happened?

I'm creating an app using Expo React Native and I setting the JWT token into the async storage but it is showing an error

```
import AsyncStorage from '@react-native-async-storage/async-storage';
const storeData = async (token: string) => {
  try {
    await AsyncStorage.setItem("@authtoken", token);
    console.log(token);
  } catch (e) {
    // saving error
    console.log(e);
  }
};

//Redux code
tokenset: (state, action) => {
      storeData(action.payload);
    },
```
### Version

1.17.3

### What platforms are you seeing this issue on?

- [x] Android
- [x] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32929.386 (Visual Studio Community 2019)
  Languages:
    Java: 18.0.2 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.2 => 0.68.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.71.1 is now available (your project is running on v0.68.2).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.71.1.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.68.2.
info To upgrade, run "react-native upgrade".
```

### Steps to Reproduce

When ever a user logs in the app should set the JWt token in the async storage but it is showing an error

**Comment by krizzu** [comment]
What kind of error you see?

**Comment by chriskoenigsfeld** [comment]
I run into the same issue. I rather use AsyncStorage from 'react-native'.
If this is the replacement of AsyncStorage of 'react-native', I really don't know what to ...

**Comment by chriskoenigsfeld** [comment]
My mistake was my import. I imported this way
import { AsyncStorage } from '@react-native-community/async-storage';
but it should be
import AsyncStorage from '@react-native-community/async-storage';

My wrong import (and maybe many users too) came from changing 'react-native' to '@react-native-community/async-storage' and pretending the rest to be the same, since the class has the same name.
