### ISSUE TITLE
Build fails with fatal error: 'RCTAsyncLocalStorage.h' file not found 

### ISSUE THREAD

**Issue by BRaymond69** [react-native-async-storage/async-storage#903]
### What happened?

Hello everyone, since fews days I have an error when it s come to build my ios application with expo (the android application works correctly), during the fastlane build I have #import <React/RCTAsyncLocalStorage.h> | ^ 'React/RCTAsyncLocalStorage.h' file not found inside EXDevLauncherController.m
I tryied to follow the troubleshoot part of the asynclocalstorage documentation but I still have the same error.

<img width="792" alt="image" src="https://user-images.githubusercontent.com/61524541/215280171-886d060f-e7ca-4832-bd29-39bbe9959965.png">

### Version

~1.17.3

### What platforms are you seeing this issue on?

- [ ] Android
- [X] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M2
    Memory: 221.30 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: 2023.01.16.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /Users/benjaminraymond/.jenv/shims/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.1 => 0.71.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

I don't for step to reproduce it.
It was working before and after a update of react native it's not working anymore.

**Comment by tido64** [comment]
Hi, `React/RCTAsyncLocalStorage.h` has been deprecated from react-native for quite some time now. If you're having issues with your Expo project, please post a question in the Expo forum. This has nothing to do with AsyncStorage.

**Comment by Yamini0** [comment]
Hey @BRaymond69 Did u find solution for this error im facing similar kind of problem with my expo project.
expo: 47
@react-native-async-storage/async-storage: ~1.17.3

**Comment by Yamini0** [comment]
@BRaymond69 why https://docs.expo.dev/versions/latest/sdk/securestore/ ?

**Comment by BRaymond69** [comment]
Because I wanted just to store language of the phone, so securestore is easier it's the same, than asynclocalstorage.
