### ISSUE TITLE
This library has an implicit dependency on @react-native-community/async-storage

### ISSUE THREAD

**Issue by abejfehr** [react-native-async-storage/async-storage#904]
### What happened?

I have a project that has @react-native-async-storage/async-storage (this library) as a transitive dependency. It also had @react-native-community/async-storage in the package.json, but that wasn't actually directly used anywhere.

Upon removing @react-native-community/async-storage from the package.json, I received [this error](https://github.com/react-native-async-storage/async-storage/blob/master/src/AsyncStorage.native.ts#L22) stating the `RNCAsyncStorage` didn't exist.

Am I correct in saying that this library implicitly depends on `@react-native-community/async-storage`? I wish this relationship was made more clear.

### Version

Here's the excerpt from the yarn.lock that shows both package versions:

```
"@react-native-async-storage/async-storage@^1.13.4", "@react-native-async-storage/async-storage@^1.15.15", "@react-native-async-storage/async-storage@^1.15.17":
  version "1.17.11"
  resolved "https://registry.yarnpkg.com/@react-native-async-storage/async-storage/-/async-storage-1.17.11.tgz#7ec329c1b9f610e344602e806b04d7c928a2341d"
  integrity sha512-bzs45n5HNcDq6mxXnSsOHysZWn1SbbebNxldBXCQs8dSvF8Aor9KCdpm+TpnnGweK3R6diqsT8lFhX77VX0NFw==
  dependencies:
    merge-options "^3.0.4"

"@react-native-community/async-storage@^1.12.1":
  version "1.12.1"
  resolved "https://registry.yarnpkg.com/@react-native-community/async-storage/-/async-storage-1.12.1.tgz#25f821b4f6b13abe005ad67e47c6f1cee9f27b24"
  integrity sha512-70WGaH3PKYASi4BThuEEKMkyAgE9k7VytBqmgPRx3MzJx9/MkspwqJGmn3QLCgHLIFUgF1pit2mWICbRJ3T3lg==
  dependencies:
    deep-assign "^3.0.0"
```

### What platforms are you seeing this issue on?

- [X] Android
- [X] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
N/A
```

### Steps to Reproduce

1. Create a react-native app
2. Install `@segment/sovran-react-native` or a similar package that has this as a transitive dependency
3. Install `@react-native-community/async-storage`
4. Uninstall `@react-native-community/async-storage`
5. Observe that the app breaks because this package fails to find `RNCAsyncStorage`

**Comment by tido64** [comment]
Hi, you need to file an issue with `@segment/sovran-react-native`. This is not an AsyncStorage issue.

**Comment by abejfehr** [comment]
Why would the issue be with that package? This is the package that's making use of the `RNCAsyncStorage` native module 🤔 can we reopen this and have a discussion about it?

**Comment by abejfehr** [comment]
Just to be clear: this package makes use of `RNCAsyncStorage`, which comes from @react-native-community/async-storage.

Is this package a _fork_ of that package? If it's dependent on @react-native-community/async-storage, why isn't it marked as a dependency in package.json? There are unanswered questions here

**Comment by abejfehr** [comment]
I see that this project also registers a native module called RNCAsyncStorage, I think that's the issue.

This package has a namespace conflict with the real @react-native-community/async-storage package. I think the native module in this package should be renamed so it's not RNCAsyncStorage

**Comment by abejfehr** [comment]
Okay, I'm now seeing that github.com/react-native-community/async-storage redirects to here, so it's just that this package was renamed and is _not_ a fork

**Comment by abejfehr** [comment]
Okay, I see now that `@react-native-community/async-storage` has a deprecation notice [here](https://www.npmjs.com/package/@react-native-community/async-storage) and says to use this package instead. It's all clear now, thank you.
