### ISSUE TITLE
Include information on the storage implemention

### ISSUE THREAD

**Issue by jackbridger** [react-native-async-storage/async-storage#905]
### Proposal

Thanks for your hard work on the project.
I was curious what the implementation looks like under the hood in Android and iOS and I couldn't find the info on the readme or docs (I might just have missed it).
I think this might be a nice addition to help us understand at a glance how this great package works. 
If this isn't helpful please feel free to close!

### Implementation Details

It could include something like the below:

Where your Redux store is stored:
* Android - SQLite
* iOS - small values in serialized dictionary and larger values in separate files
* Web - window.localStorage
* MacOS - I couldn't find the details
* Windows - I couldn't find the details

**Comment by krizzu** [comment]
I like the idea - we could add a section in the documentation about it.

And to fill up some gaps:

```diff
 Where your Redux store is stored:
 
Android - SQLite
+ iOS - small values (not exceeding 1024 characters) are serialized and stored in a common `manifest.json` file, while larger values are stored in individual, dedicated files (named as MD5 hashed `key`)
Web - window.localStorage
+ MacOS - Same as iOS
+ Windows - SQLite
```

**Comment by jackbridger** [comment]
Great, glad you like it!

I can make a PR for this early next week
