### ISSUE TITLE
Execution failed for task ':react-native-async-storage_async-storage:extractReleaseAnnotations

### ISSUE THREAD

**Issue by veeyka** [react-native-async-storage/async-storage#906]
### What happened?

hi . after android -> ./gradlew assembleRelease  - error 

`> Task :react-native-async-storage_async-storage:extractReleaseAnnotations FAILED
w: Detected multiple Kotlin daemon sessions at build\kotlin\sessions

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-async-storage_async-storage:extractReleaseAnnotations'.
> Could not resolve all files for configuration ':react-native-async-storage_async-storage:detachedConfiguration2'.
   > Could not find lint-gradle-30.2.1.jar (com.android.tools.lint:lint-gradle:30.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle/30.2.1/lint-gradle-30.2.1.jar
   > Could not find lint-30.2.1.jar (com.android.tools.lint:lint:30.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint/30.2.1/lint-30.2.1.jar
   > Could not find lint-checks-30.2.1.jar (com.android.tools.lint:lint-checks:30.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-checks/30.2.1/lint-checks-30.2.1.jar
   > Could not find lint-api-30.2.1.jar (com.android.tools.lint:lint-api:30.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-api/30.2.1/lint-api-30.2.1.jar
   > Could not find intellij-core-30.2.1.jar (com.android.tools.external.com-intellij:intellij-core:30.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/intellij-core/30.2.1/intellij-core-30.2.1.jar
   > Could not find kotlin-compiler-30.2.1.jar (com.android.tools.external.com-intellij:kotlin-compiler:30.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/kotlin-compiler/30.2.1/kotlin-compiler-30.2.1.jar
   > Could not find uast-30.2.1.jar (com.android.tools.external.org-jetbrains:uast:30.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/external/org-jetbrains/uast/30.2.1/uast-30.2.1.jar
   > Could not find aapt2-proto-7.0.0-beta04-7396180.jar (com.android.tools.build:aapt2-proto:7.0.0-beta04-7396180).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2-proto/7.0.0-beta04-7396180/aapt2-proto-7.0.0-beta04-7396180.jar`

i worked a few days ago well . but now i got error .

 "dependencies": {
    "@epubjs-react-native/core": "^1.1.0",
    "@epubjs-react-native/file-system": "^1.0.0",
    "@react-native-async-storage/async-storage": "^1.17.11",
    "@react-native-community/netinfo": "^9.3.6",
    "@react-native-community/slider": "^4.4.0",
    "@react-navigation/drawer": "^6.5.1",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.1",
    "deprecated-react-native-prop-types": "^2.3.0",
    "peerjs": "^1.4.7",
    "react": "18.1.0",
    "react-native": "0.70.6",
    "react-native-fast-image": "^8.6.3",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "^2.1.1",
    "react-native-incall-manager": "^4.0.1",
    "react-native-indicators": "^0.17.0",
    "react-native-peerjs": "^1.0.4",
    "react-native-reanimated": "^2.13.0",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.18.2",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-sound": "^0.11.2",
    "react-native-vector-icons": "^9.2.0",
    "react-native-webrtc": "^106.0.4",
    "react-native-webview": "^11.15.0",
    "react-redux": "^8.0.5",
    "redux": "^4.2.0",
    "redux-thunk": "^2.4.2",
    "socket.io-client": "^4.5.4"
  },

and  my android build.gradle

`
def REACT_NATIVE_VERSION = new File(['node', '--print',"JSON.parse(require('fs').readFileSync(require.resolve('react-native/package.json'), 'utf-8')).version"].execute(null, rootDir).text.trim())

buildscript {
    ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        kotlinVersion = "1.6.0"
        if (System.properties['os.arch'] == "aarch64") {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            ndkVersion = "24.0.8215888"
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = "21.4.7075529"
        }
    }
    repositories {

        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.2.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("de.undercouch:gradle-download-task:5.0.1")

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    configurations.all {
        resolutionStrategy {
            force "com.facebook.react:react-native:" + REACT_NATIVE_VERSION
        }
    }
    repositories {

        mavenCentral()
        exclusiveContent {
            filter {
                includeGroup "com.facebook.react"
            }
            forRepository {
                maven {
                    url "$rootDir/../node_modules/react-native/android"
                }
            }
        }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }
        google()
        maven { url 'https://www.jitpack.io' }
    }
}
`

### Version

1.17.11

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
--
```

### Steps to Reproduce

idk

**Comment by krizzu** [comment]
Seems like you miss sdk platform tools on your system? You can try to install it via Android Studio or CLI:

(Since you target API 31):

[Setup via Android Studio](https://developer.android.com/about/versions/12/setup-sdk)

> Within Android Studio, you can install the Android 12 SDK as follows:
> 1. Click Tools > SDK Manager.
> 2. In the SDK Platforms tab, select Android 12.
> 3. In the SDK Tools tab, select Android SDK Build-Tools 31.
> 4. Click OK to install the SDK.

[Setup via CLI](https://developer.android.com/studio/command-line/sdkmanager):
Once you get `sdkmanager` installed, you can install tools with:
```sh
sdkmanager "platform-tools" "platforms;android-33"
```

Hope that helps

**Comment by veeyka** [comment]
> Seems like you miss sdk platform tools on your system? You can try to install it via Android Studio or CLI:
> 
> (Since you target API 31):
> 
> [Setup via Android Studio](https://developer.android.com/about/versions/12/setup-sdk)
> 
> > Within Android Studio, you can install the Android 12 SDK as follows:
> > 
> > 1. Click Tools > SDK Manager.
> > 2. In the SDK Platforms tab, select Android 12.
> > 3. In the SDK Tools tab, select Android SDK Build-Tools 31.
> > 4. Click OK to install the SDK.
> 
> [Setup via CLI](https://developer.android.com/studio/command-line/sdkmanager): Once you get `sdkmanager` installed, you can install tools with:
> 
> ```shell
> sdkmanager "platform-tools" "platforms;android-33"
> ```
> 
> Hope that helps

thanks dude it worked .
