### ISSUE TITLE
A problem occurred configuring project ':@react-native-async-storage_async-storage'

### ISSUE THREAD

**Issue by footios** [react-native-async-storage/async-storage#908]
### What happened?

This is the full error message:

A problem occurred configuring project ':@react-native-async-storage_async-storage'. com.android.builder.errors.EvalIssueException: defaultConfig contains custom BuildConfig fields, but the feature is disabled. To enable the feature, add the following to your module-level build.gradle: android.buildFeatures.buildConfig true

### Version

^1.17.11

### What platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [X] macOS
- [ ] Windows
- [ ] web

### System Information

```true
System:
    OS: macOS 12.6.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 159.66 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
    Watchman: 2022.09.19.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 19.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.1 => 0.66.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

`react-native run-android`

**Comment by krizzu** [comment]
Enabling `buildConfig` in your `app/build.gradle` file should do the trick:

```
android {
    buildFeatures {
        buildConfig = true
    }
}
```

**Comment by footios** [comment]
Thus, `android.buildFeatures.buildConfig true` is translated to what you suggested. 
At least I've learned something! Thank you!
But unfortunately, the problem remains.

**Comment by footios** [comment]
Lastly, I changed the Gradle Version and now I get another error. Then I updated the package that was throwing the error, and now it builds, but it crashes on load.

**Comment by footios** [comment]
I've changed Android Gradle Plugin Version to 7.4.1 and Gradle Version to 7.6. For possible combinations, check [here](https://developer.android.com/studio/releases/gradle-plugin#groovy)
I updated Android Studio and used JDK 11.
Clean project and tried again and now it works.
