### ISSUE TITLE
react-native-community/async-storage@1.3.0 npm ERR! Found: react-native@0.59.3

### ISSUE THREAD

**Issue by maxi-89** [react-native-async-storage/async-storage#916]
### What happened?

hi everyone! my name is maxi.  i had a bug after make npm install...
here you have the track of the error:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @react-native-community/async-storage@1.3.0
npm ERR! Found: react-native@0.59.3
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.59.3" from the root project
npm ERR!   peer react-native@"^0.59.0" from @react-native-community/cli@1.6.0
npm ERR!   node_modules/@react-native-community/cli
npm ERR!     @react-native-community/cli@"^1.2.1" from react-native@0.59.3
npm ERR!   31 more (@react-navigation/native, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.57.0" from @react-native-community/async-storage@1.3.0
npm ERR! node_modules/@react-native-community/async-storage
npm ERR!   @react-native-community/async-storage@"^1.3.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react-native@0.57.8
npm ERR! node_modules/react-native
npm ERR!   peer react-native@"^0.57.0" from @react-native-community/async-storage@1.3.0
npm ERR!   node_modules/@react-native-community/async-storage
npm ERR!     @react-native-community/async-storage@"^1.3.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/maximiliano/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/maximiliano/.npm/_logs/2023-02-08T15_34_34_706Z-debug-0.log

### Version

1.3.0

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
Linux: Ubuntu
IDE: VSCODE AND ANDROID STUDIO
PACKAGE.JSON:
{
  "name": "mobile",
  "version": "1.2.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "android": "react-native run-android",
    "android_release_test": "react-native run-android --variant=release",
    "ios": "react-native run-ios",
    "test": "jest",
    "coverage": "jest --coverage",
    "eslint": "eslint App.js ./app/ __tests__/",
    "pre-assemble": "react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/",
    "android:debug": "fastlane android assemble_debug",
    "android:release": "fastlane android assemble_release",
    "deploy:internal": "fastlane android deploy_internal --verbose",
    "promote:alpha": "fastlane android promote_internal_to_alpha",
    "promote:beta": "fastlane android promote_alpha_to_beta",
    "promote:production": "fastlane android promote_beta_to_production",
    "jscpd": "jscpd",
    "link": "react-native link",
    "screenshots": "./scripts/screenshots.sh"
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.3.0",
    "axios": "^0.18.0",
    "buffer": "^5.4.2",
    "moment": "^2.24.0",
    "react": "16.8.3",
    "react-native": "0.59.3",
    "react-native-document-picker": "^3.2.4",
    "react-native-elements": "^1.1.0",
    "react-native-firebase": "^5.4.2",
    "react-native-flash-message": "^0.1.13",
    "react-native-fs": "^2.14.1",
    "react-native-gesture-handler": "^1.1.0",
    "react-native-linear-gradient": "^2.5.4",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-modal": "^11.0.1",
    "react-native-paper": "^2.16.0",
    "react-native-progress": "^3.6.0",
    "react-native-reanimated": "^1.1.0",
    "react-native-sectioned-multi-select": "^0.7.1",
    "react-native-sentry": "^0.42.0",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "^9.6.2",
    "react-native-svg-transformer": "^0.13.0",
    "react-native-swipeable": "^0.6.0",
    "react-native-vector-icons": "^6.4.2",
    "react-navigation": "^3.6.1",
    "react-navigation-animated-switch": "^0.2.1",
    "react-navigation-material-bottom-tabs": "^1.0.0",
    "react-navigation-transitions": "^1.0.10",
    "react-redux": "^6.0.1",
    "redux": "^4.0.1",
    "validate.js": "^0.12.0"
  },
  "devDependencies": {
    "@babel/core": "^7.4.3",
    "@babel/runtime": "^7.4.3",
    "babel-eslint": "^10.0.1",
    "babel-jest": "^24.7.1",
    "eslint": "^5.16.0",
    "eslint-plugin-jest": "^22.4.1",
    "eslint-plugin-react": "^7.12.4",
    "faker": "^4.1.0",
    "jest": "^24.7.1",
    "jest-sonar-reporter": "^2.0.0",
    "jscpd": "^0.6.22",
    "metro-react-native-babel-preset": "^0.53.1",
    "nock": "^10.0.6",
    "prop-types": "^15.7.2",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "coverageReporters": [
      "lcov",
      "text"
    ],
    "preset": "react-native",
    "testPathIgnorePatterns": [
      "/__tests__/support/"
    ],
    "transformIgnorePatterns": [
      "node_modules/(?!(@react-native-community|react-native))"
    ]
  },
  "rnpm": {
    "assets": [
      "./app/assets/fonts/"
    ]
  }
```

### Steps to Reproduce

npm i

**Comment by tido64** [comment]
The error message is quite clear what's going on here:

- You're using `react-native` 0.59
- `@react-native-community/async-storage` 1.3.0 requires `react-native` ^0.57

npm install can't resolve `react-native` because the version numbers conflict. If you bump `@react-native-community/async-storage` to 1.6.2, I think this should be resolved.

In any case, this has nothing to do with AsyncStorage so I'm closing the issue.
