### ISSUE TITLE
iOS is always restoring data after reinstalling app

### ISSUE THREAD

**Issue by yamila-fraiman** [react-native-async-storage/async-storage#924]
### What happened?

I'm using redux with asyncstorage and every time I Uninstall an reinstall my application, data is being restored. I think it wasn't happening some months ago. I tried forcing <key>RCTAsyncStorageExcludeFromBackup</key> to true and cleared data from icloud. Data is always restored and don't have any clue about how to install the app without information 

### Version

1.17.1

### What platforms are you seeing this issue on?

- [ ] Android
- [X] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
1.17.1
```

### Steps to Reproduce

Save data to asyncstorage
Uninstall app
Install app
Data already available

**Comment by raz-manoa** [comment]
+1

**Comment by gunwooa** [comment]
Not resolved?
