### ISSUE TITLE
Support for react native's new architecture with Turbo Modules

### ISSUE THREAD

**Issue by BraveEvidence** [react-native-async-storage/async-storage#926]
### Proposal

Meta recommends to upgrade all third party libs to Turbo Modules to improve performance 

### Alternatives

https://github.com/BraveEvidence/StoringKeyValuePairInReactNative2023WithNewArchitectureTurboModules/tree/main

### Additional Context

I have managed to get it working with Preferences Datastore and Userdefaults. Check this https://github.com/BraveEvidence/StoringKeyValuePairInReactNative2023WithNewArchitectureTurboModules/tree/main, https://www.youtube.com/watch?v=n6vfCn16A00 and https://www.youtube.com/watch?v=iL-o8IJhwSQ

**Comment by tido64** [comment]
Sorry, I don't see how this helps bringing TM support to AsyncStorage. Closing.
