### ISSUE TITLE
[expo] Could not resolve dependency react 18

### ISSUE THREAD

**Issue by Vitor-SO** [react-native-async-storage/async-storage#928]
### What happened?

› Installing 1 SDK 47.0.0 compatible native module using npm
> npm install
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @react-aria/tabs@3.0.0-alpha.2
npm WARN Found: react@18.1.0
npm WARN node_modules/react
npm WARN   react@"18.1.0" from the root project
npm WARN   79 more (@react-aria/checkbox, @react-aria/focus, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || ^17.0.0-rc.1" from @react-aria/tabs@3.0.0-alpha.2
npm WARN node_modules/@react-native-aria/tabs/node_modules/@react-aria/tabs
npm WARN   @react-aria/tabs@"3.0.0-alpha.2" from @react-native-aria/tabs@0.2.8
npm WARN   node_modules/@react-native-aria/tabs
npm WARN
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || ^17.0.0-rc.1" from @react-aria/tabs@3.0.0-alpha.2
npm WARN   node_modules/@react-native-aria/tabs/node_modules/@react-aria/tabs
npm WARN     @react-aria/tabs@"3.0.0-alpha.2" from @react-native-aria/tabs@0.2.8
npm WARN     node_modules/@react-native-aria/tabs
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @react-stately/tabs@3.0.0-alpha.1
npm WARN Found: react@18.1.0
npm WARN node_modules/react
npm WARN   react@"18.1.0" from the root project
npm WARN   79 more (@react-aria/checkbox, @react-aria/focus, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || ^17.0.0-rc.1" from @react-stately/tabs@3.0.0-alpha.1
npm WARN node_modules/@react-native-aria/tabs/node_modules/@react-stately/tabs
npm WARN   @react-stately/tabs@"3.0.0-alpha.1" from @react-native-aria/tabs@0.2.8
npm WARN   node_modules/@react-native-aria/tabs
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || ^17.0.0-rc.1" from @react-stately/tabs@3.0.0-alpha.1
npm WARN   node_modules/@react-native-aria/tabs/node_modules/@react-stately/tabs
npm WARN     @react-stately/tabs@"3.0.0-alpha.1" from @react-native-aria/tabs@0.2.8
npm WARN     node_modules/@react-native-aria/tabs
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @react-types/tabs@3.0.0-alpha.2
npm WARN Found: react@18.1.0
npm WARN node_modules/react
npm WARN   react@"18.1.0" from the root project
npm WARN   79 more (@react-aria/checkbox, @react-aria/focus, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || ^17.0.0-rc.1" from @react-types/tabs@3.0.0-alpha.2
npm WARN node_modules/@react-native-aria/tabs/node_modules/@react-types/tabs
npm WARN   @react-types/tabs@"3.0.0-alpha.2" from @react-native-aria/tabs@0.2.8
npm WARN   node_modules/@react-native-aria/tabs
npm WARN   3 more (@react-aria/tabs, @react-stately/tabs, @react-stately/tabs)
npm WARN
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || ^17.0.0-rc.1" from @react-types/tabs@3.0.0-alpha.2
npm WARN   node_modules/@react-native-aria/tabs/node_modules/@react-types/tabs
npm WARN     @react-types/tabs@"3.0.0-alpha.2" from @react-native-aria/tabs@0.2.8
npm WARN     node_modules/@react-native-aria/tabs
npm WARN     3 more (@react-aria/tabs, @react-stately/tabs, @react-stately/tabs)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @react-stately/checkbox@3.0.3
npm WARN Found: react@18.1.0
npm WARN node_modules/react
npm WARN   react@"18.1.0" from the root project
npm WARN   79 more (@react-aria/checkbox, @react-aria/focus, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || ^17.0.0-rc.1" from @react-stately/checkbox@3.0.3
npm WARN node_modules/native-base/node_modules/@react-stately/checkbox
npm WARN   @react-stately/checkbox@"3.0.3" from native-base@3.4.25
npm WARN   node_modules/native-base
npm WARN
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || ^17.0.0-rc.1" from @react-stately/checkbox@3.0.3
npm WARN   node_modules/native-base/node_modules/@react-stately/checkbox
npm WARN     @react-stately/checkbox@"3.0.3" from native-base@3.4.25
npm WARN     node_modules/native-base
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @react-stately/collections@3.3.0
npm WARN Found: react@18.1.0
npm WARN node_modules/react
npm WARN   react@"18.1.0" from the root project
npm WARN   79 more (@react-aria/checkbox, @react-aria/focus, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || ^17.0.0-rc.1" from @react-stately/collections@3.3.0
npm WARN node_modules/native-base/node_modules/@react-stately/collections
npm WARN   @react-stately/collections@"3.3.0" from native-base@3.4.25
npm WARN   node_modules/native-base
npm WARN
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || ^17.0.0-rc.1" from @react-stately/collections@3.3.0
npm WARN   node_modules/native-base/node_modules/@react-stately/collections
npm WARN     @react-stately/collections@"3.3.0" from native-base@3.4.25
npm WARN     node_modules/native-base
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @react-stately/combobox@3.0.0-alpha.1
npm WARN Found: react@18.1.0
npm WARN node_modules/react
npm WARN   react@"18.1.0" from the root project
npm WARN   79 more (@react-aria/checkbox, @react-aria/focus, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || ^17.0.0-rc.1" from @react-stately/combobox@3.0.0-alpha.1
npm WARN node_modules/native-base/node_modules/@react-stately/combobox
npm WARN   @react-stately/combobox@"3.0.0-alpha.1" from native-base@3.4.25
npm WARN   node_modules/native-base
npm WARN
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || ^17.0.0-rc.1" from @react-stately/combobox@3.0.0-alpha.1
npm WARN   node_modules/native-base/node_modules/@react-stately/combobox
npm WARN     @react-stately/combobox@"3.0.0-alpha.1" from native-base@3.4.25
npm WARN     node_modules/native-base
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @react-stately/radio@3.2.1
npm WARN Found: react@18.1.0
npm WARN node_modules/react
npm WARN   react@"18.1.0" from the root project
npm WARN   79 more (@react-aria/checkbox, @react-aria/focus, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || ^17.0.0-rc.1" from @react-stately/radio@3.2.1
npm WARN node_modules/native-base/node_modules/@react-stately/radio
npm WARN   @react-stately/radio@"3.2.1" from native-base@3.4.25
npm WARN   node_modules/native-base
npm WARN
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || ^17.0.0-rc.1" from @react-stately/radio@3.2.1
npm WARN   node_modules/native-base/node_modules/@react-stately/radio
npm WARN     @react-stately/radio@"3.2.1" from native-base@3.4.25
npm WARN     node_modules/native-base
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @react-stately/slider@3.0.1
npm WARN Found: react@18.1.0
npm WARN node_modules/react
npm WARN   react@"18.1.0" from the root project
npm WARN   79 more (@react-aria/checkbox, @react-aria/focus, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || ^17.0.0-rc.1" from @react-stately/slider@3.0.1
npm WARN node_modules/native-base/node_modules/@react-stately/slider
npm WARN   @react-stately/slider@"3.0.1" from native-base@3.4.25
npm WARN   node_modules/native-base
npm WARN
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || ^17.0.0-rc.1" from @react-stately/slider@3.0.1
npm WARN   node_modules/native-base/node_modules/@react-stately/slider
npm WARN     @react-stately/slider@"3.0.1" from native-base@3.4.25
npm WARN     node_modules/native-base
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @react-stately/tabs@3.0.0-alpha.1
npm WARN Found: react@18.1.0
npm WARN node_modules/react
npm WARN   react@"18.1.0" from the root project
npm WARN   79 more (@react-aria/checkbox, @react-aria/focus, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || ^17.0.0-rc.1" from @react-stately/tabs@3.0.0-alpha.1
npm WARN node_modules/native-base/node_modules/@react-stately/tabs
npm WARN   @react-stately/tabs@"3.0.0-alpha.1" from native-base@3.4.25
npm WARN   node_modules/native-base
npm WARN
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || ^17.0.0-rc.1" from @react-stately/tabs@3.0.0-alpha.1
npm WARN   node_modules/native-base/node_modules/@react-stately/tabs
npm WARN     @react-stately/tabs@"3.0.0-alpha.1" from native-base@3.4.25
npm WARN     node_modules/native-base
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @react-stately/toggle@3.2.1
npm WARN Found: react@18.1.0
npm WARN node_modules/react
npm WARN   react@"18.1.0" from the root project
npm WARN   79 more (@react-aria/checkbox, @react-aria/focus, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || ^17.0.0-rc.1" from @react-stately/toggle@3.2.1
npm WARN node_modules/native-base/node_modules/@react-stately/toggle
npm WARN   @react-stately/toggle@"3.2.1" from native-base@3.4.25
npm WARN   node_modules/native-base
npm WARN
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || ^17.0.0-rc.1" from @react-stately/toggle@3.2.1
npm WARN   node_modules/native-base/node_modules/@react-stately/toggle
npm WARN     @react-stately/toggle@"3.2.1" from native-base@3.4.25
npm WARN     node_modules/native-base
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @react-stately/tabs@3.0.0-alpha.0
npm WARN Found: react@18.1.0
npm WARN node_modules/react
npm WARN   react@"18.1.0" from the root project
npm WARN   79 more (@react-aria/checkbox, @react-aria/focus, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || ^17.0.0-rc.1" from @react-stately/tabs@3.0.0-alpha.0
npm WARN node_modules/@react-native-aria/tabs/node_modules/@react-aria/tabs/node_modules/@react-stately/tabs
npm WARN   @react-stately/tabs@"3.0.0-alpha.0" from @react-aria/tabs@3.0.0-alpha.2
npm WARN   node_modules/@react-native-aria/tabs/node_modules/@react-aria/tabs
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || ^17.0.0-rc.1" from @react-stately/tabs@3.0.0-alpha.0
npm WARN   node_modules/@react-native-aria/tabs/node_modules/@react-aria/tabs/node_modules/@react-stately/tabs
npm WARN     @react-stately/tabs@"3.0.0-alpha.0" from @react-aria/tabs@3.0.0-alpha.2
npm WARN     node_modules/@react-native-aria/tabs/node_modules/@react-aria/tabs
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @react-types/combobox@3.0.0-alpha.1
npm WARN Found: react@18.1.0
npm WARN node_modules/react
npm WARN   react@"18.1.0" from the root project
npm WARN   79 more (@react-aria/checkbox, @react-aria/focus, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || ^17.0.0-rc.1" from @react-types/combobox@3.0.0-alpha.1
npm WARN node_modules/native-base/node_modules/@react-stately/combobox/node_modules/@react-types/combobox
npm WARN   @react-types/combobox@"3.0.0-alpha.1" from @react-stately/combobox@3.0.0-alpha.1
npm WARN   node_modules/native-base/node_modules/@react-stately/combobox
npm WARN
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || ^17.0.0-rc.1" from @react-types/combobox@3.0.0-alpha.1
npm WARN   node_modules/native-base/node_modules/@react-stately/combobox/node_modules/@react-types/combobox
npm WARN     @react-types/combobox@"3.0.0-alpha.1" from @react-stately/combobox@3.0.0-alpha.1
npm WARN     node_modules/native-base/node_modules/@react-stately/combobox
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @react-types/tabs@3.0.0-alpha.2
npm WARN Found: react@18.1.0
npm WARN node_modules/react
npm WARN   react@"18.1.0" from the root project
npm WARN   79 more (@react-aria/checkbox, @react-aria/focus, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0 || ^17.0.0-rc.1" from @react-types/tabs@3.0.0-alpha.2
npm WARN node_modules/native-base/node_modules/@react-stately/tabs/node_modules/@react-types/tabs
npm WARN   @react-types/tabs@"3.0.0-alpha.2" from @react-stately/tabs@3.0.0-alpha.1
npm WARN   node_modules/native-base/node_modules/@react-stately/tabs
npm WARN
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0 || ^17.0.0-rc.1" from @react-types/tabs@3.0.0-alpha.2
npm WARN   node_modules/native-base/node_modules/@react-stately/tabs/node_modules/@react-types/tabs
npm WARN     @react-types/tabs@"3.0.0-alpha.2" from @react-stately/tabs@3.0.0-alpha.1
npm WARN     node_modules/native-base/node_modules/@react-stately/tabs

### Version

1.17.3

### What platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
System:
    OS: Windows 10 10.0.22621
 Binaries:
    Node: 19.7.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CM
npmPackages:
    react: 18.1.0 => 18.1.0
    react-native: 0.70.5 => 0.70.5
```

### Steps to Reproduce

npx expo install @react-native-async-storage/async-storage

**Comment by tido64** [comment]
Hi @Vitor-SO, sorry you hit this issue. From what I can see in the logs you provided, it doesn't look like it is related to AsyncStorage. For one, `@react-native-async-storage/async-storage` is not mentioned in the logs. Second, AsyncStorage doesn't have a dependency on `react`. It has a **dev** dependency on `react` for development purposes only, i.e. it only gets installed if you're working within this repository.

What I do see in the logs is that a number of dependencies, like `@react-stately/toggle`, require `react@17.0.2` while you require `react@18.1.0` in the `package.json`. npm is outputting warnings because it cannot reconcile this. If I'm not mistaken, npm also outputs how you can bypass this check.

I hope you can figure this. I will close this issue as it's not related.
