### ISSUE TITLE
Getting AppStore Connect Operation Error because of isPassthrough, removeValuesForKeys:completion:

### ISSUE THREAD

**Issue by iam-rohid** [react-native-async-storage/async-storage#947]
### What happened?

<img width="800" alt="Screenshot 2023-03-17 at 11 36 27 AM" src="https://user-images.githubusercontent.com/60325485/225830687-5071ded1-af9e-44e2-aaaf-c97f3cf8d4c7.png">

## Error Title: 
App Store Connect Operation Error
## Error Message
The app references non-public selectors in Payload/MyApp.app/MyApp: getAuthorizationStatus:, isPassthrough, removeValuesForKeys:completion:

Seems like this package is using this selector 'isPassthrough' and this is causing the error. 

### Version

1.17.11

### What platforms are you seeing this issue on?

- [ ] Android
- [X] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 71.03 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    Watchman: 2023.03.06.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 30, 31, 33, 33
      Build Tools: 30.0.3, 33.0.0, 33.0.2, 34.0.0
      System Images: android-UpsideDownCake-ext5 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.4 => 0.71.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

This will happen on Xcode build

**Comment by krizzu** [comment]
From experience (https://github.com/react-native-async-storage/async-storage/issues/866 and https://github.com/react-native-async-storage/async-storage/discussions/804) this is not blocking from App being accepted. AsyncStorage just happens to use the same selector names as iOS internal ones and I believe it's being caught by automatic check as a warning.

**Comment by krizzu** [comment]
The best bet is to report back to Apple verification that no internal code is used
