### ISSUE TITLE
A problem occured configuring project':react-native-async-storage

### ISSUE THREAD

**Issue by Akintunji** [react-native-async-storage/async-storage#951]
### What happened?

I saw A problem occured configuring project '':react-native-async-storage_async-storage,Coud not resolve all files for configuration '':react-native-async-storage_async-storage:classpath'.
Could not download kotlin -gradle-plug-1. 8.10-gradle75.jar(org. jetbrains.kotlin:kotlin-gradle-plugin:1.8.10)
  React :18.1.0
React-native:"0.70.6
React-native-async-storage/async-storage;"^1.18.1" 

### Version

1.18.1

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
OS:windows 10 10.0.19045
CPU:(2)×64 Pentium(R) Dual-Core CPU T4200@2.00GHZ
Memory:326.26MB/3.93GB
Binaries:
Node:16.14.2- C:\Program Files\nodejs\node.EXE
Yarn:Not found
npm:9.6.0- C:\Program Files\nodejs\npm.CMD
Watchman:Not found
SDKS:
Android SDK:
API level:30,31,32,33
Build Tools:30.0.0,30.0.0.2,30.0.3,31.0.0,
System Images:android-28|Google APIs intel ×86 Atom, android-29|Google Apis intel×86 Atom,android-31|Intel×86 Atom_64
Windows
```

### Steps to Reproduce

After asychronous storage installation, Run gradlew build, (or clean)The error shows up.

**Comment by krizzu** [comment]
Seems like a temporary download issue?

**Comment by Akintunji** [comment]
@Krizzu it still persist even with gradlew clean.

**Comment by krizzu** [comment]
Can you post full error message? It typically says why it fails (network issue or artifact cannot be found within given maven repositories)

**Comment by Akintunji** [comment]
Seems like a temporary download issue?

Nope it still persits.

**Comment by Sotatek-HieuDuong** [comment]
@Akintunji Any updates?

**Comment by krizzu** [comment]
I quickly tried to run a new RN 0.70 project and it works just fine. Maybe share some of your Gradle config, might be the case of your project-specific things blocking it

**Comment by Akintunji** [comment]
> @Akintunji Any updates?
Appologies my system crashed,As soon as it is up,I will come with update,Appologies!.

**Comment by Sotatek-HieuDuong** [comment]
> > @Akintunji Any updates?
> > Appologies my system crashed,As soon as it is up,I will come with update,Appologies!.

Oh. What can I do while waiting for that to be fixed?

**Comment by hemanthsentai** [comment]
Any update on this facing the same issue here

**Comment by krizzu** [comment]
If anyone has a similar issue, please post some more details (Gradle setup), so that we can find the root cause.

**Comment by Akintunji** [comment]
A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
 ERROR  Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.

*Got this on another project after installation of asynchronous storage with
npm install @react-native-async-storage/async-storage

Gradle properties 
buildscript {
    ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31

        if (System.properties['os.arch'] == "aarch64") {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            ndkVersion = "24.0.8215888"
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = "21.4.7075529"
        }
    }

**Comment by krizzu** [comment]
Any chance that you could provide a repo with reproducible issue, so I could have a look?

**Comment by Akintunji** [comment]
It worked again after unistalling and installing again.

**Comment by krizzu** [comment]
Great 👍

**Comment by ChingKhuman** [comment]
It is same as before after uninstalling and installing also for me, Is there any option

**Comment by Monish062003** [comment]
> It is same as before after uninstalling and installing also for me, Is there any option

same here
