### ISSUE TITLE
Storage value persists even after uninstalling the app on Android

### ISSUE THREAD

**Issue by SophieJung7** [react-native-async-storage/async-storage#959]
### What happened?

All the storage values persist even after uninstalling the app on Android. This is not very good because when you install the new app(though it is a same name app), it should start from completely new state. Is there a way to fix this problem? 

### Version

1.17.11

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
System:
    OS: macOS 13.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 715.56 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 16.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.4 => 0.71.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

Easy to reproduce. Set the key value and uninstall the app and install it again and see if the key is there.

**Comment by tido64** [comment]
Hi, please have a look at the answer here: https://github.com/react-native-async-storage/async-storage/discussions/835#discussioncomment-3454228
