### ISSUE TITLE
Storage does not persist on app force close

### ISSUE THREAD

**Issue by TheHeumanModean** [react-native-async-storage/async-storage#962]
### What happened?

Storage does not persist when app force closed on iOS.

[This issue](https://github.com/react-native-async-storage/async-storage/issues/521#issue-782741342) was closed but is not resolved for me, nor is it resolved for others in that thread.

I am not using expo

## Expected 

* Expected data to persist when saved with async storage.

## Actual
* Data only persists when app is refreshed or backgrounded
* Data does not persist when app force closed

I've also tried delaying the loading of the storage with a setTimeout in case it was trying to load value before it could access storage, but there was no behavioral difference.

This is logged in xcode
```
Manifest does not exist - creating a new one.
```

So it seems on iOS at least a new manifest is created (and therefore not loading previously saved data) on start of app every time and that is what causes the value to be null

I do not have time to investigate android as deeply as I did iOS but there could be a similar problem there

### Version

Have tried various between 1.17.3 and 1.18.1

### What platforms are you seeing this issue on?

- [] Android
- [X] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
System:
    OS: macOS 13.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 142.58 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.10.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: 2023.04.03.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 25, 27, 28, 29, 30, 31, 33
      Build Tools: 28.0.3, 29.0.2, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.5 => 0.69.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Code 
```
import AsyncStorage from "@react-native-async-storage/async-storage"

...

  public static async SAVE_STRING(key: string, value: string): Promise<boolean> {
    try {
      console.log("Saving key", key, value)
      await AsyncStorage.setItem(key, value)
      return true
    } catch {
      return false
    }
  }

  public static async LOAD_STRING(key: string): Promise<string | null> {
    try {
      console.log("Loading key", key)
      const value = await AsyncStorage.getItem(key)
      console.log("loaded value", value)
      return value
    } catch {
      console.log("Failed to load string")
      return null
    }
  }
```

## Logs
```
 LOG  Saving key SAVED_USERNAME penguin
 ```
_app is refreshed_
```
 BUNDLE  ./index.js 

 LOG  Loading key SAVED_USERNAME
 LOG  loaded value penguin
```
_app is forcce closed_
```
 BUNDLE  ./index.js 

 LOG  Loading key SAVED_USERNAME
 LOG  loaded value null

```

**Comment by krizzu** [comment]
Seems like there's the old AsyncStorage (from RN) creeping in. iOS has a migration process where it would copy over the old manifest file, if exists, and use it as a current storage destination. This happens on every app launch. 

Make sure there's no other AsyncStorage used except for one from react-native-async-storage org

**Comment by TheHeumanModean** [comment]
> Seems like there's the old AsyncStorage (from RN) creeping in. iOS has a migration process where it would copy over the old manifest file, if exists, and use it as a current storage destination. This happens on every app launch.
> 
> Make sure there's no other AsyncStorage used except for one from react-native-async-storage org

This is the only file in my project that imports AsyncStorage, so thats probably not it. 

I do have some native modules that use persistent storage (not sure how, code is pretty obfuscated), could this be causing conflicts?

**Comment by 1989TomE** [comment]
Hi, I am experiencing the same issue, though I am using Expo. 
`  
"dependencies": {
    "expo": "~48.0.15",
    "@react-native-async-storage/async-storage": "1.17.11",
    "expo-secure-store": "~12.1.1",
  },
`

As @TheHeumanModean described, it works when app resumes (from background), but when it is freshly started (that is when it is really need for persisting users to be logged in), data in storage are always`null`. I tried to use different package [Expo's SecureStore](https://docs.expo.dev/versions/latest/sdk/securestore/) to work around this, but it behaves the same way. I am experiencing this on iOS app installed from Testflight. Not sure if those two can be connected somehow. I has been working for me before updating my project to Expo SDK 48.

**Comment by krizzu** [comment]
@TheHeumanModean are you able to reproduce this on a new project? If not, I'd assume it has to be something related to your project.
Can you spot the issue on android too?

**Comment by TheHeumanModean** [comment]
> @TheHeumanModean are you able to reproduce this on a new project? If not, I'd assume it has to be something related to your project. Can you spot the issue on android too?

@krizzu I was mistaken when I first made this, it seems android is fine and this is just an iOS problem for my project. And no I can't reproduce it in a new project, I know it has something to do with mine, just need to figure out what it is.

I need help understanding why the "manifest" gets recreated with no data on app start so that I can resolve the issue

**Comment by krizzu** [comment]
@TheHeumanModean The "manifest" is a file (JSON) where all key-value values below 5MB are being saved on iOS. When AsyncStorage was extracted from React Native, the location of the manifest file is located has changed. Now we needed the migration code to move files to the new location so that users could work undisturbed. The migration code [removes the old manifest file, once migration is successful](https://github.com/react-native-async-storage/async-storage/blob/main/ios/RNCAsyncStorage.m#L314-L315), so that we know AsyncStorage operates on latest version of it.

We spotted the issue you have where two versions of AsyncStorage and AsyncStorage from RN are used. Old AsyncStorage creates a manifest on app launch and the new one removes it, after migration.

**Comment by TheHeumanModean** [comment]
@krizzu Looking at the comments in that method I don't think it really applies to our project. I've never used react-native/async-storage nor have I used this plugin pre 1.17.3. I put in some logs to confirm my suspicions and sure enough no migration happens

init
```
// Get the path to any old storage directory that needs to be migrated. If multiple exist,
// the oldest are removed and the most recently modified is returned.
NSString *oldStoragePath = RCTGetStoragePathForMigration();
if (oldStoragePath != nil) {
    printf("ASYNC STORAGE, old storage path is NOT nil");
    // Migrate our deprecated path "Documents/.../RNCAsyncLocalStorage_V1" or
    // "Documents/.../RCTAsyncLocalStorage" to "Documents/.../RCTAsyncLocalStorage_V1"
    RCTStorageDirectoryMigrationCheck(
            oldStoragePath, RCTCreateStorageDirectoryPath_deprecated(RCTStorageDirectory), YES);
}
else {
    printf("ASYNC STORAGE, old storage path is nil\n");
}
// Migrate what's in "Documents/.../RCTAsyncLocalStorage_V1" to
// "Application Support/[bundleID]/RCTAsyncLocalStorage_V1"
RCTStorageDirectoryMigrationCheck(RCTCreateStorageDirectoryPath_deprecated(RCTStorageDirectory),
                                      RCTCreateStorageDirectoryPath(RCTStorageDirectory),
                                      NO);
```

RCTStorageDirectoryMigrationCheck
```
if ([fileManager fileExistsAtPath:fromStorageDirectory isDirectory:&isDir] && isDir) {
        printf("ASYNC STORAGE, old storage path does exist and we need to migrate\n");
        ...
else {
        printf("ASYNC STORAGE, old storage path does not exist\n");
}
```
Logs on startup:
> ASYNC STORAGE, old storage path is nil
  ASYNC STORAGE, old storage path does not exist

I think the problem is [here on line 528](https://github.com/react-native-async-storage/async-storage/blob/dc13a8b26e7ea1c86b8937fc88dfb6fe72a4acb8/ios/RNCAsyncStorage.m#LL528C100-L528C100) where data is not serialized because it does not read the file 
```
static NSString *RCTReadFile(NSString *filePath, NSString *key, NSDictionary **errorOut)
{
    if ([[NSFileManager defaultManager] fileExistsAtPath:filePath]) {
        printf("Storage file does exist\n");
        ...
        return entryString;
    }
    printf("Storage file does NOT exist\n");
    
    return nil;
}
```

> Storage file does NOT exist

hit reload 

> Storage file does exist

force close and cold start

> Storage file does NOT exist

I don't know why but it looks like the file you write to and the file you read from differ on cold start, so I logged the file written to and the file read from on the next cold start. And on the simulator they differ!

write 
> /Users/my.username/Library/Developer/CoreSimulator/Devices/0148E0A0-9A01-471F-A676-AD5E08693911/data/Containers/Data/Application/6B2E78F2-865E-450E-A8E8-E55FF7069539/Library/Application Support/redacted.bundle.id/RCTAsyncLocalStorage_V1/manifest.json

read
> /Users/my.username/Library/Developer/CoreSimulator/Devices/0148E0A0-9A01-471F-A676-AD5E08693911/data/Containers/Data/Application/8F1C5550-6E39-45C0-A8BE-CBCD2458E5E9/Library/Application Support/redacted.bundle.id/RCTAsyncLocalStorage_V1/manifest.json

They differ in the application id, (6B2E78F2-865E-450E-A8E8-E55FF7069539 vs 8F1C5550-6E39-45C0-A8BE-CBCD2458E5E9) 

The same thing happens on an actual device

write 
> /var/mobile/Containers/Data/Application/CAA95996-C39C-408A-9228-C68D8F19E00F/Library/Application Support/redacted.bundle.id/RCTAsyncLocalStorage_V1/manifest.json

read
> /var/mobile/Containers/Data/Application/B9966AEA-6A28-4760-A3B6-85C4A9450CB0/Library/Application Support/redacted.bundle.id/RCTAsyncLocalStorage_V1/manifest.json

**so it seems for simulators the reason the data isn't persisting is because you're storing data under a specific application directory that changes from run to run.** 

Is there a way for me to correct this app side? Or is it a bug on the package side that would need to be fixed?
Storage directory name is constructed [here](https://github.com/react-native-async-storage/async-storage/blob/dc13a8b26e7ea1c86b8937fc88dfb6fe72a4acb8/ios/RNCAsyncStorage.m#L129)

It seems very weird that this would only happen to my project

**Comment by krizzu** [comment]
@TheHeumanModean This behavior (different paths for Dodcuments/Library data) exists since iOS 8, [here's the technical note on that](https://developer.apple.com/library/archive/technotes/tn2406/_index.html#//apple_ref/doc/uid/DTS40014932-CH1-LOCCOM). AsyncStorage is implemented in the suggested regards (use system APIs to retrieve the current document location).

>  I've never used react-native/async-storage nor have I used this plugin pre 1.17.3.
My bet would be that one of your dependencies is using AsyncStorage and causing this - I can suggest scanning `node_modules` to see if any library is using AsyncStorage.

**Comment by TheHeumanModean** [comment]
@krizzu 
```
 grep -R --exclude-dir=@react-native-async-storage --include \*.ts --include \*.js "AsyncStorage" node_modules/
```

returns only results from react native, react native types, metro and the actual react-native async storage library

```
node_modules//@types/react-native/index.d.ts: * AsyncStorage is a simple, unencrypted, asynchronous, persistent, key-value storage

 ... More results from same file

node_modules//react-native/Libraries/Storage/AsyncStorage.js:const RCTAsyncStorage = NativeAsyncSQLiteDBStorage || NativeAsyncLocalStorage;

... More results from same file

node_modules//react-native/index.js:  get AsyncStorage(): AsyncStorage {

... More results from same file

node_modules//metro/node_modules/metro-react-native-babel-preset/src/configs/lazy-imports.js:  "AsyncStorage",
node_modules//metro-react-native-babel-preset/src/configs/lazy-imports.js:  "AsyncStorage",
```

So looks like thats not the issue unless you have a better way to find references to that library?

**Comment by krizzu** [comment]
Do you use `.clear` method by any chance somewhere?

Otherwise, I'd try the divide-and-conquer approach, starting with commenting out all imports in `index.js`, so that App would run and test if storage is removed on restart. Then bring back import by import, checking where the issue is reproducible.

**Comment by TheHeumanModean** [comment]
@krizzu issue is with one of our native modules, a minor release from them caused the problem. Of course its a highly obfuscated one so I don't know what caused it. May report back later with info but closing it for now as its not an issue with the async storage package.

**Comment by MohsinChopDawg** [comment]
i am using redux toolkit with redux-persist
value save on android but on ios persist not working properly sometimes gives undefined or sometimes gives me value

**Comment by Inalegwu** [comment]
This is still an issue on ```@react-native-async-storage/async-storage@^1.23.1```` after much troubleshooting, much nothing new has come out of the issue aside what has already been mentioned above
