### ISSUE TITLE
Get this error: Execution failed for task ':react-native-async-storage_async-storage:verifyReleaseResources'.

### ISSUE THREAD

**Issue by shayelbaz1** [react-native-async-storage/async-storage#964]
### What happened?

I try to build my app with `cd android && ./gradlew assembleRelease`

and get this error:

`
> Task :react-native-async-storage_async-storage:verifyReleaseResources FAILED
aapt2 W 05-18 14:51:40 93852 3846600 LoadedArsc.cpp:657] Unknown chunk type '200'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-async-storage_async-storage:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > 1 exception was raised by workers:
     com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
     AAPT: aapt2 W 05-18 14:51:37 93852 3846600 LoadedArsc.cpp:657] Unknown chunk type '200'.
     /Users/user/ls-techs/community-application/node_modules/@react-native-async-storage/async-storage/android/build/intermediates/res/merged/release/layout/autofill_inline_suggestion.xml:18: error: resource attr/autofillInlineSuggestionChip (aka com.reactnativecommunity.asyncstorage:attr/autofillInlineSuggestionChip) not found.
     /Users/user/ls-techs/community-application/node_modules/@react-native-async-storage/async-storage/android/build/intermediates/res/merged/release/layout/autofill_inline_suggestion.xml:25: error: resource attr/autofillInlineSuggestionStartIconStyle (aka com.reactnativecommunity.asyncstorage:attr/autofillInlineSuggestionStartIconStyle) not found.
     /Users/user/ls-techs/community-application/node_modules/@react-native-async-storage/async-storage/android/build/intermediates/res/merged/release/layout/autofill_inline_suggestion.xml:32: error: resource attr/autofillInlineSuggestionTitle (aka com.reactnativecommunity.asyncstorage:attr/autofillInlineSuggestionTitle) not found.
     /Users/user/ls-techs/community-application/node_modules/@react-native-async-storage/async-storage/android/build/intermediates/res/merged/release/layout/autofill_inline_suggestion.xml:41: error: resource attr/autofillInlineSuggestionSubtitle (aka com.reactnativecommunity.asyncstorage:attr/autofillInlineSuggestionSubtitle) not found.
     /Users/user/ls-techs/community-application/node_modules/@react-native-async-storage/async-storage/android/build/intermediates/res/merged/release/layout/autofill_inline_suggestion.xml:50: error: resource attr/autofillInlineSuggestionEndIconStyle (aka com.reactnativecommunity.asyncstorage:attr/autofillInlineSuggestionEndIconStyle) not found.
     error: failed linking file resources.
`

### Version

^1.18.1

### What platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [X] macOS
- [ ] Windows
- [ ] web

### System Information

```true
info Fetching system and libraries information...
System:
    OS: macOS 13.2.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 23.50 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
    Watchman: 2023.04.24.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 23, 25, 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.0, 33.0.1
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

npx react-native@0.64.4 init example --version 0.1

yarn add @react-native-async-storage/async-storage

yarn android

**Comment by krizzu** [comment]
I had to downgrade to java 11 to make it run, but I did not have issues running RN 0.64.4.

Your repro step will not work tho, you have to specify version like this:
`npx react-native init example --version 0.64.4`

I suggest to clean the gradle build, using `./gradlew clean` and trying again.
