### ISSUE TITLE
convertError 「NSCocoaErrorDomain Code=640 “Data” is out of space 」 「NSPOSIXErrorDomain Code=28 No space left on device」

### ISSUE THREAD

**Issue by Lunziyuan** [react-native-async-storage/async-storage#971]
### What happened?

I got error report when some ios user open the app.

Failed to write manifest file.Error Domain=NSCocoaErrorDomain Code=640 "You can’t save the file “manifest.json” because the volume “Data” is out of space." UserInfo={NSFilePath=/var/mobile/Containers/Data/Application/BE5C6DE8-D361-40A6-8BC0-18376C4A5C78/Library/Application Support/XXXXX/RCTAsyncLocalStorage_V1/manifest.json, NSUnderlyingError=0x28370b960 {Error Domain=NSPOSIXErrorDomain Code=28 "No space left on device"}}

the error is report form 

/node_modules/@react-native-async-storage/async-storage/src/helpers.ts',
  line: 49,
  column: 29,
  name: 'error'
}

### Version

1.17.11

### What platforms are you seeing this issue on?

- [ ] Android
- [X] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M2
    Memory: 1.62 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.6 - ~/.nvm/versions/node/v16.19.0/bin/npm
    Watchman: 2023.03.27.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.5 => 0.67.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

some ios user open the app

**Comment by harleenarora** [comment]
same error

**Comment by Norcy** [comment]
same

**Comment by aqigif** [comment]
same, how to handle this?
