### ISSUE TITLE
The new update has automatically increased the load time of the application.

### ISSUE THREAD

**Issue by A4Dragon** [react-native-async-storage/async-storage#974]
### What happened?

As the new release has arrived my load time of application has increased from 3 to 7 second. Also in the previous builds I think there is something wrong with the server 

### Version

1.18.0

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
Dell vostro i5
```

### Steps to Reproduce

Just install the async storage with the new react native

**Comment by tido64** [comment]
Hi, I don't know how you arrived at AsyncStorage being the culprit for slowing down your app startup:

- Did you do any profiling to see where the time is spent?
- What's the setup of your app?
- What version of React Native are you using?
- Are you using New Architecture?

Can you provide a minimal repro? Your steps doesn't provide enough information for us to help you.
