### ISSUE TITLE
Subproject ':react-native-async-storage' is outside of the project root. This behaviour has been deprecated and is scheduled to be removed in Gradle 8.0.

### ISSUE THREAD

**Issue by hasbelcaro** [react-native-async-storage/async-storage#975]
### What happened?

I try to build my app with cd android && ./gradlew assembleRelease and get this error:

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

When I execute this ./gradlew --warning-mode=all get this:

> Configure project :react-native-async-storage
Subproject ':react-native-async-storage' has location '/Users/hasbel/Documents/Hasbel/Mobile/ReactNative/SdkDespachos/node_modules/@react-native-async-storage/async-storage' which is outside of the project root. This behaviour has been deprecated and is scheduled to be removed in Gradle 8.0. Consult the upgrading guide for further information: https://docs.gradle.org/7.3.3/userguide/upgrading_version_7.html#deprecated_flat_project_structure

> Configure project :react-native-async-storage_async-storage
Subproject ':react-native-async-storage_async-storage' has location '/Users/hasbel/Documents/Hasbel/Mobile/ReactNative/SdkDespachos/node_modules/@react-native-async-storage/async-storage/android' which is outside of the project root. This behaviour has been deprecated and is scheduled to be removed in Gradle 8.0. Consult the upgrading guide for further information: https://docs.gradle.org/7.3.3/userguide/upgrading_version_7.html#deprecated_flat_project_structure

### Version

"@react-native-async-storage/async-storage": "^1.17.3"

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
info Fetching system and libraries information...
System:
    OS: macOS 12.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 41.27 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: 2023.03.27.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.5.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK:
      API Levels: 23, 27, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0, 32.0.0
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 16.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

cd android && ./gradlew clean && ./gradlew assembleRelease

**Comment by tido64** [comment]
Hi, those are warnings and shouldn't have caused your build to fail. Can you please post the full logs?

**Comment by hasbelcaro** [comment]
Hi, There were some duplicate resources in the project that were solved whit this commands

rm -rf ./android/app/src/main/res/drawable-*
rm -rf ./android/app/src/main/res/raw

Thank you
