### ISSUE TITLE
CocoaPods could not find compatible versions for pod "RNCAsyncStorage"

### ISSUE THREAD

**Issue by ravindraguptacapgemini** [react-native-async-storage/async-storage#982]
### What happened?

After the recent update of 1.19.0, the pod install command started to fail.

Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
RNFBApp: Using overridden static_framework value of 'true'
RNFBMessaging: Using overridden static_framework value of 'true'
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
[!] CocoaPods could not find compatible versions for pod "RNCAsyncStorage":
  In Podfile:
    RNCAsyncStorage (from `../node_modules/@react-native-async-storage/async-storage`)

Specs satisfying the `RNCAsyncStorage (from `../node_modules/@react-native-async-storage/async-storage`)` dependency were found, but they required a higher minimum deployment target.

### Version

1.19.0

### What platforms are you seeing this issue on?

- [ ] Android
- [X] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
RCT_NEW_ARCH_ENABLED=1 pod install
```

### Steps to Reproduce

Just run pod install command

**Comment by tido64** [comment]
What is `IPHONEOS_DEPLOYMENT_TARGET` currently set to? If you enabled New Arch, you will also need to bump it to at least 13.4:

https://github.com/react-native-async-storage/async-storage/blob/d30a69f2eb2c77a8e41a82129a1e5729c1efb015/RNCAsyncStorage.podspec#L26

**Comment by Sowed** [comment]
Thank you so much @tido64

**Comment by felipegmg** [comment]
Is there any problem if I need to downgrade the iOS platform to 13.0?

**Comment by jorgegvallejo** [comment]
> What is `IPHONEOS_DEPLOYMENT_TARGET` currently set to? If you enabled New Arch, you will also need to bump it to at least 13.4:
> 
> https://github.com/react-native-async-storage/async-storage/blob/d30a69f2eb2c77a8e41a82129a1e5729c1efb015/RNCAsyncStorage.podspec#L26

My podspec file was already set to 13.4 and pod install wasn't working. What worked for me was doing `pod update` then doing the `pod install` again
