### ISSUE TITLE
Android Analyzer Flag: Column Name 'key' Issue in ReactDatabaseSupplier

### ISSUE THREAD

**Issue by abuciuman** [react-native-async-storage/async-storage#999]
### What happened?

While using the Android Analyzer on my project which incorporates `react-native-async-storage/async-storage`, I encountered the following error:
`<column definition name> expected, got 'key'`

![Screenshot 2023-08-09 at 10 32 19](https://github.com/react-native-async-storage/async-storage/assets/137059906/b01fa6ef-9ffe-45fa-a28a-0c15b7024de1)

### Version

1.17.11

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 71.50 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.7 - /opt/homebrew/bin/npm
    Watchman: 2023.07.10.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.12 => 0.71.12
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

Run Android Analyzer from Android Studio on the project.
Observe the mentioned error related to the ReactDatabaseSupplier.java file.

**Comment by krizzu** [comment]
That's not an error, but IDE warning/lint. Feels like some sort of plugin or something is highlighting this.
